pulumi/pulumi-hugo

themes/default/content/docs/troubleshooting/_index.md
Proposed changes
Added information on how to update the provider if you're running an M1 MBP and you see an error message with a 403 HTTP status code:
=> Updated troubleshooting doc

themes/default/content/docs/get-started/install/_index.md
Port of https://github.com/pulumi/docs/pull/4384.
=> Documenting MacPorts install option

themes/default/content/docs/tutorials/kubernetes/eks.md
Fixes: https://github.com/pulumi/docs/issues/5437
=> Update yaml file from which eks tutorial uses

.gitignore, themes/default/assets/sass/_pulumi-up.scss, themes/default/content/pulumi-up/_index.md, themes/default/content/resources/ask-the-expert/index.md, themes/default/content/resources/getting-started-with-automation-api/index.md, themes/default/content/resources/getting-started-with-azure-native/index.md, themes/default/content/resources/introduction-to-pulumi/index.md, themes/default/layouts/page/pulumi-up.html
This PR adds the follow-up events for PulumiUP and lists them on the PulumiUP landing page.
=> Add PulumiUP follow up events

themes/default/content/pulumi-up/_index.md, themes/default/content/resources/getting-started-with-automation-api/index.md, themes/default/content/resources/getting-started-with-azure-native/index.md, themes/default/content/resources/introduction-to-pulumi/index.md, themes/default/layouts/page/pulumi-up.html
This PR updates some of the workshop names, adds a workshop to the list, and adds a callout for the Clubhouse after party.
=> PulumiUP workshops and after party updates

Makefile, README.md, scripts/test.sh, themes/default/content/blog/pulumiup/index.md, themes/default/content/docs/intro/concepts/inputs-outputs.md, themes/default/content/resources/getting-started-with-automation-api/index.md, themes/default/content/resources/getting-started-with-azure-native/index.md
Fixes some failing lint checks and enables the `lint` and `test` targets for pull requests.
=> Fix and enable tests

themes/default/content/docs/guides/testing/integration.md
#50 had lint errors, so this PR fixes those errors.
=> Fixed lint errors and matched example code with example reference

themes/default/content/docs/intro/console/ci-cd-integration-assistant.md, themes/default/layouts/page/pricing.html
this should hold until the changes are released to the console in https://github.com/pulumi/pulumi-service/issues/6498
fixes #47
=> update cicd docs

themes/default/content/docs/get-started/_index.md
First stage of updating the Getting Started page is to bring in content about the "Intro to Pulumi" live workshops.
Also redesigned the page a bit to set up for adding other learning options such as video walkthroughs and interactive workshops (when ready).
=> Update Getting Started page to incorporated other learning options

themes/default/data/newsroom.toml, themes/default/layouts/page/pricing-oss.html
=> add link to press release

themes/default/content/docs/get-started/azure/create-project.md
Instead of dumping 13k+ lines of JSON to the console, display a clean table
```
➜  ~ az account list-locations --output table
DisplayName               Name                 RegionalDisplayName
------------------------  -------------------  -------------------------------------
East US                   eastus               (US) East US
East US 2                 eastus2              (US) East US 2
South Central US          southcentralus       (US) South Central US
West US 2                 westus2              (US) West US 2
Australia East            australiaeast        (Asia Pacific) Australia East
Southeast Asia            southeastasia        (Asia Pacific) Southeast Asia
North Europe              northeurope          (Europe) North Europe
UK South                  uksouth …
```
=> human readable az cli location output

themes/default/assets/sass/_header.scss, themes/default/layouts/partials/banner.html
=> Update banner for the 3.0 launch

themes/default/content/resources/azure-cosmos-db-conference-2021/index.md, themes/default/content/resources/introduction-to-pulumi/index.md, themes/default/content/resources/modern-devops-automation-with-octopus/index.md, themes/default/layouts/partials/banner.html
Just as the title states, nothing fancy here.
=> Remove old events from listings and update copy on the top banner

themes/default/content/cloud-engineering/_index.md
Fixes: https://github.com/pulumi/pulumi-hugo/issues/115
=> Update /cloud-engineering meta description

themes/default/content/resources/ask-the-expert/index.md, themes/default/content/resources/getting-started-with-automation-api/index.md
Just as the title states this PR adds the recording to our latest Automation API workshop
=> Update Automation API workshop with recording

themes/default/content/resources/getting-started-with-azure-native/index.md
We had some technical issues with our webinar provider this morning so we need to push the workshop out one day. This PR updates the copy on the website.
=> Update azure workshop date

themes/default/content/docs/intro/cloud-providers/_index.md, themes/default/content/docs/intro/cloud-providers/libvirt/_index.md
=> Adding Libvirt provider to cloud-providers page

themes/default/assets/config/postcss.config.js, themes/default/assets/sass/_buttons.scss, themes/default/assets/sass/_card.scss, themes/default/assets/sass/_header.scss, themes/default/assets/sass/_hero.scss, themes/default/assets/sass/_hubspot.scss, themes/default/assets/sass/_marketing.scss, themes/default/assets/sass/_mixins.scss, themes/default/layouts/crosswalk/aws.html, themes/default/layouts/crosswalk/kubernetes.html, themes/default/layouts/partials/learnmore-contactus.html
* Make a `gradient-button` mixin with support for transitions
* Apply some styles to the buttons in the `learnmore-contactus` partial
* Add a bit of margin between the Download button icon and label
* Extend the default transition duration to 120ms
* Remove some unused styles
* Remove some no-longer-needed punctuation
fixes #127
=> Fix up some button things

themes/default/content/blog/pulumiup-pulumi-packages-multi-language-components/index.md
Left in a TODO that needs to be removed
=> Fix unneeded TODO in Pulumi Packages blog post

themes/default/content/docs/intro/cloud-providers/azure/_index.md, themes/default/content/docs/intro/cloud-providers/azure/version-guide.md
Resolve https://github.com/pulumi/pulumi-azure-native/issues/557
=> Azure Native Version Guide

themes/default/content/_index.md
replaced one of the tweets with one from claudiordgz
=> Updated one tweet

themes/default/layouts/partials/header.html
WIth Docs as a top-level item now, we can remove it from Learn.
=> Remove Docs from the Learn menu

themes/default/content/blog/getting-started-with-k8s-part3/index.md
The URL to the file changed in https://github.com/microservices-demo/microservices-demo/commit/6660538af760d16175cf4d172e17bb4292d33dc5.
=> Fix a broken link

themes/default/layouts/shortcodes/changelog-table-row.html
=> Add the ability for the user to see the checksums download link

themes/default/content/blog/pinpoint/index.md
These are now 404ing and there don't seem to be replacements.
=> Unlink Pinpoint authors

themes/default/content/docs/intro/cloud-providers/azure/_index.md
Fixes pulumi/pulumi-azure-native#601
=> Add blurb about Azure SDK integration

themes/default/content/docs/reference/cli/environment-variables.md
Related to: https://github.com/pulumi/pulumi/pull/6882
=> Add PULUMI_AUTOMATION_API_SKIP_VERSION_CHECK var

themes/default/content/docs/intro/cloud-providers/libvirt/_index.md
=> Add the libvirt binary requirement on the cloud provider page

themes/default/content/resources/ask-the-expert/index.md, themes/default/content/resources/aws-dev-day-building-a-kubernetes-platform/index.md, themes/default/content/resources/aws-howdy-partner-twitch-2020-06-01/index.md, themes/default/content/resources/aws-howdy-partner-twitch/index.md, themes/default/content/resources/build-reusable-infrastructure-as-code-patterns/index.md, themes/default/content/resources/cncf-live-building-your-dream-cloud-native-platform/index.md, themes/default/content/resources/getting-started-with-automation-api/index.md, themes/default/content/resources/getting-started-with-azure-native/index.md, themes/default/content/resources/getting-started-with-google-cloud-platform/index.md, themes/default/content/resources/kubecon-eu-2021/index.md, themes/default/content/resources/multicloud-oss-database-deployments-with-aiven/index.md
Just as the title states I cleaned up the old event listings and then added new ones based on the Marketing calendar.
@jaxxstorm I used the descriptions from the doc you wrote but I know people are actively tweaking the descriptions. We really need to get the reg forms open so we can promote these workshops, so hopefully you are ok with shipping this as-is and updating as necessary.
=> Clean up the webinar/event listings and add upcoming events.

themes/default/content/docs/intro/cloud-providers/kubernetes/_index.md, themes/default/content/docs/tutorials/kubernetes/aks.md
Fixes https://github.com/pulumi/docs/issues/5188 and https://github.com/pulumi/docs/issues/5488.
=> Updated AKS tutorial to Azure Native provider, updated instructions and links

themes/default/content/docs/guides/testing/unit.md
The current example is invalid C#
=> Fix C# unit testing snippet with mocks

themes/default/assets/config/postcss.config.js, themes/default/assets/sass/_api-nodejs.scss
The preview for https://github.com/pulumi/docs/pull/6081 revealed a couple of places in the docs that still needed fixing after the Tailwind v2 upgrade. This should fix things up. (We'll need to merge this PR in order to unblock that one.)
=> Fix a couple of Tailwind upgrade bugs

themes/default/content/docs/guides/pulumi-packages/_index.md, themes/default/content/docs/guides/pulumi-packages/schema.md
=> Add Pulumi Package Schema documentation

themes/default/content/docs/intro/cloud-providers/gitlab/_index.md
Signed-off-by: Noel Georgi <git@frezbo.dev>
=> Update GitLab go provider version to v4

themes/default/content/docs/intro/cloud-providers/github/setup.md
Signed-off-by: Noel Georgi <git@frezbo.dev>
=> Fix variable name

themes/default/content/docs/guides/continuous-delivery/github-actions.md
Fixes: https://github.com/pulumi/docs/issues/6041
=> Add other languages to GitHub Actions Guide

themes/default/content/resources/7-things-executives-can-learn-from-software-engineers/index.md, themes/default/content/resources/ask-the-expert/index.md, themes/default/content/resources/aws-howdy-partner-twitch/index.md, themes/default/content/resources/getting-started-with-google-cloud-platform/index.md, themes/default/content/resources/introduction-to-pulumi/index.md, themes/default/content/resources/jfrog-swampup-2021/index.md, themes/default/content/resources/move-fast-and-dont-break-things/index.md, themes/default/content/resources/securing-the-gitops-workflow/index.md
Just as the title states, this PR cleans up some of the older events and adds some more external events.
=> Update workshop listings and external events

themes/default/layouts/page/solutions.html
=> Fix heading wrapping on Solutions page

themes/default/content/case-studies/lykke.md, themes/default/layouts/case-studies/list.html
This PR adds the Lykke case study and lists the Kenshoo blog post on the case studies page. 
Broken out from this PR: https://github.com/pulumi/pulumi-hugo/pull/232
=> Add lykke case study

themes/default/layouts/case-studies/single.html
Just as the title states, this PR updates the text for the description of Pulumi at the bottom of each case study.
=> Update case study footer

themes/default/data/team/team/hitesh-boinpally.toml
Fixes https://github.com/pulumi/docs/issues/6136.
=> Remove Hitesh from the Team page

themes/default/content/docs/guides/continuous-delivery/_index.md
Unblocks https://github.com/pulumi/docs/pull/6138.
=> Fix a broken relref

themes/default/content/docs/guides/crosswalk/aws/lambda.md
=> Fix incorrect example using new with get in Crosswalk example

themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md
Just as the title states.
Fixes: https://github.com/pulumi/marketing/issues/44
=> Fix typo in NGINX livestream abstract

themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md
=> Remove link from NGNIX livestream and update duration

themes/default/content/resources/build-reusable-infrastructure-as-code-patterns/index.md, themes/default/content/resources/move-fast-and-dont-break-things/index.md, themes/default/content/resources/securing-the-gitops-workflow/index.md
This PR adds the recording for the "Building Reusable Infra" workshop and removes two past external webinar links.
=> Add recording for "Building Reusable Infra" workshop

themes/default/content/case-studies/fenergo.md
Just as the title states, this PR adds the Fenergo case study.
=> Add fenergo case study

themes/default/content/docs/intro/console/accounts.md, themes/default/content/docs/intro/console/auditing.md, themes/default/content/docs/intro/console/ci-cd-integration-assistant.md, themes/default/content/docs/intro/console/organization-roles.md, themes/default/content/docs/intro/console/organizations.md, themes/default/content/docs/intro/console/project-and-stack-management.md, themes/default/content/docs/intro/console/pulumi-button.md, themes/default/content/docs/intro/console/teams.md, themes/default/content/docs/intro/console/webhooks.md
fixes #345
pls note im not adding any new content in this pr, i am changing instructional steps that are presented in paragraphs to lists to make them easier to consume and use, more details in #345 issue description.
=> console docs: change instructional steps to lists

themes/default/content/docs/intro/console/project-and-stack-management.md, themes/default/content/docs/intro/console/webhooks.md
adding stack transfer docs
fixes #308 and is in follow-up to https://github.com/pulumi/pulumi-hugo/pull/307
=> add stack transfer docs

themes/default/layouts/page/pricing.html
a few tiny things to clean up on the pricing page.
one plan -> edition, and link text fixes mostly.
=> small cleanup on pricing page

themes/default/data/team/team/dave-wrede.toml, themes/default/data/team/team/sean-holung.toml
😢 
Fixes https://github.com/pulumi/docs/issues/6155.
=> Remove Sean and Dave

themes/default/layouts/page/pricing.html
This PR adds a sentence above the fold on the pricing page that describes the relation between the service and the SDK, as request by @joeduffy.
=> Add description above the fold on the pricing page

themes/default/content/docs/intro/cloud-providers/azure/version-guide.md
Resolve https://github.com/pulumi/pulumi-hugo/issues/389
=> Mention provider's returned versions in Azure Native Version Guide

themes/default/content/docs/intro/concepts/resources.md
=> Fix a bad reference in the Python custom-resources doc

themes/default/content/case-studies/atlassian.md
Some last minute edits to the copy of the Atlassian case study.
=> Copy edits to Atlassian case study

themes/default/content/blog/inside-crosswalk-for-kubernetes/index.md, themes/default/content/blog/kubernetes-anti-patterns/index.md, themes/default/content/docs/guides/continuous-delivery/spinnaker.md
The plugin creator guide has moved
=> Fix some broken links

themes/default/content/_index.md
Unfortunately, I couldn't find this in the rawkode's timeline either, so I couldn't find a suitable replacement.
=> Remove tweet that's no longer available

themes/default/content/docs/intro/concepts/state.md
=> fixes link from state to secrets

themes/default/content/resources/getting-started-with-azure-native/index.md
This PR adds the azure workshops for August 2021.
=> Add august 2021 azure workshops

themes/default/content/docs/tutorials/aws/ec2-webserver.md, themes/default/content/docs/tutorials/aws/ecs-fargate.md, themes/default/content/docs/tutorials/kubernetes/guestbook.md, themes/default/layouts/shortcodes/github-buttons.html
Fixes some missing buttons and updates the shortcode to make it more flexible.
Fixes #409.
=> Fix multi-lang tutorial buttons

themes/default/content/resources/7-things-executives-can-learn-from-software-engineers/index.md, themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md, themes/default/layouts/partials/banner.html
Just as the title states this PR updates the banner on the website and cleans up some older events.
=> Update site banner to CES and clean up older events

themes/default/assets/sass/_hero.scss
Fixes: https://github.com/pulumi/pulumi-hugo/issues/387
This PR reduces the size of the non home page hero sections.
=> Reduce size of non home page hero sections

themes/default/content/resources/getting-started-with-azure-native/index.md
Fixes: https://github.com/pulumi/marketing/issues/45
=> Add Mikhail as speaker for azure workshops

themes/default/content/blog/top-5-things-for-azure-devs-intro/index.md, themes/default/content/blog/top-5-things-for-azure-devs-serverless/index.md, themes/default/content/blog/top-5-things-for-azure-devs-vm/index.md
We would like to schedule this out for next week, so marking them as draft mode for now
=> Move azure blog series to draft

themes/default/content/blog/top-5-things-for-azure-devs-intro/index.md
This was supposed to be published last week but was delayed to this week. It was already approved.
=> [Blog] Top 5 Things an Azure Developer Needs to Know: Introduction

themes/default/content/resources/azurefunbytes-infrastructure-as-code/index.md, themes/default/content/resources/getting-from-code-to-cloud-with-vscode-and-pulumi/index.md, themes/default/content/resources/getting-started-with-automation-api/index.md, themes/default/content/resources/getting-started-with-azure-native/index.md, themes/default/layouts/page/cloud-engineering-summit.html
This PR updates some event listings and details for upcoming events in the next two quarters.
Fixes: https://github.com/pulumi/marketing/issues/47
=> Update webinars and add new workshops for aug 2021

themes/default/content/blog/kenshoo-migrates-to-aws-with-pulumi/index.md
Kenshoo rebranded to Skai, so we need to change the name in this blog post.
=> Update Kenshoo's branding

themes/default/content/_index.md
Replace Ware2Go with SANS logo
=> Add SANS logo

themes/default/content/docs/intro/cloud-providers/signalfx/_index.md
=> Add correct link to SignalFx

themes/default/content/docs/intro/cloud-providers/openstack/_index.md
=> Fixup openstack cloudproviders page

themes/default/layouts/page/pricing.html
The answer to this FAQ is confusing some customers per feedback from the CE team. People do not know what "production" means, the number of environments chosen in each scenario seems to cause confusion, and the wording around "deployment" also seems to throw people off. 
I revised the answer to make it less ambiguous and more consistent.
=> Revise pricing FAQ "how many credits will I need?"

themes/default/content/resources/aws-reinvent-2021/index.md, themes/default/content/resources/getting-started-with-azure-native/index.md, themes/default/content/resources/gettint-started-with-aws/index.md, themes/default/content/resources/kubecon-na-2021/index.md
This PR adds the upcoming AWS workshops, Kubecon, and re:Invent listings to the website.
=> Add upcoming aws workshops, kubecon, reinvent

themes/default/content/resources/azurefunbytes-infrastructure-as-code/index.md, themes/default/content/resources/getting-started-with-automation-api/index.md, themes/default/content/resources/getting-started-with-azure-native/index.md, themes/default/content/resources/gettint-started-with-aws/index.md
This PR updates the details of some workshops and removes ones that have already happened.
=> Update workshop details and remove old workshops

themes/default/content/blog/top-5-things-for-azure-devs-kubernetes-apps/index.md
https://github.com/pulumi/docs/runs/3363187366 failed due to a link with a trailing slash - fixing that here
=> Fix Kubernetes link

themes/default/layouts/partials/banner.html
Fixes: https://github.com/pulumi/marketing/issues/48
=> Update Cloud Engineering Summit banner text

themes/default/content/docs/guides/pulumi-packages/schema.md
Add `methods` property to table of Resource properties.
Fixes #521
=> Update Pulumi Package schema docs for methods

themes/default/content/resources/developerweek-global-cloud/index.md, themes/default/content/resources/docker-show-multi-language-components/index.md, themes/default/content/resources/nginx-deploy-kubernetes-and-the-kitchen-sink/index.md
Fixes: https://github.com/pulumi/marketing/issues/49
=> Add upcoming events for Sept/Oct

themes/default/content/topics/why-is-python-so-popular.md
https://insights.stackoverflow.com/survey/2020#technology-most-loved-dreaded-and-wanted-languages-loved
"% of developers who are developing with the language or technology and have expressed interest in continuing to develop with it"
Possibly some other statistic may better fit this article.
=> Corrected incorrect statement about Python popularity

themes/default/content/topics/why-is-python-so-popular.md
I saw this PR https://github.com/pulumi/pulumi-hugo/pull/486, which I then broke again. This fixes it.
=> Change dev to dev who worked extensively

themes/default/content/docs/intro/console/organizations.md, themes/default/layouts/page/pricing.html
its not super clear to folks that when they create a new organization it means a new subscription (unless they have a custom invoiced plan that accounts for it)
some convo about this in this [internal slack thread](https://pulumi.slack.com/archives/C8A7QG1CZ/p1630289756004200)
=> improve messaging related to orgs and subscriptions

themes/default/assets/sass/_notes.scss
=> make note styles accessible and align them to the new brand colors

themes/default/content/resources/building-event-driven-communications-with-twilio-and-aws/index.md, themes/default/content/resources/developerweek-global-cloud/index.md, themes/default/content/resources/scale-kubernetes-on-any-cloud-with-spot/index.md, themes/default/layouts/page/cloud-engineering-summit.html
Just some date fixes and updated links.
Fixes: https://github.com/pulumi/marketing/issues/51
=> Fix some event dates and registration links

themes/default/data/team/team/sophia-parafina.toml
Removes Sophia from the team. 😢
=> Update the About page

themes/default/content/docs/intro/concepts/secrets.md
=> Corrects GCP KMS ID structure

themes/default/content/cloud-engineering-summit/agenda.md, themes/default/content/cloud-engineering-summit/speakers.md, themes/default/layouts/page/cloud-engineering-summit-agenda.html, themes/default/layouts/page/cloud-engineering-summit-speakers.html, themes/default/layouts/page/cloud-engineering-summit.html
This PR adds the agenda and speaker pages for the Cloud Engineering Summit.
=> Add agenda and speakers pages for the Cloud Engineering Summit

themes/default/data/newsroom.toml
add SANS and Atlassian announcements
=> Update the newsroom with new press releases

themes/default/assets/sass/_header.scss
=> fix invisible get started button in top nav

themes/default/content/docs/guides/pulumi-packages/schema.md
Update the schema property table for `replaceOnChanges`.
Fixes #570
=> Add entry for replaceOnChanges

themes/default/content/cloud-engineering-summit/_index.md, themes/default/content/resources/build-reusable-infrastructure-as-code-patterns/index.md, themes/default/content/resources/developerweek-global-cloud/index.md, themes/default/content/resources/docker-show-multi-language-components/index.md, themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md, themes/default/content/resources/getting-started-with-automation-api/index.md, themes/default/content/resources/getting-started-with-aws/index.md, themes/default/content/resources/getting-started-with-azure-native/index.md, themes/default/content/resources/getting-started-with-google-cloud-platform/index.md, themes/default/layouts/page/cloud-engineering-summit.html
This pR adds the workshops for the Cloud Engineering Summit and lists them on the landing page as well.
=> Add Cloud Engingeering Summit workshops

themes/default/components/src/components/convert/convert.tsx
This should have no material changes to existing converters.
=> Component changes for new converter

themes/default/content/partner/azure-infrastructure-as-code.md, themes/default/content/partner/azure.md, themes/default/content/what-is/infrastructure-as-code-for-devops.md, themes/default/content/what-is/infrastructure-as-code-for-kubernetes.md, themes/default/content/what-is/javascript-and-infrastructure-as-code.md, themes/default/content/what-is/python-for-devops.md, themes/default/layouts/partner/azure.html
Fixes https://github.com/pulumi/pulumi-hugo/issues/614
Fixes https://github.com/pulumi/pulumi-hugo/issues/609
Fixes https://github.com/pulumi/pulumi-hugo/issues/595
Fixes https://github.com/pulumi/pulumi-hugo/issues/594
Fixes https://github.com/pulumi/pulumi-hugo/issues/630
=> Add SEO topic pages to `what-is` 

themes/default/content/docs/reference/service-rest-api/_index.md
- Added webhook REST API to docs
- Set access token to be $PULUMI_ACCESS_TOKEN
=> Updated REST API docs to include webhooks

themes/default/layouts/index.html, themes/default/layouts/page/cloud-engineering-summit.html
Fixes: https://github.com/pulumi/pulumi-hugo/issues/648
=> Add secondary CTA for summit to home hero

themes/default/layouts/index.html
Happened to notice this while fixing another bug -- little thing, but my eyes couldn't look past it. 😂
=> Center the CES button

themes/default/content/blog/announcing-aws-native/index.md, themes/default/content/docs/intro/cloud-providers/aws-native/_index.md
- Fix gcp link
- Add all languages to AWS Native blog example
=> Make AWS Native example multi-language

themes/default/data/newsroom.toml
Add press release for AWS Native
=> Update newsroom for AWS Native

themes/default/layouts/partials/banner.html
fixing up the link text so its consumable outside the rest of the text
=> fix cloud eng summit banner link text

themes/default/content/resources/nginx-deploy-kubernetes-and-the-kitchen-sink/index.md
Fixes: https://github.com/pulumi/marketing/issues/56
=> Update date of NGINX live stream and embed the stream

themes/default/assets/sass/components/_banner.scss, themes/default/layouts/partials/banner.html, themes/default/layouts/partials/header.html
Fixes https://github.com/pulumi/pulumi-hugo/issues/686
=> Add top banner for Cloud Engineering Summit

themes/default/layouts/partials/header.html
Fixes https://github.com/pulumi/pulumi-hugo/issues/686
=> Update text of CES site banner

themes/default/content/docs/guides/pulumi-packages/contribute-to-pulumi-registry.md
Related to https://github.com/pulumi/registry/issues/78
=> Add contribution landing page

themes/default/content/product/packages.md
Reducing word count for better readability
=> Edits to Pulumi Packages page copy

themes/default/content/docs/guides/crosswalk/aws/_index.md
Fixes https://github.com/pulumi/docs/issues/3565
=> Update Crosswalk guide example to match text

themes/default/content/docs/get-started/aws/modify-program.md
Fixes #790 
@justinvp @komalali I want to at least fix the example so this type checks correctly, but I'm wondering how the codegen in Node does this "correctly" (i.e. you can pass in the resource itself) and if we should extend that same support to Python?
=> Update modify-program to type check correctly

themes/default/layouts/page/about.html
We've been discussing this for a while now but understandably haven't been able to carve out the time due to lots of other priorities. My design skills are quite poor but I think it's an okay start.
I also slightly editorialized the values so they fit more cleanly on the page (we probably want to edit the internal doc down a little bit too, as it's a tad more verbose than it needs to be.)
=> Add company values to the about page

themes/default/data/team/team/kevin-kotecki.toml, themes/default/data/team/team/komal-ali.toml
For an auto-assigned offboarding task.
=> Update the Team page

themes/default/content/docs/reference/service-rest-api/_index.md
Added API docs for Granting and removing team stack access.
=> Add team stack access apis

themes/default/layouts/partials/header.html
=> repeat case studies in the learn menu

themes/default/layouts/partials/docs/toc.html
fixes https://github.com/pulumi/pulumi-hugo/issues/826
=> add data tracking ids to docs toc nav items

themes/default/content/blog/pulumi-recommended-patterns-the-basics/index.md
Happened to notice while doing some local testing.
=> Fix a relref

themes/default/content/resources/automation-devops-summit-2021/index.md, themes/default/content/resources/deploy-digital-ocean-2021/index.md, themes/default/content/resources/ndc-oslo-2021/index.md
Just as the title states, just adding some upcoming events to the listing.
=> Update events for Nov 2021

themes/default/content/learn/building-with-pulumi/_index.md, themes/default/content/learn/pulumi-fundamentals/configure-and-provision/index.md, themes/default/content/learn/pulumi-fundamentals/create-docker-images/index.md
=> Patch links for Learn launch

themes/default/layouts/page/about.html
This change makes it clearer that we're a remote-first company!
=> Add a remote-first callout

themes/default/content/docs/troubleshooting/faq.md
@jaxxstorm wrote a great blog post https://www.leebriggs.co.uk/blog/2021/11/06/pulumi-faqs.html and i worked with him to distill some of that information into new faqs. at the same time i also noticed some issues on the faq page, so i cleaned up a few questions and also grouped them together into sections.
additionally i created a follow-up issue to use accordions to make the page even easier to navigate https://github.com/pulumi/pulumi-hugo/issues/836
i am fully open to feedback of any kind, pls let me know if i got anything wrong or if you have ideas to make it even better.
✨ also important note ✨ i moved stuff around which makes the files changed difficult to read, it may be helpful to read the current page: https://www.pulumi.com/docs/troubleshooting/faq/, then reference the preview …
=> faq cleanup and additions

themes/default/content/docs/guides/pulumi-packages/_index.md, themes/default/content/docs/guides/pulumi-packages/how-to-author.md, themes/default/content/docs/guides/pulumi-packages/schema.md
Related to https://github.com/pulumi/docs/issues/5943
Fixes https://github.com/pulumi/pulumi/issues/6954
=> How to: author a Pulumi Package

themes/default/layouts/partials/banner.html
Update the banner from cloud engineering summit to the Registry.
=> Refresh homepage banner with Registry announcement

themes/default/content/docs/get-started/azure/review-project.md, themes/default/content/docs/guides/adopting/from_aws.md, themes/default/content/docs/guides/crosswalk/aws/eks.md, themes/default/content/docs/guides/crosswalk/aws/vpc.md, themes/default/content/docs/guides/crosswalk/kubernetes/apps.md, themes/default/content/registry/packages/aws/how-to-guides/ec2-webserver.md
Context: https://github.com/pulumi/pulumi/issues/7946
Prerequisites before this can be merged:
=> Update conceptual docs for use fnOutput feature

themes/default/content/resources/aws-howdy-partner-twitch/index.md, themes/default/content/resources/deploy-serverless-containers-using-azure-container-apps/index.md, themes/default/content/resources/pulumipustv-fun-with-datadog-with-dan-maher/index.md
Fixes https://github.com/pulumi/marketing/issues/62
Datadog Email: https://app.hubspot.com/email/4429525/details/59620749235/performance
Howdy Partner Email: https://app.hubspot.com/email/4429525/details/59620690837/performance
=> Add upcoming events for December 2021

themes/default/content/resources/aws-howdy-partner-twitch/index.md, themes/default/content/resources/pulumipustv-fun-with-datadog-with-dan-maher/index.md
=> Fix typos on devember 2021 events

themes/default/content/docs/guides/crosswalk/aws/cloudwatch.md
Fixes: https://github.com/pulumi/pulumi-hugo/issues/835
=> Add optimization suggestions for cloudwatch crowsswalk page

themes/default/content/docs/guides/continuous-delivery/github-actions.md, themes/default/content/docs/guides/continuous-delivery/github-app.md, themes/default/content/docs/intro/languages/dotnet.md, themes/default/content/docs/intro/languages/go.md, themes/default/content/docs/intro/languages/javascript.md, themes/default/content/docs/reference/cli/_index.md
randomly noticed these buttons that still had all caps, this fixes it.
=> remove all caps from button text

themes/default/content/resources/pulumipustv-fun-with-datadog-with-dan-maher/index.md
Fixes https://github.com/pulumi/marketing/issues/62
=> Fix timezone on datadog livestream

themes/default/content/docs/guides/self-hosted/api.md, themes/default/content/docs/guides/self-hosted/console.md
Related to https://github.com/pulumi/pulumi-service/pull/7726.
=> Update self-hosted docs for configuring the email identity availability

themes/default/content/docs/get-started/azure/begin.md
It's currently pointed to the azure classic one
=> updated link to azure native installation/config

themes/default/data/newsroom.toml
Adding a new customer announcement for Dec 7.
=> Update newsroom with customer announcement (Dec 7)

themes/default/content/docs/guides/crosswalk/aws/api-gateway.md
- Rework examples to use new package and in TS, Python & Go.
- Remove sections which relate to helper-functions or TypeScript-specific code.
- Refresh content around example (simplify, reword & reorder sections).
- Don't try to cover all permiatations, but plan to build out examples repo instead to help support.
Progress - completed to end of authorizers.
=> Rework API Gateway guide to use new cross-language component

themes/default/content/blog/the-industry-comes-together-for-the-cloud-engineering-summit-2021/index.md
Fixes: https://github.com/pulumi/marketing/issues/68
=> Update links in CES 2021 partner blog

themes/default/content/resources/aws-dev-day-getting-started-with-aws/index.md
=> fix(presenters): AWS workshop

themes/default/layouts/partials/learnmore-contactus.html
=> fix learn-more partial

themes/default/content/docs/intro/console/organizations.md
Adds a section describing how organization administrators might invite new members to an organization, incorporating recent changes to the invite process.  This is my first time making docs content changes, so in addition to any feedback on the specific content, please share any feedback about voice/tone/etc.  
fixes https://github.com/pulumi/pulumi-service/issues/7774
=> Add invite new members section

themes/default/layouts/case-studies/list.html
fixes https://github.com/pulumi/pulumi-hugo/issues/920
=> make headings on case studies list page consistent

themes/default/content/learn/building-with-pulumi/testing/index.md
I was going through [this documentation](https://www.pulumi.com/learn/building-with-pulumi/testing/) and noticed a typo. Submitting this PR in an effort to correct it. This is my first time contributing to open source, so please let me know if I'm doing anything incorrectly or breaking protocol. Happy holidays!
fixes https://github.com/pulumi/pulumi-hugo/issues/936
=> correct reference to test file name

themes/default/content/blog/api-gateway-to-eventbridge/index.md
=> Undraftify

.gitignore
Bit of context here:
https://discourse.gohugo.io/t/what-is-the-hugo-build-lock-file/35417
=> Ignore .hugo_build.lock

themes/default/content/blog/observable-infrastructure-as-code/index.md
=> Add attribution link at bottom of syndicated post

themes/default/content/blog/pulumi-and-localstack/index.md
Update to a previous syndicated post to make it more clear on the demarcation of content
=> Add line to show where community member post begins

themes/default/content/docs/troubleshooting/_index.md
For example, if you don't have external internet access
=> Added text if you need access to service

README.md, themes/default/content/docs/guides/pulumi-packages/schema.md, themes/default/content/docs/intro/concepts/resources/options/_index.md, themes/default/content/docs/intro/concepts/resources/options/providers.md, themes/default/content/docs/intro/concepts/resources/options/replaceonchanges.md, themes/default/content/docs/intro/concepts/resources/options/transformations.md, themes/default/content/docs/intro/concepts/resources/options/version.md
This adds documentation for some of my other PRs: https://github.com/pulumi/pulumi/issues/8796 and https://github.com/pulumi/pulumi/pull/8735.
=> Add providers and root namespace to documentation

themes/default/content/blog/dynamic-providers/index.md
I was just reading the docs. Haven't built the doc-site before.
fixes https://github.com/pulumi/pulumi-hugo/issues/1012
=> fixed broken link in blog/dynamic-providers/

themes/default/content/docs/guides/self-hosted/console.md
Trying to make it clear that this value should not be "https://DOMAIN" but just "DOMAIN"
=> Give DOMAIN examples

themes/default/content/case-studies/greenpark-sports.md
Update description of GreenPark Sports per customer request.
=> Update GreenPark Sports case study

themes/default/data/team/team/kimberley-mackenzie.toml
=> updating Kimberley's title

themes/default/content/blog/understanding-state/index.md
I never actually finished sentences 🤦‍♀️
=> fix(post): missing sentences

themes/default/content/docs/guides/adopting/import.md
Update docs to include where to find import IDs and how to know if they're available.
=> fix(import ids): update location and availability

themes/default/content/docs/guides/testing/unit.md
Happened to notice while using this doc to write some tests.
=> Qualify the reference to MockCallArgs

themes/default/content/docs/get-started/_index.md
Fixes https://github.com/pulumi/marketing/issues/100.
=> Add /getting-started alias

themes/default/content/docs/intro/concepts/config.md, themes/default/content/docs/intro/concepts/resources/providers.md
Adds documentation for disabling default providers (https://github.com/pulumi/pulumi/issues/3383)
Fixes https://github.com/pulumi/pulumi/issues/8987
=> Document disable default providers

README.md
To align with what's now in repo metadata:
=> Update the README's repo description

themes/default/content/learn/abstraction-encapsulation/_index.md, themes/default/content/learn/abstraction-encapsulation/abstraction/index.md, themes/default/content/learn/abstraction-encapsulation/component-resources/index.md, themes/default/content/learn/abstraction-encapsulation/encapsulation/index.md
This PR adds TypeScript language support to the Building with Pulumi pathway.
=> Add TypeScript to Learn > Abstraction & Encapsulation

themes/default/layouts/robots.txt
Fixes: https://github.com/pulumi/home/issues/1838
=> Add host and sitemap to robots.txt

themes/default/content/blog/retainondelete/index.md
Addressed some grammar issues in blog post.
=> Grammar fixes

themes/default/content/resources/automating-infrastructure-as-code-workflows/index.md, themes/default/content/resources/building-a-scientific-computing-lab-on-public-clouds-with-python/index.md, themes/default/content/resources/sharing-and-reusing-infrastructure-best-practices/index.md
=> Add workshops for April 2022

themes/default/content/docs/guides/self-hosted/quickstart-docker-compose.md
Noticed this while clicking around locally -- I think it's the only one.
=> Fix link to repo folder

themes/default/layouts/page/pricing.html
Fixes a link on the pricing page.
=> Underline a link

themes/default/content/product/pulumi-service.md
Add business critical to the list of Editions
=> Include Business Critical Edition

themes/default/content/case-studies/greenpark-sports.md
Revised description of company.
=> Update GreenPark case study

themes/default/content/blog/business-critical-launch/index.md
fixes https://github.com/pulumi/pulumi-hugo/issues/1141
=> fix business critical blog link

themes/default/content/pulumi-up/_index.md, themes/default/layouts/page/pulumi-up-2022.html
Just as the title states, this PR adds the date to the PulumiUP hype page.
=> Add date to pulumiup hype page

themes/default/content/blog/aws-eks-managed-nodes-fargate/index.md, themes/default/content/blog/embrace-kubernetes-part1/index.md, themes/default/content/blog/kubecon-review/index.md, themes/default/content/blog/managing-containers-on-aws-with-pulumi/index.md, themes/default/content/blog/pulumi-2-0/index.md
Stopped getting error about twitter shortcodes needing id and user
This is what they should look like now: https://gohugo.io/content-management/shortcodes/#example-tweet-input
=> Fixed twitter shortcodes

themes/default/content/docs/guides/continuous-delivery/github-actions.md
Apparently we were all so busy giggling that we forgot to actually fix this. 😂
And now my work is finished for the day.
=> Fix a typo

themes/default/content/blog/2022-03-10-hierarchical-config/index.md, themes/default/content/resources/_index.md, themes/default/layouts/page/brand.html, themes/default/layouts/resources/list.html
This PR is for implementing a new third nav design on the brand resources + resources pages.  The bulk of the code changes are in theme: https://github.com/pulumi/theme/pull/83, where I implemented a new reusable component for this nav functionality.  I used that component for the brand resources page, but had to implement the resources page separately because of how we use the nav as a filter there - but future implementations of a tertiary nav in this style should be easy with the new component.
Designs: https://www.figma.com/file/VRCp6m8TyfCN4tZugJiyh7/Third-Nav-Design?node-id=3%3A273 & https://www.figma.com/proto/VRCp6m8TyfCN4tZugJiyh7/Third-Nav-Design?node-id=3%3A1161&scaling=scale-down-width&page-id=3%3A273&starting-point-node-id=3%3A1161
Ticket: …
=> Third nav implementation on resources + brand resources pages

themes/default/content/confirmation/workshop.md
Fixes https://github.com/pulumi/marketing/issues/121.
=> De-list the thank-you page, remove some frontmatter

themes/default/content/docs/get-started/_index.md, themes/default/content/docs/intro/pulumi-service/_index.md
Fixes https://github.com/pulumi/pulumi-hugo/issues/994
We'll also be changing the language of the button on the Service doc for consistency ("Create an Account" vs "Sign up").
=> Updating Get Started Landing Page

themes/default/content/blog/pulumi-secrets-management/index.md
Great catch, @iwahbe! Fixing the code block.
=> fix(code): add missing fence for code block

themes/default/content/blog/announcing-aws-native/index.md
Fixes https://github.com/pulumi/marketing/issues/132.
=> Fix a note in the AWS Native post

themes/default/content/resources/build-reusable-infrastructure-as-code-patterns/index.md
=> Fix author on Registry Publishing video

STYLE-GUIDE.md
i realized that we dont really have redirects/aliases documented anywhere. adding a note to the style guide. suuper open to any wording feedback to make this more clear.
=> add note about redirects/aliases

README.md
Add some details about Swiftype and ways we have to adjust search results to the readme.  I added here since it's relevant to both docs and registry, but let me know if there's a better place for this info!
fixes https://github.com/pulumi/pulumi-hugo/issues/1220
=> Update readme with information about Swiftype

themes/default/content/blog/six-things-about-pulumi-service/index.md
Adds recommended tags and heading adjustments.
Fixes https://github.com/pulumi/marketing/issues/142.
=> Add tags to Service post

BLOGGING.md
was helping someone with a blog for the first time, and i know its prolly assumed but thought it might be good to explicitly state that you need to move onto a new branch; open to closing this if folks don't want to include this
=> adding step about moving onto a branch 

themes/default/content/enterprise/_index.md
Updating link to self-hosted offering to trial requst page.
=> Fix link to self-hosted trial page

.github/workflows/pull-request.yml
fixes https://github.com/pulumi/pulumi-hugo/issues/1325
=> trying to fix js overflow

.github/workflows/pull-request.yml, .github/workflows/push.yml, README.md, scripts/ensure.sh, themes/default/config.yml, themes/default/content/blog/pulumi-release-notes-m58/index.md
Bumps versions of Node, Go, and Hugo to align with currents, and removes a bit of cruft.
=> Update some dev dependencies

.devcontainer/devcontainer.json
This matches the version in .github/workflows/push.yml
=> Update hugo version in devcontainer

themes/default/content/pulumi-up/_index.md, themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md, themes/default/layouts/page/pulumi-up-2022.html
This PR adds a workshop section and the NGNIX workshop for PulumiUP.
=> Add nginx workshop for pulumiup

themes/default/content/enterprise/_index.md, themes/default/content/security/_index.md
Fixes https://github.com/pulumi/marketing/issues/226.
=> Add whitepaper links

themes/default/content/docs/reference/service-rest-api/_index.md
=> Change parameter name to correct one

STYLE-GUIDE.md
these are taken from @SaraDPH's work to define content design guidelines
super open to any and all feedback
=> adding some content design guidelines to style guide

themes/default/content/resources/using-pulumi-to-supercharge-your-deployments/index.md
Fixes https://github.com/pulumi/marketing/issues/236.
=> Clarify workshop location

themes/default/content/pulumi-up/_index.md, themes/default/content/resources/gitops-with-github-actions-and-the-pulumi-operator/index.md
https://github.com/pulumi/marketing/issues/239
https://github.com/pulumi/marketing/issues/240
=> Add workshops for PulumiUP 2022

themes/default/content/pulumi-up/_index.md, themes/default/content/resources/ci-cd-pipelines-for-kubernetes-apps-with-codefresh/index.md
=> Update codefresh workshop timezone and add link to suggest topics for commnity summit.

themes/default/content/blog/pulumi-release-notes-70/index.md
Fixes https://github.com/pulumi/marketing/issues/251.
=> Fix broken anchors

themes/default/content/solutions/infrastructure-ci-cd.md
also made text updates throughout while at it :)
=> fixes a typo 'the the'

themes/default/content/community/developer-advocates/matt-stratton.md, themes/default/layouts/community/developer-advocates/single.html
pretty sure this is gonna fail if anyone adds another commit, or re-runs it, so hopefully its good to just merge
=> Add slides to Matty's devopsdays Denver talk

themes/default/content/docs/intro/concepts/assets-archives.md
Adjusting to snake case on pulumi.com [asset & archives page](https://www.pulumi.com/docs/intro/concepts/assets-archives/)
=> Adjusting Python variables to be consistent

themes/default/content/blog/organization-access-tokens/index.md
Few fixes for this post:
* Removes the time, so it can go out now
* Replaces some hard-coded links
* Fixes some terminology
=> Fixes for org-tokens post

themes/default/content/pulumi-up/_index.md, themes/default/content/resources/deploying-microservices-with-pulumi-and-aws-lambda/index.md, themes/default/content/resources/jdconf-2022/index.md
Just as the title states, this PR adds listings for JDConf and the devops.com workshop.
=> Add JDConf and AWS workshop for PulumiUP

themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md, themes/default/content/resources/getting-started-with-azure-native/index.md, themes/default/content/resources/getting-started-with-infrastructure-as-code-on-oracle-cloud/index.md
Fixes: https://github.com/pulumi/marketing/issues/301
=> Update PulumiUP workshop information

themes/default/content/pulumi-up/_index.md, themes/default/content/resources/getting-started-with-infrastructure-as-code-on-digital-ocean/index.md
https://github.com/pulumi/marketing/issues/300
=> Add DigitalOcean workshop for PulumiUP

themes/default/content/docs/guides/self-hosted/_index.md
this is addressing feedback from a person on twitter
[twitter thread](https://twitter.com/aaomidi/status/1517544347155238914?s=20&t=mrq0DsNp-Rx6F9wcCPDxEA)
[internal slack convo](https://pulumi.slack.com/archives/C01E2KK808G/p1650733843563659)
=> make self-hosted language more clear

themes/default/content/docs/guides/organizing-projects-stacks/_index.md
=> Additions to Projects and Stacks page

themes/default/content/docs/guides/crosswalk/aws/_index.md, themes/default/content/docs/guides/crosswalk/aws/autoscaling.md, themes/default/content/docs/guides/crosswalk/aws/cloudwatch.md, themes/default/content/docs/guides/crosswalk/aws/ecr.md, themes/default/content/docs/guides/crosswalk/aws/ecs.md, themes/default/content/docs/guides/crosswalk/aws/eks.md, themes/default/content/docs/guides/crosswalk/aws/iam.md, themes/default/content/docs/guides/crosswalk/aws/lambda.md, themes/default/content/docs/guides/crosswalk/aws/vpc.md
- Update AWSx Cloudwatch, IAM and Lambda to refer to classic module
- Update AWSx Autoscaling to refer to classic module
- Adding AWSX ECR updates for MLC
- Updating EKS guide to include new AWSX setup
- Adding AWSX VPC updates for MLC
- Linting of the guides
=> awsx guides

themes/default/content/blog/aws-cdk-on-pulumi/index.md
moved more up so it renders better on the blog page
=> Tiny fix for CDK blog

themes/default/content/docs/intro/_index.md, themes/default/content/docs/intro/concepts/_index.md, themes/default/content/docs/intro/concepts/how-pulumi-works.md, themes/default/content/docs/intro/concepts/project.md, themes/default/content/docs/intro/concepts/stack.md, themes/default/content/docs/intro/concepts/state.md, themes/default/content/docs/intro/vs/cloud-template-transpilers/aws-cdk/_index.md, themes/default/content/docs/intro/vs/cloud-templates/cloudformation/_index.md
=>  Make pulumi architecture more discoverable

themes/default/content/learn/pulumi-fundamentals/configure-and-provision/index.md, themes/default/content/learn/pulumi-fundamentals/create-docker-images/index.md
=> Fix some issues with Java version of Learn

themes/default/content/docs/intro/languages/yaml.md
The Kubernetes template doesn't display. This fixes it.
=> Fix kubernetes template

themes/default/layouts/partials/header.html
=> fix products menu item

themes/default/content/docs/get-started/aws/deploy-changes.md, themes/default/content/docs/get-started/aws/modify-program.md, themes/default/content/docs/get-started/aws/review-project.md, themes/default/content/docs/get-started/azure/modify-program.md, themes/default/content/docs/get-started/azure/review-project.md, themes/default/content/docs/get-started/gcp/deploy-changes.md, themes/default/content/docs/get-started/gcp/modify-program.md, themes/default/content/docs/get-started/gcp/review-project.md, themes/default/content/docs/get-started/kubernetes/modify-program.md, themes/default/content/docs/get-started/kubernetes/review-project.md, themes/default/layouts/shortcodes/install-java.html
Walked through all of the new stuff and fixed up little things as I found them.
Fixes https://github.com/pulumi/marketing/issues/309.
Related PRs:
* https://github.com/pulumi/templates/pull/280
* https://github.com/pulumi/templates/pull/281
* https://github.com/pulumi/templates/pull/282
=> Getting Started papercuts

themes/default/content/resources/improving-the-gitops-pipeline/index.md
the previous link was going to the channel and not an individual video
=> fix improving gitops resource link

themes/default/content/docs/intro/pulumi-service/organization-access-tokens.md, themes/default/content/docs/reference/service-rest-api/_index.md
Fixes [#1495](https://github.com/pulumi/pulumi-hugo/issues/1495)
=> Add 'List Teams' Action to Pulumi Service REST API docs

themes/default/content/docs/intro/languages/_index.md
i noticed in @SaraDPH's issue that YAML was missing form this description, this adds it
https://github.com/pulumi/marketing/issues/312
I also reordered them to match the order on the page
=> update meta description on languages page

themes/default/content/cloud-engineering/_index.md, themes/default/content/partner/aws.md, themes/default/layouts/partner/aws.html
This PR updates the code examples and some text on /aws and /cloud-engineering.
=> Update code examples on language on /aws and /cloud-engineering

themes/default/content/blog/configuring-your-dev-environment/index.md, themes/default/content/blog/kubernetes-ingress-with-aws-alb-ingress-controller-and-pulumi-crosswalk/index.md, themes/default/content/blog/mapbox-iot-as-code-with-pulumi-crosswalk-for-aws/index.md, themes/default/content/blog/persisting-kubernetes-workloads-with-amazon-efscsi-volumes-using-pulumi-sdks/index.md, themes/default/content/blog/simplify-kubernetes-rbac-in-amazon-eks-with-open-source-pulumi-packages/index.md, themes/default/content/docs/get-started/install/_index.md, themes/default/layouts/shortcodes/install-pulumi.html
in https://github.com/pulumi/pulumi-hugo/pull/1382 we updated the brew command on the install page; i noticed in a usability study yesterday that the aws get started guide was not updated, so this brings that inline, along with a few other places
=> update brew commands

go.mod, go.sum
Build failure with invalid revision for theme module requires this manual update of the go mod and go sum: https://github.com/pulumi/pulumi-hugo/runs/6532566897?check_suite_focus=true
=> Fix up go mod and go sum.

themes/default/content/docs/intro/concepts/secrets.md
This needs to wait until the following PR is released: pulumi/pulumi#9536
=> Added note about adding `profile` to the KMS identifier

themes/default/content/blog/aws-cloudwatch-made-easy-with-pulumi-infrastructure-as-code/index.md, themes/default/content/blog/kubernetes-ingress-with-aws-alb-ingress-controller-and-pulumi-crosswalk/index.md, themes/default/content/blog/meals-for-ukraine/index.md, themes/default/content/blog/top-5-things-for-azure-devs-vm/index.md
see website-notifications in internal slack for more deets
updates...
- /blog/author/nishi-davidson/ 
- /blog/aws-cloudwatch-made-easy-with-pulumi-infrastructure-as-code/ 
- /blog/kubernetes-ingress-with-aws-alb-ingress-controller-and-pulumi-crosswalk/
- /blog/meals-for-ukraine/ 
- /blog/top-5-things-for-azure-devs-vm/ 
=> fix blog 404s

go.mod, go.sum, themes/default/content/learn/_index.md
Fixes: https://github.com/pulumi/pulumi-hugo/issues/1534
Theme PR: https://github.com/pulumi/theme/pull/144
This PR addresses the following fixes that are also outlined in the issue linked above. 
Here is a screenshot. Also, check out the preview when it becomes available. Let me know what you all think and if we need to make any other adjustments to other things on the page. The page is located at the `/learn` route.
=> Learn page fixes

go.mod, go.sum
Looks like my build failed.... seems to be due to a discrepancy with the go.mod and go.sum files... 
this is an attempt to fix it.
=> fix go.mod

themes/default/layouts/partials/head.html
Fixes: https://github.com/pulumi/marketing/issues/336
=> Update site header with fb domain verfication

themes/default/archetypes/blog-post/index.md
because I never remember the max length of the meta_desc
=> Add helper text to blog post archetype

themes/default/layouts/page/about.html
Fixes: https://github.com/pulumi/marketing/issues/345
=> Fix typo on about page

themes/default/content/_index.md
Fixes: https://github.com/pulumi/pulumi-hugo/issues/1255
=> Add materialize logo to home page

themes/default/layouts/page/pricing.html
Updated FAQ about estimated costs for different scenarios to clarify that they are before factoring in free credits.
=> Clarify pricing FAQ

themes/default/content/docs/intro/vs/terraform/_index.md, themes/default/layouts/migrate/terraform.html
This PR adds the new Terraform to two of our Terraform-related pages as well as provides some SEO updates to the Pulumi vs Terraform page.
Fixes: https://github.com/pulumi/pulumi-hugo/issues/1568
=> Update terraform related pages with terraform video

themes/default/content/blog/persisting-kubernetes-workloads-with-amazon-efscsi-volumes-using-pulumi-sdks/index.md
@stack72 let me know if this is the right thing to link to
=> fix 404 link in kube workloads blog

themes/default/content/docs/guides/pulumi-packages/how-to-author.md, themes/default/content/docs/guides/pulumi-packages/schema.md
Added documentation for RespectSchemaVersion which was added [here](https://github.com/pulumi/pulumi/pull/8881) but not documented.
=> Add Documentation for RespectSchemaVersion

BLOGGING.md
When someone writes an awesome blog post, we want to make sure it reaches as many people as possible. 
This PR adds a step to alert Marketing in #blogs so they can include it in their ongoing messaging.
=> Add marketing process to blog publication

themes/default/content/resources/ci-cd-pipelines-for-kubernetes-apps-with-codefresh/index.md
Fixes: https://github.com/pulumi/marketing/issues/239
This PR updates the workshop time to be August 30, 2022. It also updates the description with the new text as well as the title. I reduced the wording for the description that shows up on the resources landing page from what is described in the issue since we have a character limit of 160 characters for those descriptions in place. Let me know if it sounds ok. cc @isaac-pulumi
=> Update codefresh workshop

themes/default/content/resources/ci-cd-pipelines-for-kubernetes-apps-with-codefresh/index.md
See slack convo for context: https://pulumi.slack.com/archives/CPD83QEQ1/p1654022575258509
=> Update codefresh workshop with new bulletpoints and title

themes/default/content/docs/guides/crosswalk/aws/ecs.md
Discovered a couple of typos in the awsx ECS with VPC example code.
=> Mitchell gerdisch/correct awsx ecs examples

themes/default/layouts/blog/rss.xml
Applies date-based sort (most recent first) to the RSS feed.
=> Fix RSS sorting

themes/default/content/docs/guides/adopting/import.md
Fixes https://github.com/pulumi/pulumi/issues/9785
=> Document the schema for bulk imports

themes/default/data/team/team/joshua-studt.toml
This is to adjust the formatting for Josh on the Puluminaries page
=> Update Joshua Studt formatting 

themes/default/content/blog/meals-for-ukraine/index.md
removing the links that have been 503ing since June 17th
[internal slack convo](https://pulumi.slack.com/archives/C7XHM1GNT/p1655914784788929)
=> remove 503 links from ukraine blog

scripts/ci/sync.sh
Related to https://github.com/pulumi/docs/pull/7703.
=> Handle AWS CLI V2

themes/default/content/docs/get-started/aws/next-steps.md, themes/default/content/docs/get-started/azure/next-steps.md, themes/default/content/docs/get-started/gcp/next-steps.md, themes/default/content/docs/get-started/kubernetes/next-steps.md, themes/default/layouts/shortcodes/get-started-next-step.html
Updates the next-steps pages at the end of each Getting Started tutorial to include links to Learn, Docs, How-to guides, and the Blog.
=> Update next-steps pages

themes/default/content/resources/getting-started-with-iac-aws/index.md
Fix hero casing. Capitalize S in Getting Started.
=> Fix hero casing

themes/default/data/team/team/joshua-studt.toml
Updating to reflect past job change :)
=> Josh Studt - update title & company

themes/default/content/blog/pulumiup-workshop-series/index.md
Fixes https://github.com/pulumi/marketing/issues/373
=> Update Oracle workshop link in blog

themes/default/content/docs/guides/pulumi-packages/how-to-author.md
See https://github.com/pulumi/pulumi/pull/9984
=> Add documentation about the github schema for pluginDownloadURL

themes/default/content/docs/get-started/aws/begin.md
fixes https://github.com/pulumi/pulumi-hugo/issues/1686
=> removing confusing line about policy in aws get started guide

themes/default/content/resources/deploying-microservices-with-pulumi-and-aws-lambda/index.md, themes/default/content/resources/getting-started-with-iac-aws/index.md, themes/default/content/resources/turning-infrastructure-into-software-through-cloud-engineering/index.md
Fixes: https://github.com/pulumi/marketing/issues/377
Part of: https://github.com/pulumi/marketing/issues/359
=> Update resources listings with new presenters

themes/default/layouts/migrate/kube2pulumi.html
Just a quick typo I noticed. :)
=> Fix typo on kube2pulumi page

themes/default/content/docs/guides/pulumi-packages/schema.md
Fixes https://github.com/pulumi/pulumi/issues/10087
=> Add pluginName and version to schema page

themes/default/content/resources/ci-cd-pipelines-for-kubernetes-apps-with-codefresh/index.md
Fixes: https://github.com/pulumi/marketing/issues/378
=> Update speaker for Codresh workshop

themes/default/content/learn/pulumi-fundamentals/configure-and-provision/index.md, themes/default/content/learn/pulumi-fundamentals/create-a-pulumi-project/index.md
The shown example won't compile, let's fix this.
=> Fix Java example at create-a-pulumi-project/index.md

themes/default/content/docs/get-started/aws/review-project.md, themes/default/content/docs/get-started/azure/review-project.md, themes/default/content/docs/get-started/gcp/review-project.md, themes/default/content/docs/get-started/kubernetes/modify-program.md, themes/default/content/docs/get-started/kubernetes/review-project.md, themes/default/content/registry/packages/aws/how-to-guides/ec2-webserver.md
Tactical fix for pulumi/pulumi#10202
=> Fix C# code in get-started

themes/default/content/docs/guides/crosswalk/aws/api-gateway.md
=> Python Fixes

themes/default/content/docs/guides/crosswalk/aws/ecs.md
Add a pulumi.export in the python code block so the next step can be followed
fixes #1775
=> update python code block in ecs.md

themes/default/content/resources/introduction-to-infrastructure-as-code-with-yaml/index.md
https://github.com/pulumi/marketing/issues/451
=> update yaml workshop for 8/9/22

themes/default/content/resources/collaborating-with-people/index.md, themes/default/content/resources/connecting-securing-and-scaling-microservices-with-kubernetes/index.md, themes/default/content/resources/getting-started-with-infrastructure-as-code-on-oracle-cloud/index.md
Updates based on this https://github.com/pulumi/marketing/issues/424 pending title change
=> move Oracle workshop from upcoming to resources/videos

themes/default/content/docs/intro/pulumi-service/projects-and-stacks.md
=> Fix C# stack readme sample code

themes/default/content/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply.md
Add Java examples, update Go and C# examples
=> Update Kubernetes SSA guide

themes/default/content/docs/reference/pulumi-yaml.md
See https://github.com/pulumi/pulumi/pull/10146 for implementation
=> Add docs about plugins section in Pulumi.yaml

themes/default/content/docs/aws/ec2.md, themes/default/layouts/shortcodes/cli-note.html
Fixes a couple of things that came up in a recent working group meeting:
* Mentions self-managed options in the getting-started CLI note
* Fixes the (totally broken!) EC2 instance example 
cc @joeduffy on the former just 'cause it was something you mentioned.
=> Fix a couple of papercuts

themes/default/content/docs/intro/concepts/resources/get.md, themes/default/content/docs/intro/concepts/resources/names.md, themes/default/content/docs/intro/languages/yaml.md, themes/default/content/docs/reference/yaml/_index.md
Fixes https://github.com/pulumi/pulumi-yaml/issues/292
=> Document yaml getters

themes/default/content/docs/support/troubleshooting.md
System wide proxy should not proxy local traffic required by Pulumi
=> Troubleshoot Pulumi & system wide proxy server

themes/default/content/resources/getting-started-with-iac-aws/index.md
Changes per https://github.com/pulumi/marketing/issues/360
=> update iac on aws workshop for 9/8

themes/default/content/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply.md
Fix https://github.com/pulumi/pulumi-kubernetes/issues/2119
=> Add better explanation for a k8s how-to example

themes/default/layouts/index.html
=> fix buttons on home on smaller screens

themes/default/content/docs/intro/concepts/resources/options/transformations.md
Resolves https://github.com/pulumi/pulumi-java/issues/680
=> Add stack transformation example for Java

themes/default/content/resources/getting-started-with-iac-aws/index.md
https://github.com/pulumi/marketing/issues/360
=> update iac on aws date to 9/12

themes/default/content/resources/gophercon-2022-platform-engineering-in-any-language/index.md
https://github.com/pulumi/marketing/issues/498
=> add gophercon workshop to upcoming resources

themes/default/content/resources/gophercon-uk-2022-canonical-gitops/index.md
https://github.com/pulumi/marketing/issues/499
=> add gophercon canonical GitOps talk to resources page

STYLE-GUIDE.md
adding this in now so we can head in this direction
will start the process of aligning things in a separate pr
=> update style guide to include sentence case

themes/default/content/blog/unlocking-your-data-with-metabase-and-aws/index.md
Just as the title states, this PR updates the C# code examples in the Metabase blog post.
=> Update csharp code examples on Metabase blog

themes/default/content/resources/container-days-2022-debugging-kubernetes-live/index.md
https://github.com/pulumi/marketing/issues/500
=> add Container Days workshop to resources page

themes/default/content/resources/ndc-oslo-2022-reactive-infrastructure/index.md
https://github.com/pulumi/marketing/issues/502
=> add ndc oslo reactive infrastructure talk to resources

themes/default/content/docs/reference/pulumi-yaml.md
trying to make the pulumi yaml file usable
=> improve usability of pulumi yaml project file

themes/default/content/resources/getting-started-with-iac-aws/index.md
https://github.com/pulumi/marketing/issues/360#issuecomment-1217032787
=> update presetners for iac on aws workshop on 9/12

themes/default/layouts/shortcodes/configure-gcp.html
Patch up the configuration info to display the code blocks properly.
=> fix(markdown): format code blocks

themes/default/content/docs/get-started/install/_index.md
h/t to @aureq for spotting this one while we were looking at something else.
=> Fix CLI binary download link for Windows

themes/default/content/docs/support/troubleshooting.md
i dont think this page has been reviewed as a whole in a long time, as there were some heading level issues and misalignment between various sections. this pr is cleaning up the page to make it a bit more usable. feedback welcome!
edits have been made to `docs/support/troubleshooting`
**important note**: a number of things have been moved around, so reading the files changed on github is somewhat difficult. i recommend first reviewing the current page, then the preview, ahead of reviewing files changed.
=> fix headings and clean up troubleshooting page

themes/default/content/docs/reference/yaml/_index.md
=> Add Fn::Split to YAML Reference

themes/default/content/learn/abstraction-encapsulation/_index.md, themes/default/content/learn/building-with-pulumi/_index.md, themes/default/content/learn/embedding-pulumi/_index.md, themes/default/content/learn/importing/_index.md, themes/default/content/learn/pulumi-fundamentals/_index.md
fixes https://github.com/pulumi/pulumi-hugo/issues/1672
=> feat(cli): add cli install links

themes/default/content/learn/building-with-pulumi/secrets/index.md, themes/default/content/learn/building-with-pulumi/stack-outputs/index.md, themes/default/content/learn/building-with-pulumi/stack-references/index.md, themes/default/content/learn/building-with-pulumi/understanding-stacks/index.md
fixes https://github.com/pulumi/pulumi-hugo/issues/1506
=> fix(var): fix all variables for typescript; remove seed container ref

themes/default/content/docs/intro/concepts/state.md
Fixes https://github.com/pulumi/pulumi/issues/9555
=> Update state & login instructions for AWS profiles

themes/default/content/resources/kubecrash-2022/index.md
https://github.com/pulumi/marketing/issues/513
=> add kubecrash to resources

themes/default/content/resources/building-a-developer-platform-with-aks-and-cosmosdb/index.md
https://github.com/pulumi/marketing/issues/523
=> add aks/cosmosdb workshop to resources

themes/default/content/cloud-engineering-days/_index.md, themes/default/layouts/partials/head.html, themes/default/layouts/robots.txt
This will also allow us to fill out `event_data` fields for future workshops to show up in google events
https://developers.google.com/search/docs/advanced/structured-data/event
=> add script for google events, fill in event data for CED

themes/default/content/docs/guides/organizing-projects-stacks/_index.md
[internal slack thread](https://pulumi.slack.com/archives/C85BS3LJZ/p1661392718349309)
=> add stack references to organizing projects and stacks guide

themes/default/content/docs/intro/concepts/config.md
this recently came up in community slack
so thought it might b e good to add to the docs
[community slack convo](https://pulumi-community.slack.com/archives/C01PF3E1B8V/p1661598311827829)
=> add details about passing config to pulumi new

themes/default/content/learn/pulumi-fundamentals/configure-and-provision/index.md, themes/default/content/learn/pulumi-fundamentals/create-docker-images/index.md
Updates code to remove old code syntax from before the launch.
fix #1841, fix pulumi/pulumi-java#810
=> fix(java): patch java errors and mistakes

themes/default/content/resources/getting-started-with-iac-aws/index.md, themes/default/layouts/webinars/single.html
https://github.com/pulumi/marketing/issues/528
=> create aws_only version of 'Get Started with Pulumi' links

themes/default/content/docs/reference/yaml/_index.md
Updates YAML reference for `Fn::Invoke` based on [change here](https://github.com/pulumi/pulumi-yaml/pull/284)
=> Add options to Fn::Invoke docs

themes/default/content/docs/get-started/install/_index.md
#1818 fixed one but there is one more
=> Fix WinGet download URL (another one)

themes/default/content/docs/support/troubleshooting.md
=> Update troubleshooting docs for `pulumi refresh` changes

themes/default/data/team/team/joshua-studt.toml
Just updating to reflect my new position. Thank you :)
=> update Josh Studt company & title

themes/default/layouts/index.html
This PR adds some padding to the hero so the text doesn't bump up against edge of the window on smaller screens.
=> Fix up responsive padding in home hero

themes/default/content/docs/intro/pulumi-service/billing-managers.md
[internal slack thread](https://pulumi.slack.com/archives/C8A7QG1CZ/p1663039758266469)
changes to `docs/intro/pulumi-service/billing-managers`
=> add note to billing managers page about org identity providers

themes/default/layouts/partials/banner.html
Part of https://github.com/pulumi/pulumi-hugo/issues/1911
=> Add pulumi challenge banner promotion

themes/default/content/resources/ci-cd-pipelines-for-kubernetes-apps-with-codefresh/index.md, themes/default/content/resources/container-days-2022-debugging-kubernetes-live/index.md, themes/default/content/resources/getting-started-with-iac-aws/index.md, themes/default/content/resources/gophercon-2022-platform-engineering-in-any-language/index.md, themes/default/content/resources/gophercon-uk-2022-canonical-gitops/index.md, themes/default/content/resources/introduction-to-infrastructure-as-code-with-python/index.md, themes/default/content/resources/introduction-to-infrastructure-as-code-with-yaml/index.md, themes/default/content/resources/turning-infrastructure-into-software-through-cloud-engineering/index.md, themes/default/content/resources/women-who-code-melbourne/index.md
https://github.com/pulumi/marketing/issues/535
=> remove completed workshops from upcoming - first party youtube videos added, external unlisted

BLOGGING.md
Add instructions to access the Gilroy font for meta image designs.
=> Add Gilroy instructions to BLOGGING.md

themes/default/content/docs/guides/crosswalk/aws/eks.md
=> Use correct AssumeRolePolicy in EKS guide

themes/default/content/docs/intro/pulumi-service/projects-and-stacks.md
George noticed the favorite spelling issue, i decided to do a full pass of the page along with fixing that issue
=> fix projects and stacks spelling and grammar

themes/default/content/cloud-engineering-days/_index.md, themes/default/content/resources/building-containers-azure/index.md, themes/default/content/resources/pulumi-101-kubernetes-on-azure/index.md, themes/default/content/resources/pulumi-101-serverless-containers-gcp/index.md, themes/default/content/resources/pulumi-101-static-site-on-aws/index.md, themes/default/content/resources/serverless-architecture-aws/index.md, themes/default/content/resources/simpler-pulumi-package-authoring/index.md
https://github.com/pulumi/marketing/issues/550
=> add workshops to CED and resources pages with placeholder presenters

themes/default/content/resources/getting-started-with-infrastructure-as-code-on-digital-ocean/index.md
https://github.com/pulumi/marketing/issues/300
=> update date and presenters for DigitalOcean workshop

themes/default/content/_index.md
=> Remove Kavak logo

themes/default/layouts/shortcodes/install-go.html
Update the minimum Go version to 1.18.
=> Update the minimum Go version

themes/default/content/resources/getting-started-with-iac-aws/index.md
Part of https://github.com/pulumi/marketing/issues/562#event-7480256337
=> Add aws workshop for october

themes/default/content/challenge/one-quickstart.md, themes/default/content/challenge/startup-in-a-box.md, themes/default/layouts/challenge/list.html
Adds draft of September Challenge, and corrects a grammatical issue with August.
Swag graphic TBA
=> adds september challenge draft

themes/default/content/docs/reference/pulumi-yaml.md
Follow up from https://github.com/pulumi/pulumi/issues/10824
=> Fix refresh option in pulumi project file example

themes/default/content/resources/pulumi-101-fundamentals-python-and-docker/index.md
Issue: https://github.com/pulumi/marketing/issues/549
=> Add pulumi 101 with python and docker workshop

themes/default/content/resources/getting-started-with-infrastructure-as-code-on-digital-ocean/index.md
https://github.com/pulumi/marketing/issues/300
=> update time for DigitalOcean workshop

themes/default/content/docs/guides/adopting/from_kubernetes.md
- Fix outdated example usage
- Fix a few typos and grammar issues
Fix https://github.com/pulumi/docs/issues/8069
=> Update Kubernetes adoption doc

themes/default/content/request-a-demo/_index.md, themes/default/layouts/page/demo.html, themes/default/layouts/page/pricing.html, themes/default/layouts/partials/footer.html, themes/default/layouts/partials/hand-raise-section.html, themes/default/layouts/partials/header.html
This PR adds are a request demo page and updates copy in a few places to point to the new page. In some places we are changing the CTA from "Contact Sales" to "Request a Demo".
=> Add request a demo page

themes/default/content/cloud-engineering-days/_index.md
https://github.com/pulumi/marketing/issues/570
=> fix agenda working/typo

themes/default/data/team/team/andy-de-mars.toml, themes/default/data/team/team/david-flanagan.toml, themes/default/data/team/team/jay-wampold.toml
got approval from Casie before opening this pr
=> remove people

themes/default/layouts/page/kubecon-eu.html
https://github.com/pulumi/marketing/issues/495
Also pasted in some description to support Pulumi Challenge & Cloud Engineering Days sections
=> update kubecon EU page

themes/default/content/registry/packages/gcp/how-to-guides/gce-webserver.md
Hi! :wave: I came across this line while following the guide, and figured I'd fix it :smile:
=> fix(gce-webserver): adjust a sentence in a comment

themes/default/content/templates/container-service/aws/index.md, themes/default/content/templates/kubernetes/aws/index.md, themes/default/content/templates/serverless-application/aws/index.md, themes/default/content/templates/static-website/aws/index.md, themes/default/content/templates/static-website/azure/index.md, themes/default/content/templates/static-website/gcp/index.md
Fix a few items for consistency
=> Fixes to template landing pages

themes/default/content/docs/guides/self-hosted/_index.md, themes/default/content/docs/guides/self-hosted/byo-infra-hosted.md
Do not merge until https://github.com/pulumi/pulumi-self-hosted-installers/pull/83 is merged
=> Add docs for self-hosted byo infra

themes/default/content/docs/reference/yaml/_index.md
Fixes https://github.com/pulumi/pulumi-yaml/issues/377
=> Update Pulumi YAML reference with new fields

themes/default/content/docs/guides/continuous-delivery/azure-devops.md, themes/default/content/docs/guides/continuous-delivery/circleci.md, themes/default/content/docs/guides/continuous-delivery/github-actions.md, themes/default/content/docs/guides/continuous-delivery/jenkins.md
Customer reported the runtime versions were quite outdated. Updated these to reflect the current runtime versions better.
=> Refresh runtime versions in the CI guides

themes/default/content/templates/kubernetes/aws/index.md, themes/default/content/templates/kubernetes/azure/index.md
⚠️ Don't merge this until https://github.com/pulumi/templates/pull/411 has merged.
=> Add C# language options Kubernetes AWS and Azure templates

themes/default/content/cloud-engineering-days/_index.md
The new form has a simplified optin for swag
=> Replaced Registration form with a v2

themes/default/layouts/partials/banner.html
https://github.com/pulumi/pulumi-hugo/issues/2080
=> update banner for kubernetes operator

themes/default/archetypes/templates/template/index.md
Fixes to catch up the standard page template with the latest changes
=> Update to template page helper

themes/default/layouts/page/kubecon.html
Updates per [this comment](https://github.com/pulumi/marketing/issues/495#issuecomment-1273970839)
Needed prior to 10/26
=> update kubecon page to include pulumi templates info

themes/default/content/resources/cloud-engineering-in-aws-with-python/index.md, themes/default/content/resources/getting-started-with-iac-aws/index.md
fixes: https://github.com/pulumi/marketing/issues/642
=> update workshop with yt video

themes/default/content/docs/intro/concepts/secrets.md
The latest gocloud update also brought support for encryption context.
See https://github.com/google/go-cloud/pull/3154 and https://github.com/google/go-cloud/issues/3149 for additional details.
=> secrets: Add description for AWS KMS encryption context

themes/default/content/cloud-engineering-days/_index.md
https://github.com/pulumi/marketing/issues/339#issuecomment-1293883790
=> update dutchie talk title

themes/default/content/resources/pulumi-101-fundamentals-java-and-docker/index.md, themes/default/layouts/webinars/single.html
issue: https://github.com/pulumi/marketing/issues/634
=> add fundamentals with java and docker workshop

themes/default/content/cloud-engineering-days/_index.md, themes/default/content/resources/building-virtual-networks-with-pulumi-and-tailscale/index.md, themes/default/content/resources/deploying-and-managing-kafka-with-pulumi-and-confluent/index.md
Part of https://github.com/pulumi/marketing/issues/640
Part of https://github.com/pulumi/marketing/issues/641
=> Add Tailscale and Confluent workshops to CED page

themes/default/content/resources/introduction-to-infrastructure-as-code-with-typescript/index.md
=> New Workshop - intro to infrastructure as code with typescript

themes/default/content/docs/reference/yaml/_index.md
=> Update YAML Reference to new config

themes/default/content/resources/intro-to-infrastructure-as-code-with-yaml/index.md
issue: https://github.com/pulumi/marketing/issues/637
=> New Workshop - introduction to infrastructure as code with yaml

themes/default/layouts/challenge/list.html
Fixes a typo in the challenge list links.
=> Fix typo in challenge links

themes/default/layouts/page/pricing.html
Fixes: https://github.com/pulumi/pulumi-hugo/issues/2166
=> Change CTA from Request Demo to Contact Us

themes/default/content/docs/guides/continuous-delivery/github-app.md
Seems like a word may be missing here. Maybe this one?
=> Add a missing word

themes/default/content/resources/automating-infrastructure-as-code-workflows-with-pulumi/index.md
issue: https://github.com/pulumi/marketing/issues/635
=> New Workshop - automating infrastructure as code workflows with pulumi 

themes/default/content/resources/pulumi-101-fundamentals-java-and-docker/index.md
ref https://github.com/pulumi/marketing/issues/634#issuecomment-1306143114
=> fix(time): change workshop to expected 60 minutes

themes/default/content/blog/announcing-pulumi-service-provider/index.md, themes/default/content/blog/meals-for-ukraine/index.md, themes/default/content/blog/pulumi-rest-api/index.md, themes/default/content/blog/unlocking-your-data-with-metabase-and-aws/index.md, themes/default/content/docs/guides/continuous-delivery/teamcity.md
Resolved handful of broken internal and external links across /blogs/ and /docs/ as part of technical SEO maintenance.
Original PR: https://github.com/pulumi/pulumi-hugo/pull/2121
=> Resolve broken internal/external links

themes/default/content/docs/get-started/_index.md
Fixes: https://github.com/pulumi/pulumi-hugo/issues/2220
=> Add more templates to get started landing page

themes/default/content/docs/reference/deployments-rest-api/_index.md
Specific docs to get the right combination for a successful poetry install
=> Add specific steps for poetry

themes/default/content/cloud-engineering-days/_index.md, themes/default/layouts/page/cloud-engineering-days.html
fixes https://github.com/pulumi/pulumi-hugo/issues/2228
=> remove registration prompts for finished workshops, remove section links to CED registration form

themes/default/layouts/page/pricing.html
Adding team & org access tokens to the feature comparison table.
=> Add team & org access tokens to pricing page

themes/default/content/blog/fullstack-pulumi-mern-stack-digitalocean/index.md
Repo's been moved into the pulumi org, so this just updates some links to avoid confusion.
=> Change the location of the MERN DO repo

themes/default/content/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply.md
Fix https://github.com/pulumi/pulumi-kubernetes/issues/2213
=> Add a note about required `patch` permission for k8s SSA mode

themes/default/content/docs/intro/pulumi-service/projects-and-stacks.md, themes/default/content/docs/support/faq.md
small updates to our docs that mention stack transfer to align with the new bulk transfer feature.
fixes https://github.com/pulumi/pulumi-hugo/issues/2222
=> update stack transfer in docs

.github/workflows/pull-request.yml, .github/workflows/push.yml
=> Bump Go to 1.19

themes/default/content/docs/intro/concepts/plans.md, themes/default/content/docs/intro/concepts/stack.md
Fixes https://github.com/pulumi/pulumi-hugo/issues/1604
=> Update plans concept page

themes/default/content/resources/automating-infrastructure-as-code-workflows-with-pulumi/index.md, themes/default/content/resources/building-a-developer-platform-with-aks-and-cosmosdb/index.md, themes/default/content/resources/getting-started-infrascructure-as-code-azure-java/index.md, themes/default/content/resources/getting-started-with-infrastructure-as-code-on-digital-ocean/index.md, themes/default/content/resources/kubecrash-2022/index.md, themes/default/content/resources/ndc-oslo-2022-fixing-broken-kubernetes-clusters/index.md, themes/default/content/resources/ndc-oslo-2022-reactive-infrastructure/index.md, themes/default/content/resources/pulumi-101-fundamentals-java-and-docker/index.md, themes/default/content/resources/pulumi-101-fundamentals-python-and-docker/index.md, themes/default/content/resources/securing-deployments-policy-as-code/index.md
https://github.com/pulumi/pulumi-hugo/issues/2260
=> update workshops with youtube videos

themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md, themes/default/content/resources/observability-as-code-with-new-relic/index.md
Part of: https://github.com/pulumi/marketing/issues/650, https://github.com/pulumi/marketing/issues/665
=> Add partner workshops in early 2023

themes/default/content/docs/guides/crosswalk/aws/ecr.md
- Update to be compatible with 1.0 changes
- Add Go, Java and YAML examples
- All examples regenerated from YAML
=> Update Crosswalk ECR Guide

themes/default/content/docs/guides/crosswalk/aws/eks.md
Update the examples in the Crosswalk EKS docs to use valid code from EKS 1.0 release.
Related to #2281
=> Update basic examples to use EKS 1.0

themes/default/content/blog/crosswalk-for-aws-1-0/index.md, themes/default/content/docs/guides/crosswalk/aws/_index.md, themes/default/layouts/crosswalk/aws.html
Add @nimbinatus's MiW video on Crosswalk for AWS v1 to blog, docs page, and marketing page.
=> Add crosswalk MiW video to pages

themes/default/content/docs/guides/self-hosted/components/console.md
=> Don't terrify our users reading about an ancient Node version.

themes/default/content/docs/guides/pulumi-packages/how-to-author.md
adding some missing information thats important for usability, accessibility, and seo in the registry
=> add missing info to package authoring

themes/default/content/docs/intro/concepts/resources/options/ignorechanges.md
Updated the examples based on https://github.com/pulumi/pulumi/blob/v3.48.0/sdk/go/common/resource/properties_path.go#L30-L46
[Direct link to doc change](http://pulumi-hugo-origin-pr-2301-fd616037.s3-website.us-west-2.amazonaws.com/docs/intro/concepts/resources/options/ignorechanges/)
=> Add wildcard examples to resource ignoreChanges docs

themes/default/content/resources/intro-to-infrastructure-as-code-with-yaml/index.md, themes/default/content/resources/introduction-to-infrastructure-as-code-with-typescript/index.md, themes/default/content/resources/simpler-pulumi-package-authoring/index.md
https://github.com/pulumi/marketing/issues/672
=> update workshops through EOY

themes/default/content/docs/guides/pulumi-packages/schema.md
Document https://github.com/pulumi/pulumi/blob/a0f2c1c09e39a850c37e7d9621e41e1c0bbd7492/pkg/codegen/schema/schema.go#L361
Addresses docs part of https://github.com/pulumi/pulumi/issues/11608
=> Add `willReplaceOnChanges` to package schema

themes/default/content/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply.md
Partial fix for https://github.com/pulumi/pulumi-kubernetes/issues/2258
=> Add docs for resolving k8s SSA field conflicts

themes/default/content/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply.md
Fix https://github.com/pulumi/pulumi-kubernetes/issues/2108
=> More docs for resolving k8s SSA field conflicts

themes/default/layouts/page/pricing.html
Added an FAQ about sales tax
Do not merge. Waiting on Sales tax work to go out before shipping.
=> Pricing page updates for sales tax

themes/default/content/docs/guides/crosswalk/aws/_index.md
Also add a couple of missing references to API gateway.
=> Update Crosswalk index page to use 1.0 examples

themes/default/content/docs/guides/self-hosted/components/api.md
What it says on the tin. Also reformatted markdown tables.
Fixes: https://github.com/pulumi/pulumi-service/issues/11649
=> Update self-hosted docs to include service metadata endpoint

themes/default/content/learn/pulumi-fundamentals/configure-and-provision/index.md, themes/default/content/learn/pulumi-fundamentals/create-a-pulumi-project/index.md, themes/default/content/learn/pulumi-fundamentals/create-docker-images/index.md
This PR modifies the three topics in the "Pulumi Fundamentals" pathway of Pulumi Learn to add Golang (to already existing TypeScript, Python, Java, and YAML). This includes code and explanatory text.
=> Add Golang to Fundamentals track of Pulumi Learn

themes/default/layouts/community/section.html
=> Link to GitHub discussions

themes/default/content/docs/reference/yaml/_index.md
Fixes `pu/yaml` [430](https://github.com/pulumi/pulumi-yaml/issues/430)
=> Add builtin `pulumi` variable to YAML reference

themes/default/content/blog/disable-default-providers/index.md
=> Fix smart quotes in code snip

themes/default/content/blog/how-to-create-and-share-a-pulumi-template/index.md
=> Fix typo in snippet

themes/default/content/challenge/one-quickstart.md, themes/default/content/challenge/startup-in-a-box.md
Adding banners to deprecate the swag distribution for the challenges
=> Turning off the challenges

themes/default/content/learn/building-with-pulumi/secrets/index.md, themes/default/content/learn/building-with-pulumi/stack-outputs/index.md, themes/default/content/learn/building-with-pulumi/stack-references/index.md
This PR adds YAML support to all topics within the "Building with Pulumi" pathway.
=> Add YAML to “Building with Pulumi” pathway

themes/default/layouts/shortcodes/templates/pulumi-new.html, themes/default/layouts/templates/overview.html, themes/default/layouts/templates/section.html
Fixes https://github.com/pulumi/devrel-team/issues/439.
=> Add a Deploy with Pulumi button option to template pages

themes/default/content/challenge/startup-in-a-box.md
https://github.com/pulumi/pulumi-hugo/issues/2337
=> remove swag from startup in a box challenge

themes/default/content/challenge/startup-in-a-box.md, themes/default/content/docs/intro/concepts/inputs-outputs.md, themes/default/layouts/challenge/list.html
This PR adds a GCP version of the first Pulumi Challenge, "Startup in a Box."
This PR also fixes some linting errors that cropped up from an earlier PR.
=> Add GCP version of the first Pulumi Challenge

themes/default/content/docs/get-started/azure/modify-program.md
"FileAsset" is not accepted needs to be "fileAsset" "block" need to be "Block"
=> fix syntax errors in YAML

themes/default/content/docs/intro/concepts/config.md
Fixes: https://github.com/pulumi/pulumi-hugo/issues/2373
=> Fix config docs

themes/default/content/learn/building-with-pulumi/stack-outputs/index.md
Noticed while reviewing another PR.
=> Remove duplicate word

themes/default/layouts/partials/head.html
Fixes: https://github.com/pulumi/pulumi-hugo/issues/2386
Fixes: https://github.com/pulumi/pulumi-hugo/issues/2385
=> Add additional text in titles for docs and registry

themes/default/content/learn/building-with-pulumi/secrets/index.md, themes/default/content/learn/building-with-pulumi/stack-outputs/index.md, themes/default/content/learn/building-with-pulumi/stack-references/index.md
This PR adds Go content to the "Building with Pulumi" Learn pathway.
=> [Learn] Add Go to Building with Pulumi pathway

themes/default/content/resources/getting-started-with-iac-aws/index.md
https://github.com/pulumi/marketing/issues/678
=> update iac/aws workshop for february

themes/default/content/resources/getting-started-with-iac-aws/index.md
Time offset was wrong (daylight savings is wild)
=> fix time zone on iac/aws workshop

themes/default/content/blog/crosswalk-for-aws-1-0/index.md
Add some concrete details for users of AWSx v0.x on how to migrate.
=> Add AWSx blog migration details

BLOGGING.md
Adds a line to BLOGGING.md to verify that logos are current. (Request from @SaraDPH.)
=> Add a line about using the right logo in blog posts

themes/default/data/team/team/engin-diri.toml
Hi,
This PR changes some of the metadata of my profile.
=> docs: change status from Engin Diri

BLOGGING.md
Adds a note about author images and fixes a couple of minor issues (404, formatting bug).
=> Add a note about author images

themes/default/content/challenge/one-quickstart.md, themes/default/content/challenge/startup-in-a-box.md
Adjusts the wording to mention including the URL to their post in swag requests.
=> Tweak the swag note

themes/default/content/blog/building-a-data-warehouse-on-aws-with-redshift-and-pulumi/index.md
The post should link to the next post in the series, but instead links to itself.
=> Fix a link in the Redshift post

themes/default/content/docs/intro/pulumi-service/projects-and-stacks.md
fixes https://github.com/pulumi/pulumi-hugo/issues/2437
=> fix-delete-stack-docs

themes/default/content/what-is/what-is-platform-engineering.md
Fixes https://github.com/pulumi/marketing/issues/701.
=> Add platform-engineering page

themes/default/content/what-is/what-is-platform-engineering.md
#2466 got merged before these were applied.
=> Fix a page title

themes/default/content/docs/intro/vs/cloud-templates/_index.md
=> cloud-templates: Fix double create

themes/default/content/resources/kubernetes-on-google-cloud/index.md
=> New Workshop - kubernetes on google cloud 

themes/default/content/docs/reference/project-file.md
we fixed up the content on the page and the nav to use project file so as not to confuse with pulumi yaml
but forgot about the url
this fixes up the url as well
=> fix project file url

themes/default/data/team/team/scott-lowe.toml
Update TOML file to reflect that Scott Lowe is now a Pulumi employee
=> Update author data

themes/default/content/resources/platform-with-aws-proton-and-pulumi/index.md
issue: https://github.com/pulumi/marketing/issues/714
=> New Workshop - platform with aws proton and pulumi 

themes/default/content/resources/getting-started-with-kubernetes-aws/index.md
issue: https://github.com/pulumi/marketing/issues/716
=> New Workshop - getting started with kubernetes aws 

themes/default/content/resources/getting-started-with-iac-pulumi-aws/index.md
issue: https://github.com/pulumi/marketing/issues/715
=> New Workshop - getting started with iac pulumi aws 

themes/default/content/resources/kubecon-eu-2023/index.md
Adding kubecon to resources list page
=> add kubecon to events list page

themes/default/layouts/page/kubecon.html
Fixing typos and language issues
=> Update to KubeCon

BLOGGING.md
To align with updated standards.
=> Tweak the recommended image size

themes/default/content/docs/intro/concepts/resources/names.md
=> Update names.md - Fix two small typos

themes/default/layouts/page/kubecon.html
text update per https://github.com/pulumi/marketing/issues/710#issuecomment-1446865965
=> update kubecon text with booth number

themes/default/content/resources/getting-started-with-kubernetes-google-cloud/index.md
=> New Workshop - getting started with kubernetes google cloud 

themes/default/content/resources/getting-started-with-kubernetes-azure/index.md
=> New Workshop - getting started with kubernetes azure 

themes/default/content/docs/intro/concepts/inputs-outputs.md
=> Fix Go example for pulumi.All

themes/default/content/blog/international-women-day-celebrating-women-in-tech/index.md
Updating the beginning of  Kelsey Dirks' quote
Adding Guin's
=> Updating Kelsey Dirks quote + adding Guin

themes/default/content/docs/intro/concepts/secrets.md
context
https://github.com/pulumi/registry/pull/2167#issuecomment-1460577492
=> add a note to secrets page

themes/default/content/docs/intro/concepts/update-plans.md
make update plans page title more specific
=> make update plans page title more specific

themes/default/layouts/page/pulumi-up-2022.html, themes/default/layouts/page/pulumi-up-2023.html
https://github.com/pulumi/marketing/issues/712#issuecomment-1464027393
=> add formcomplete script

themes/default/layouts/partials/head.html
issue: https://github.com/pulumi/registry/issues/2184
=> update title tags to replace slashes with dots for registry pages
