pulumi/pulumi-hugo

.github/workflows/pull-request.yml
scripts/ensure.sh

To align with https://github.com/pulumi/docs/pull/5671, which upgrades Hugo to 0.82 as well.
https://github.com/gohugoio/hugo/releases

Bump Hugo to 0.82

---

themes/default/content/docs/get-started/aws/deploy-changes.md

Using content will result in this error:
Diagnostics:
aws:s3:BucketObject (index.html):
error: unexpected asset content

Python s3.BucketObject takes source argument, not content

---

themes/default/content/docs/get-started/aws/modify-program.md
themes/default/content/docs/get-started/azure/modify-program.md
themes/default/content/docs/get-started/gcp/modify-program.md

Ported from https://github.com/pulumi/docs/pull/5609
This change reminds folks to create `index.html` from within their project directory so that a new `FileAsset` object can be created (and used as a source) successfully in the tutorial.

Add clause reminding people to create file from within project directory

---

themes/default/content/docs/get-started/install/_index.md
themes/default/content/docs/get-started/install/migrating-3.0.md

We'll want to actually have the migration guide explain beta usage until we get to the actual 3.0 release.

Update 3.0 migration instructions to match beta

---

.gitignore
themes/default/content/docs/reference/cli/_index.md

Fixes: https://github.com/pulumi/docs/issues/5668
Also ignores .idea folders to ensure these don't get checked in by something
We should standardise (in another PR) for what should go in a .gitignore)

Add docs to ensure users know Fish completions are supported

---

themes/default/content/docs/intro/concepts/inputs-outputs.md

Add an example of using output.all with keyword args

---

themes/default/content/docs/get-started/aws/deploy-changes.md
themes/default/content/docs/get-started/aws/modify-program.md

Without the last comma, go is unhappy
Signed-off-by: Matt Stratton <matt.stratton@hey.com>

Add comma after last arg for go example in AWS quickstart

---

themes/default/content/docs/guides/testing/integration.md

Fixes https://github.com/pulumi/home/issues/1293

Update integration test guide to account for Automation API

---

themes/default/content/docs/get-started/kubernetes/modify-program.md

Got a nil pointer dereference runtime error when running through the tutorial with the new ApplyT changes, so I added in this check.
Note: I wasn't sure what to return if the minikube `ClusterIP` value is nil, so I just return an empty string. Happy to change it to whatever the best practice is.

Fixed dereference issue in K8s Getting Started tutorial

---

themes/default/assets/sass/_pulumi-up.scss
themes/default/assets/sass/components/_audio.scss
themes/default/layouts/page/pulumi-up.html

Around one hour before the start of PulumiUP we want to link directly to BigMarker so that we can avoid people not receiving an email with a link to join. By registering directly with BigMarker and not our marketing forms people will be able to gain access to the webinar right away instead of waiting for an email.

Link directly to webinar from pulumiup page

---

themes/default/content/docs/guides/self-hosted/_index.md

We had a warning about a Docker x macOS bug. However, it has since been fixed. (Or at the very least, we cannot reproduce the problems you encounter if you have that option checked.) So removing it from the docs.
cc https://github.com/pulumi/pulumi-ee/issues/10

Remove warning about unchecking gRPC FUSE warning

---

themes/default/assets/sass/_hero.scss

This addresses https://github.com/pulumi/pulumi-hugo/issues/86, to decrease the gap between the homepage hero and content on especially tall screens.
With this change, for a screen height of 2150:

Add max height for homepage hero

---

themes/default/content/blog/automation-api-python/index.md
themes/default/content/blog/automation-api/index.md
themes/default/content/blog/getting-started-with-pac/index.md
themes/default/content/case-studies/credijusto.md
themes/default/content/product/_index.md

Fixes some errors from today's link-check run:
• /case-studies/credijusto/ → https://www.credijusto.com/ (HTTP_308)
• /case-studies/credijusto/ → https://www.credijusto.com/ (HTTP_308)
• /blog/automation-api/ → https://github.com/pulumi/pulumi/tree/master/sdk/python/lib/pulumi/x/automation (HTTP_404)
• /blog/automation-api-python/ → https://github.com/pulumi/pulumi/tree/master/sdk/python/lib/pulumi/x/automation (HTTP_404)
• /blog/getting-started-with-pac/ → https://siliconangle.com/2020/01/22/microsoft-exposes-250m-customer-service-records-via-misconfigured-elasticsearch-database/ (HTTP_500)
• /product/ → https://www.pulumi.com/docs/docs/guides/pulumi-packages/ (HTTP_403)
• /product/ → https://www.pulumi.com/docs/docs/guides/automation-api/ (HTTP_403)

Fix some broken links

---

themes/default/content/docs/guides/self-hosted/_index.md
themes/default/content/docs/guides/self-hosted/api.md
themes/default/content/docs/guides/self-hosted/console.md

Attempt to help with confusion between Self-Hosted and Self-Managed backends.

Add link to self-managed backend on self-hosted pages.

---

themes/default/content/docs/get-started/gcp/modify-program.md

Lists of member definitions need a comma after each member.
It's the smallest PR ever, but I'd be happy to contribute.

Fix a syntax error

---

themes/default/content/docs/guides/testing/unit.md

The `MockCallArgs` does not have `Inputs` as a property. This should be `Args`.
Source code: https://github.com/pulumi/pulumi/blob/master/sdk/go/pulumi/mocks.go#L34
Doc page: https://www.pulumi.com/docs/guides/testing/unit/#add-mocks _select golang examples_

Fix MockCallArgs property in Golang example

---

themes/default/content/docs/get-started/install/migrating-3.0.md

Noticed that this was missing when I upgraded some code and had to go searching in pulumi/pulumi to figure out which package it was in.

Add pulumi package to mocks upgrade example

---

themes/default/layouts/migrate/kube2pulumi.html
themes/default/layouts/migrate/tf2pulumi.html
themes/default/layouts/page/about.html
themes/default/layouts/page/support.html
themes/default/layouts/partials/contact-us.html

when looking at the contact us page, I noticed some leftover backgrounds, this removes them
changes to...
- /support
- /contact-us
- /kube2pulumi
- /tf2pulumi
- /about

remove bgs

---

themes/default/content/docs/intro/cloud-providers/github/setup.md

Fixes: https://github.com/pulumi/docs/issues/5359
Please note, the difference from that original issue is that
GITHUB_ORGANIZATION has been deprecated in favour of GITHUB_OWNER as
per https://github.com/pulumi/pulumi-github/#configuration

Adding github owner to the github provider setup details

---

themes/default/content/docs/intro/concepts/state.md

Change the variable name to better match AWS documentation. We want a user to enter `s3://my-bucket` rather than `s3://my-bucket.s3-us-east-1.amazonaws.com`

Change from `bucket-path` to `bucket-name`

---

themes/default/content/docs/guides/automation-api/concepts-terminology.md

Removing the section about custom workspaces because it isn't expected that users will be implementing these.
Fixes: #153

Update automation api guide

---

themes/default/assets/sass/styles.scss

This change addresses https://github.com/pulumi/pulumi-hugo/issues/136, to make the background of the "Common Architecture Types" header on the Solutions page slightly opaque.
Before this change:
With this change:

Update solutions page common architecture types header

---

themes/default/components/src/components.d.ts
themes/default/components/src/components/convert/convert.e2e.ts
themes/default/components/src/components/slot-machine/slot-machine.tsx
themes/default/components/src/components/swiper/swiper.e2e.ts
themes/default/components/src/components/swiper/swiper.tsx

Stencil's `@Method` decorator [expects methods to be defined `async`](https://stenciljs.com/docs/methods), so this change just declares them async to suppress the warnings we see in the console in development.
Update: Turned out we had a bit of logic to clean up as well (e.g., only use the `autoplay` module when autoplay is enabled), so did that, and tightened up some typings as well.

Fix Stencil async warnings

---

themes/default/content/docs/intro/cloud-providers/cloudflare/setup.md

CloudFlare API Keys are legacy but luckily pulumi-cloudflare already accepts API Tokens.

[CloudFlare] Update install instructions

---

themes/default/content/docs/intro/cloud-providers/digitalocean/_index.md

TypeScript reported that `do` is a reserved keyword and the homepage example didn't work out of the box as a result of that. The full API reference examples use `digitalocean` already.

Fix digitalocean example

---

themes/default/content/docs/guides/adopting/from_terraform.md
themes/default/content/docs/intro/vs/terraform.md

Fixes https://github.com/pulumi/docs/issues/4589 including customer feedback asking about OSS license comparison.
Also, updated some text on using tf2pulumi for Go and C#.

Updated structure of Pulumi v. Terraform doc

---

themes/default/content/blog/announcing-per-user-pricing-and-unlimited-stacks-for-teams/index.md
themes/default/content/pricing/open-source-free-tier.md
themes/default/layouts/page/pricing.html

a bit ago in community slack a user was confused on what apis meant here alongside webhooks, they thought it meant they couldn't interact with any apis unless they were on enterprise.
i believe this language is confusing so I've changed it to only say webhooks, pls let me know if you have any concerns or think I'm overlooking something with this change.

remove apis text from apis and webhooks

---

themes/default/assets/sass/_hero.scss
themes/default/assets/sass/_mixins.scss

There's not really a need to make buttons huge on wide screens, especially when everything else stays the same size. 
Fixes #170.

Don't super-size button labels

---

themes/default/content/blog/pulumi-2020-update/index.md
themes/default/content/blog/pulumiup-bring-your-whole-team-to-pulumi/index.md
themes/default/content/docs/get-started/crossguard/enforcing-a-policy-pack.md
themes/default/content/docs/guides/saml/_index.md
themes/default/content/docs/guides/scim/_index.md
themes/default/content/docs/guides/self-hosted/_index.md
themes/default/content/docs/guides/self-hosted/api.md
themes/default/content/docs/guides/self-hosted/console.md
themes/default/content/docs/intro/console/auditing.md
themes/default/content/docs/intro/console/collaboration/auditing.md
themes/default/content/docs/intro/console/organizations.md
themes/default/data/glossary.toml

Also consistently use "Pulumi Enterprise" to refer to the SKU, instead of "Pulumi Enterprise Edition".
Fixes #198.

Add Enterprise note to organizational enforcement of policy docs

---

themes/default/content/docs/get-started/crossguard/enforcing-a-policy-pack.md

noticed this numbering issue when reviewing the policy docs
/docs/get-started/crossguard/enforcing-a-policy-pack/
fixes part of #198

fix numbering

---

themes/default/content/docs/get-started/_index.md

The video on the get-started page looks out of place as it is now, centered and with shadowing that doesn't align with the other elements on the page. This just left-justifies the video and gives it a border and shadow treatment that looks consistent with the tiles above it.

Minor adjustments to video display

---

themes/default/assets/sass/_code.scss

Little thing I've been meaning to fix forever.
👇👇

Size code elements relatively in headings

---

Makefile
scripts/ensure.sh

We currently impose a restriction on Hugo version, pinning to the same version as what's used in CI. But this is technically unnecessary (Hugo's built-in `minVersion` warns when the CLI is too far behind what's required by the modules in use in a given site), and given how often Hugo updates, and how hard it is to install a specific version on certain platforms, it makes life more difficult for contributors. So this change just relaxes that restriction and leaves it up to `minVersion` to alert when necessary.

Relax the Hugo version restriction

---

themes/default/assets/sass/_header.scss

This was my oversight, actually. 😢 It should be correct, but because the `btn-primary` class I intended to extend is [contained in a block that excludes everything that isn't a marketing page](https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/assets/sass/_marketing.scss#L7), it had no effect. This should fix it up.
fixes #220

Fix header button

---

themes/default/content/docs/intro/console/auditing.md

Update audit log event list to include secret decrypted event.
link to page from preview below: http://pulumi-hugo-origin-pr-229-3882ffbd.s3-website.us-west-2.amazonaws.com/docs/intro/console/auditing/
fixes #230

add secret decrypted to audit log event list

---

themes/default/content/docs/intro/languages/_index.md

Fixes [a bad `relref`](https://github.com/pulumi/docs/pull/5986/checks?check_run_id=2587919846) and adjusts others to be properly root-relative.

Fix a bad relref

---

themes/default/assets/sass/_api-nodejs.scss

changing the docs to present data in a 2-col layout instead of 3-col layout which should make the content a bit easier for folks to consume
part of #234
you wont be able to use the link to view the pages, but I've included a few screenshots

change resource docs from 3-col to 2-col layout

---

themes/default/content/topics/containers.md

Fixes: #5187
Uses: https://github.com/pulumi/examples/blob/master/azure-ts-aci/index.ts

Migrate Azure ACI example to be azure-native

---

themes/default/content/docs/get-started/gcp/deploy-changes.md

The missing newline after the `choosable` shortcode is preventing the markdown from being rendered properly on these pages. This should fix it up.

Fix rendering issue in the GCP guide

---

themes/default/content/docs/get-started/aws/deploy-changes.md
themes/default/content/docs/get-started/gcp/deploy-changes.md

Our `csharp` templates [give these attributes lines of their own](https://github.com/pulumi/templates/blob/master/gcp-csharp/MyStack.cs#L15-L16), and this seems to be the convention as well. This just adjusts our guide pages to be consistent.

Put output declarations on separate lines

---

themes/default/layouts/shortcodes/configure-gcp.html

This just specifies the GCP project field to use when configuring `gcloud`.

Specify we should use the project ID with GCP

---

themes/default/content/docs/troubleshooting/_index.md

Currently Jaeger has the advantage of correlating traces from all Pulumi sub-processes. Linked pulumi/pulumi#7109

Instructions on local jaeger

---

themes/default/content/docs/get-started/aws/begin.md
themes/default/content/docs/get-started/azure/begin.md
themes/default/content/docs/get-started/gcp/begin.md
themes/default/content/docs/get-started/kubernetes/begin.md

In the GCP guide in particular, it's slightly strange that we say "you'll create a new project" after just having created a Google Cloud project. This just adds the word Pulumi to each of these steps for clarity.
This came out of the usability exercise we did yesterday, btw.

Disambiguate the kind of project you'll create

---

themes/default/assets/sass/_marketing.scss

They're currently following the styling of marketing pages, which makes their headings look hugs. This should fix 'em up.

Fix headings on legal pages

---

themes/default/content/resources/build-reusable-infrastructure-as-code-patterns/index.md
themes/default/content/resources/getting-started-with-google-cloud-platform/index.md

The timezones were off in two of the workshop listings. This fixes that up

Fix times for upcoming workshops

---

themes/default/assets/config/postcss.config.js
themes/default/assets/config/tailwind.config.js
themes/default/assets/sass/_api-python.scss
themes/default/assets/sass/_buttons.scss
themes/default/assets/sass/_code.scss
themes/default/assets/sass/_container.scss
themes/default/assets/sass/_copy-button.scss
themes/default/assets/sass/_header.scss
themes/default/assets/sass/_hubspot.scss
themes/default/assets/sass/_marketing.scss
themes/default/assets/sass/components/_convert.scss
themes/default/assets/sass/components/_install.scss
themes/default/assets/sass/styles.scss
themes/default/components/package.json
themes/default/content/docs/tutorials/aws/ecs-fargate.md
themes/default/layouts/docs/aws-list.html
themes/default/layouts/docs/list.html
themes/default/layouts/docs/single.html
themes/default/layouts/migrate/arm2pulumi.html
themes/default/layouts/migrate/kube2pulumi.html
themes/default/layouts/migrate/tf2pulumi.html
themes/default/layouts/page/pricing.html
themes/default/layouts/partials/header.html
themes/default/layouts/partials/home/ide.html
themes/default/layouts/partials/learn/topics.html
themes/default/layouts/partials/sidebar-cta.html
themes/default/layouts/shortcodes/github-buttons.html
themes/default/layouts/webinars/single.html
themes/default/package.json
themes/default/yarn.lock

Upgrades TailwindCSS, PostCSS, PurgeCSS, Autoprefixer, and CSSNano to their latest versions, and makes a few minor adjustments to make everything continue to lay out right.
https://tailwindcss.com/docs/upgrading-to-v2
Fixes #83.

Upgrade our CSS toolchain

---

themes/default/layouts/partials/head.html

We currently load Sentry in the default way, which blocks page rendering until the Sentry SDK finishes loading. This change uses a different approach that loads the Sentry SDK later, as an attempt to improve page performance. 
Fixes https://github.com/pulumi/docs/issues/5959. (🤞)

Lazy-load sentry

---

themes/default/content/docs/intro/cloud-providers/azuread/_index.md

Ensure setup page for azuread cloud provider points to azure-classic not azure native

---

themes/default/layouts/page/get-started.html
themes/default/layouts/partials/docs/breadcrumb.html
themes/default/layouts/partials/docs/toc.html

These are no longer needed. Related to https://github.com/pulumi/pulumi-service/issues/6676.

Remove query params

---

themes/default/layouts/blog/list.html
themes/default/layouts/blog/single.html
themes/default/layouts/docs/list.html
themes/default/layouts/docs/single.html
themes/default/layouts/partials/blog/sidebar.html
themes/default/layouts/taxonomy/author.html
themes/default/layouts/taxonomy/tag.html

This uses the mobile layout up to iPad width, which makes browsing the docs and blog a lot nicer on a tablet. (This used to be fine before the redesign, so I suspect between the redesign itself and the post-redesign upgrade to Tailwind 2, something must've shifted.)
Before: 
After:

Adjust docs & blog layout for tablets

---

themes/default/layouts/partials/blog/sidebar.html

we present 2 hamburger nav buttons on the blog page for small screens
fixes comment in https://github.com/pulumi/pulumi-hugo/pull/306#issuecomment-858064052
i also removed the link to the blog from the blog because I did not understand why that was there... pls let me know if its serving a purpose I'm overlooking
use a text label instead of an icon

fix nav toggle button

---

themes/default/assets/js/docs-feedback.js

The overlay currently sits "behind" the header bar (even with a higher z-index) because of its position in the DOM. This change reparents it temporarily when it's open and returns it to its position when it's closed.
Fixes #172.

Reparent the feedback dialog when it's "open"

---

themes/default/content/resources/building-event-driven-communications-with-twilio-and-aws/index.md
themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md
themes/default/content/resources/getting-from-code-to-cloud-with-vscode-and-pulumi/index.md

Fixes https://github.com/pulumi/marketing/issues/41
Fixes https://github.com/pulumi/marketing/issues/42
Fixes https://github.com/pulumi/marketing/issues/40
This PR adds the Twilio Webinar, NGINX livestream, and the VSCode livestream to the resources page. The livestream registration form are wired into a reminder email that will be sent 30 minutes before the stream starts with a link to join. Below are links to those emails.
NGINX: https://app.hubspot.com/email/4429525/details/48880188690/performance
VSCode: https://app.hubspot.com/email/4429525/details/48880249158/performance

Add Twilio webinar and two livestream events

---

themes/default/assets/sass/_api-python.scss

It appears we made a change at some point that made it so that our
CSS selector no longer selected the Python API docs as intended, leading
to virtually illegible rendering of those docs. Unless I'm mistaken, we
only use these docs for the Pulumi SDK now-a-days, and not the other
providers, so the fix just targets the styles to that section.
This isn't the first time this has happened (see
https://github.com/pulumi/docs/pull/1397), so I'd love to know if there
are any ideas on what we can do to structurally avoid this breaking again!

Fix poor Python API docs formatting

---

themes/default/content/docs/guides/crosswalk/aws/eks.md

This example doesn't compile. Unfortunately, the AWSX VPC constructor
appears to require an args bag, even though all properties of it are
optional. Also, the way you pass subnets seems to have changed in the
EKS class -- or maybe this was always a bug -- but the examples I
found in the EKS repo itself suggested this is the right way to do it.
Fixes #325.

Fix the EKS networking example

---

themes/default/content/resources/building-event-driven-communications-with-twilio-and-aws/index.md

Fixes: https://github.com/pulumi/marketing/issues/43
Changes the webinar title and description for the Twilio webinar.

Update Twilio webinar title and description

---

themes/default/assets/sass/_api-python.scss

This change prevents PurgeCSS from stripping out the CSS we use for our Python docs. 
I'll follow this up by making sure https://github.com/pulumi/docs/pull/6158 works as intended and we can get that merged as well to make sure we don't regress here again. (Thanks @joeduffy!)

Preserve Python docs CSS

---

config/_default/menus.yml
themes/default/content/docs/intro/languages/dotnet.md
themes/default/content/docs/intro/languages/go.md
themes/default/content/docs/intro/languages/javascript.md
themes/default/content/docs/intro/languages/python.md
themes/default/content/docs/reference/pulumi-sdk.md
themes/default/content/docs/reference/pulumi-yaml.md

This change adds the Pulumi SDK to the left-hand nav and
cross-links in a few more places (the language guides), while
also making them a little more visually appealing.
Fixes pulumi/docs#4523.

Make the Pulumi SDK reference docs more visible

---

themes/default/content/docs/guides/crosswalk/aws/eks.md

The Crosswalk/EKS docs are very good and are ranking highly on SEO.
However, we only had TypeScript examples, despite recently broadening
language coverage for our EKS component. This change adds language
choosers and equivalent examples in JavaScript, Python, Go, and C#.
Part of https://github.com/pulumi/docs/issues/3171.

Add more language coverage for Crosswalk/EKS docs

---

themes/default/layouts/page/pricing.html

in talking with @ericrudder he suggested we at least mention that prices are in USD in the faq. this does that, super open to feedback!
changes to `/pricing/` page

add usd to faq prices

---

themes/default/content/docs/guides/continuous-delivery/github-actions.md

while toying around with pulumi on github actions, I've copied & pasted the examples from the website and accidentally run `prettier` on them:
```
$ prettier .
.github/workflows/pulumi-deploy.yml
[error] .github/workflows/pulumi-deploy.yml: SyntaxError: All collection items must start at the same column (1:1)
[error] >  1 | name: Pulumi
[error]      | ^^^^^^^^^^^^
[error] >  2 |   push:
[error]      | ^^^^^^^
[error] >  3 |     branches:
[error]      | ^^^^^^^
[error] >  4 |       - master
[error]      | ^^^^^^^
[error] >  5 | jobs:
[error]      | ^^^^^^^
```
which made me wonder _why_, until I've realized the `on:` definition is missing from them

fix github actions

---

LEARN.md
Makefile
scripts/content/new-learn-module.sh
scripts/content/new-learn-topic.sh

Some of this stuff got lost with the split-off of pulumi-hugo. This PR restores the README and helpers and adjusts things to work with the new directory structure.
Keep in mind this is fairly weird-looking visually due to (a) having been built prior to the rebrand and (b) the focus on scaffolding, content structuring, navigation, and overall mechanics over fine-grained UX. So it could definitely use a proper visual pass. But the bones should be good enough for content authoring to proceed, knowing we'll likely need to make little improvements (add metadata fields, etc.) as that happens.

Add Learn README and helpers

---

themes/default/content/docs/intro/concepts/inputs-outputs.md

The example python code contains a syntax error and semicolons that are not usually used in python.

Fix syntax error and remove semicolons

---

themes/default/layouts/blog/single.html

Fixes #185 
Moved publish date to top of page, and set it as a standard text color.

Moved blog posts publish date to top of page, standard text color

---

themes/default/content/docs/guides/testing/unit.md

They are currently using a static method that isn't static.
Plus in one place we were getting userdata when it should have been tags﻿

Fixed csharp test examples

---

themes/default/content/resources/getting-from-code-to-cloud-with-vscode-and-pulumi/index.md
themes/default/layouts/page/cloud-engineering-summit.html
themes/default/layouts/partials/header.html

This PR adds the Cloud Engineering Summit landing page as submenu item to Cloud Engineering. The motivation for the change is to expose a link to the summit hype page that is discoverable. In the Cloud Engineering submenu felt like the natural place to put this link but open to other suggestions.

Add Cloud Engineering Summit to header submenu

---

themes/default/assets/sass/_icons.scss
themes/default/components/src/components.d.ts
themes/default/components/src/components/contact-us-form/contact-us-form.css
themes/default/components/src/components/contact-us-form/contact-us-form.tsx
themes/default/components/src/components/contact-us-form/test/contact-us-form.e2e.ts
themes/default/components/src/components/contact-us-form/test/contact-us-form.spec.tsx
themes/default/components/src/components/pulumi-multi-select-form/pulumi-multi-select-form.css
themes/default/components/src/components/pulumi-multi-select-form/pulumi-multi-select-form.tsx
themes/default/components/src/components/pulumi-multi-select-form/test/pulumi-multi-select-form.e2e.ts
themes/default/components/src/components/pulumi-multi-select-form/test/pulumi-multi-select-form.spec.tsx
themes/default/components/src/components/webinar-form-select/webinar-form-select.tsx
themes/default/content/contact.md
themes/default/layouts/migrate/cloudformation.html
themes/default/layouts/migrate/terraform.html
themes/default/layouts/page/confirmation.html
themes/default/layouts/page/contact.html
themes/default/layouts/page/show.html
themes/default/layouts/partials/contact-us.html
themes/default/layouts/partials/hand-raise-section.html
themes/default/layouts/partials/icons/team.html
themes/default/layouts/partner/aws.html
themes/default/layouts/partner/azure.html
themes/default/layouts/partner/gcp.html
themes/default/layouts/topics/containers.html
themes/default/layouts/topics/kubernetes.html
themes/default/layouts/topics/serverless.html
themes/default/static/icons/team.svg

Fixes https://github.com/pulumi/pulumi-hugo/issues/119
This PR replaces the Contact Us forms throughout the marketing site with a four card section that directs people to "different" places based on their request. Mainly we are hoping to ensure our Support questions are routed through the correct system and so we can differentiate between different types of requests.
I also updated the Contact Us page to be much simpler and have a selector on the type of the form so the user can pick what type of "Contact Us" they want.

Consolidate contact us forms

---

themes/default/content/resources/building-event-driven-communications-with-twilio-and-aws/index.md

This PR removes the Twilio webinar from the resources page.

Remove July 27th Twilio webinar

---

themes/default/content/docs/guides/continuous-delivery/gitlab-app.md

Since all new organizations are Pulumi-managed, by default, if a user wants to configure the GitLab app, they must ensure a couple of things before doing the GitLab side of the setup. This PR clarifies those prerequisites.
Page to review: Under the **User Guides** nav header > Continuous Delivery > Pulumi GitLab Integration

Add prerequisites section to configure the GitLab App

---

themes/default/layouts/migrate/arm2pulumi.html
themes/default/layouts/migrate/kube2pulumi.html
themes/default/layouts/migrate/tf2pulumi.html
themes/default/layouts/page/about.html

This PR transitions the remaining contact us forms on the website to the new Hand Raise sections offering people different options for contact our team.

Replace old contact us forms with hand raise section

---

themes/default/archetypes/blog-post/index.md

The linter task will flag/block if this field is omitted, so it's not optional. This provides clarity for folks doing blogs for the first time.

Update comment in blog post archetype for clarity

---

BLOGGING.md

This PR updates BLOGGING.md with how to publish blogs with titles longer than 60 characters.

Update BLOGGING.md to add allow_long_title to front matter

---

themes/default/content/docs/guides/testing/unit.md

Fully qualify `MockResourceArgs` and `MockCallArgs` (first commit).
Also, while making changes here, use tabs consistently in Go snippets (second commit).

Fix go unit test snippet

---

themes/default/content/blog/top-5-things-for-azure-devs-kubernetes-infrastructure/index.md

The trailing `/` is causing the [integration build to fail](https://github.com/pulumi/docs/pull/6351/checks?check_run_id=3324641131) in pulumi/docs.

Fix a relref

---

themes/default/content/docs/reference/cli/_index.md

I believe there is a mistake in the docs when generating auto completion for fish shell.
It looks like a general code snippet has been used and the `yourprogram` has not been replaced with `pulumi`.
This did not work until I changed the fish completion filename to `pulumi.fish` which I have done in the example command shown in the docs.

docs: fish completion generator example fix

---

themes/default/content/docs/intro/cloud-providers/azuread/_index.md
themes/default/content/docs/intro/cloud-providers/azuread/setup.md

Fixes: https://github.com/pulumi/pulumi-azuread/issues/180
Fixes: https://github.com/pulumi/pulumi-azuread/issues/169
Fixes: https://github.com/pulumi/pulumi-hugo/issues/295

Adding a specific setup page for AzureAD due to provider prefix

---

themes/default/content/docs/guides/pulumi-packages/schema.md

React to changes from https://github.com/pulumi/pulumi/pull/7059
- Remove `plain` and `plainInputs` array properties
- Add a bool `plain` property to `Type`
Fixes #520

Update Pulumi Package schema docs for plain values

---

themes/default/assets/sass/_header.scss

When search in docs, the header container covers search modal.
So I moved `sticky` class of `.header-container` to `&.is-pinned`.
Before:
After:

Fix header not to cover search modal

---

themes/default/assets/sass/_header.scss

This reverts commit 4d443d97ef9a44f0b9e2a6ea985337fb326aa1fd. (I failed to notice before merging that the change causes main-nav menus to fall behind hero content, rendering their items inaccessible.)

Revert "Fix header not to cover search modal (#533)"

---

themes/default/content/docs/get-started/install/_index.md

Update the PowerShell script to replace the correct placeholder for installing a specific version of the CLI
This is the result of the current script listed in https://www.pulumi.com/docs/get-started/install/#installation-script for Windows. Notice how it still downloads the latest version. It's because the placeholder `${latestVersion}` does not exist. It should be `${Version}`.
```
C:\Users\ploke>@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; $version = '3.10.0'; iex ((New-Object System.Net.WebClient).DownloadString('https://get.pulumi.com/install.ps1')).Replace('${latestVersion}', $version)" && SET …
```

Fix CLI installation script command for Windows

---

themes/default/layouts/partials/head.html

We currently expose a frontmatter param, `block_external_search_index`, that seems intended to prevent a page from being indexed. However it looks like that only keeps the page from being listed [in sitemap.xml](https://github.com/pulumi/pulumi-hugo/blob/4d443d97ef9a44f0b9e2a6ea985337fb326aa1fd/themes/default/layouts/_default/sitemap.xml#L4), it doesn't actually keep it from being indexed by other means. This change adds a check to the `head` partial to add a `noindex` meta tag when `block_external_search_index` is `true`.

Support page-level noindex

---

themes/default/content/resources/building-event-driven-communications-with-twilio-and-aws/index.md
themes/default/content/resources/docker-show-multi-language-components/index.md
themes/default/content/resources/getting-started-with-aws/index.md

This PR removes a workshop, updates the time of two workshop/livestreams, and fixes a title in a URL.

Fix up event dates and typo for upcoming workshop

---

themes/default/content/blog/announcing-per-user-pricing-and-unlimited-stacks-for-teams/index.md

folks are starting to get confused by this old pricing blog and the new pricing model
this drafts the old blog so folks don't continue to use the information in it
[community slack convo](https://pulumi-community.slack.com/archives/C01PF3E1B8V/p1628510974034900)
[internal slack convo](https://pulumi.slack.com/archives/C01ADF2C8KC/p1628514904003900)
[internal community chat convo](https://pulumi.slack.com/archives/CG326KPTM/p1628511070033200)

adjust messaging on old pricing blog

---

themes/default/layouts/page/cloud-engineering-summit.html

Just as the title states, there were some commented out relrefs that were causing a build error for the docs repo.

Remove commented out relrefs causing build error

---

themes/default/content/cloud-engineering-summit/sessions.md
themes/default/layouts/page/cloud-engineering-summit-session-list.html
themes/default/layouts/page/cloud-engineering-summit.html

Just as the title states, this PR adds a session list page to the Cloud Engineering Summit.

Add sessions list page for Cloud Engineering Summit

---

themes/default/archetypes/whitepaper/index.md
themes/default/assets/sass/_event-list.scss
themes/default/content/resources/getting-started-with-infrastructure-as-code-guide/index.md
themes/default/layouts/resources/list.html

Fixes: https://github.com/pulumi/pulumi-hugo/issues/554
This PR adds the Dzone ref card as a gated resources. It also adds support for a `Whitepapers` category to the resources page. I created a new archetype as I suspect we will have more of these in the furture.

Add dzone ref card and whitepapers to resources

---

themes/default/layouts/learn/section.html

Adjusts the spacing between the items on the Learn index page:
https://user-images.githubusercontent.com/274700/133527507-94c28079-adb3-47c3-9598-f67893d94bb0.mov

Adjust the spacing between Learn items

---

themes/default/content/docs/intro/cloud-providers/azure-classic/_index.md

This PR improves the note on the Azure Classic intro page to make it clearer why you might use Azure Native instead.﻿

Improved explanation of Azure Native vs Azure Classic

---

themes/default/assets/sass/_header.scss

a community member opened up a pr to fix the issue where the top nav is still displayed when the docs search results dialog is open but it was later discovered that this prevented the menus from appearing on top.
ref: https://github.com/pulumi/pulumi-hugo/pull/533
im adding that back in, and also adding a z-index to the nav menus
@cnunciato @zchase pls let me know if this isn't the correct way to fix this

fix docs search results and nav issue

---

themes/default/content/docs/intro/languages/javascript.md

Pulumi no longer overrides certain tsconfig.json options (https://github.com/pulumi/pulumi/pull/7068). This change updates the docs to be in-line with the current behavior.

Update docs related to TypeScript

---

package.json
themes/default/package.json
themes/default/yarn.lock
yarn.lock

Requesting to update to dart-sass to enable m1 local builds (node-sass won't build on arm64 because it doesn't support the platform). It should be a simple lift-and-shift with no additional work needed according to https://sass-lang.com/blog/libsass-is-deprecated.
Marked as `do-not-merge` so there's time to chat if needed.
cc: @mattstratton @katcosgrove

build(sass): update to dart-sass to enable m1 local builds

---

themes/default/assets/sass/components/_convert.scss
themes/default/components/src/components/convert/convert.tsx
themes/default/package.json

Adds a close button to dismiss warning and error messages so as not to obscure the code we were able to render.
https://user-images.githubusercontent.com/274700/135174077-9cfac9fb-bc82-429b-b243-f571cb05e17b.mov
Fixes #636.

Add support for dismissing alerts in converter

---

themes/default/content/cloud-engineering-summit/_index.md
themes/default/content/cloud-engineering-summit/agenda.md
themes/default/content/cloud-engineering-summit/sessions.md
themes/default/content/cloud-engineering-summit/speakers.md

I noticed that in open graph previews (slack, etc) the date of the event isn't in text, and thought it might be helpful to add that.

Add date to meta info for CES pages

---

themes/default/content/cloud-engineering-summit/_index.md
themes/default/content/resources/build-reusable-infrastructure-as-code-patterns/index.md
themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md
themes/default/content/resources/getting-started-with-automation-api/index.md
themes/default/content/resources/getting-started-with-aws/index.md
themes/default/content/resources/getting-started-with-azure-native/index.md
themes/default/content/resources/getting-started-with-google-cloud-platform/index.md

This PR does just as the title states and cleans up the workshop times for the Cloud Engineering Summit.

Update the times of the Cloud Engineering Summit workshops

---

themes/default/layouts/page/pricing.html

adding the audit logs export to pricing page
it is available to select enterprise customers, so we are listing it as available

add audit logs export to pricing page

---

themes/default/content/blog/resource-methods-for-pulumi-packages/index.md

While we don't yet support authoring multi-language components in .NET, we do support using them from .NET. Since the blog post mentions being able to use methods from all supported Pulumi languages, I wanted to show usage from .NET.
This change adds back the C# chooser tabs for usage examples, and adds authoring snippets for C# so that the choosers on the page work correctly. The C# authoring snippets just mention that C# authoring isn't supported yet, with a link to the GH issue for upvoting.

Include C# examples in methods blog post

---

themes/default/content/docs/reference/cli/environment-variables.md

- Adds `PULUMI_CONFIG`
- Adds `PULUMI_CONFIG_PASSPHRASE_FILE`
- Alphabetize entries
- Fix code formatting

Add a few missing env variables to "Environment Variables" page.

---

.github/workflows/push.yml

This change adds a `push` workflow that runs `hugo mod get github.com/pulumi/theme` whenever a change is merged to `master` and commit any `go.*` diffs to `master` as well. Most of the time, this won't have any effect. But on the off chance a change gets merged into `master` containing a  deliberately applied `go.mod` reference -- for example, when a developer is working concurrently on a branch of `pulumi/theme`, and wants to pin to that branch during development or for PR previews -- other runners of `make serve` or `make ci-pull-request` won't accidentally get an outdated (or even no-longer-existing) version of `pulumi/theme`.
This change only affects local development and PR previews. It won't have any effect on pulumi/docs builds or on other consumers of this module. The motivation …

Add a push workflow, always use latest theme

---

themes/default/content/docs/intro/concepts/secrets.md

Adding missing double quote when setting `AZURE_KEYVAULT_AUTH_VIA_CLI` to `"true"`.
Added a few more words to indicate the double quotes are required.

doc fix: Set `AZURE_KEYVAULT_AUTH_VIA_CLI` correctly

---

themes/default/layouts/shortcodes/aws-resource-note.html

- we should not be using quote styling for things that are not quotes, this removes it and uses the note styling instead
- note that we are repeating the note definition because you cannot use a shortcode inside of another shortcode definition
note to reviewers: i don't believe you will be able to preview this anywhere until it gets to the docs

remove quote thats not a quote from shortcode

---

themes/default/content/docs/intro/languages/go.md

I go an error with the message
> embed: package embed is not in GOROOT
when using Pulumi with Golang version 1.15.
Since `embed` was introduced in version 1.16 I believe this is the minimum version, updating to this version did solve the problem with embed.

Update min Go version

---

themes/default/layouts/partials/head.html

AnchorJS, which we use for our auto-anchor links to sections in our docs, is not running in the Registry section of the site. This adds such support.
1/2 of fixes for https://github.com/pulumi/registry/issues/239
See [this PR](https://github.com/pulumi/registry/pull/308) for remaining work.

Add Registry to sections which use anchor-js

---

themes/default/layouts/page/pulumi-up.html
themes/default/layouts/partials/head.html
themes/default/layouts/partials/right-nav-ad.html

This PR fixes some SEO issues identified within SEMrush. The biggest issue we have are some duplicate Title tags, mostly from Blog "tag" pages. There were also a ton a 302 redirect warnings because there was a missing `/` at the end of the CES CTA.

Fix some SEO issues and warnings

---

themes/default/content/product/_index.md
themes/default/layouts/page/product.html

Surface the public roadmap in the "open source" section of our product page

Add link to public roadmap blog on /product/

---

themes/default/layouts/partials/footer.html

we have an apis link in the footer that went to the docs API reg list page which we will prolly be removing at some point in the future; i updated the link to send you to registry and use that link text; if anyone feels strongly that it should be `Pulumi Registry` instead of just registry pls let me know, happy to update

update footer link and link text; apis -> registry

---

themes/default/content/what-is/what-is-infrastructure-as-code.md
themes/default/layouts/what-is/single.html

This PR adds support for videos on the "What is" pages.
Fixes: https://github.com/pulumi/pulumi-hugo/issues/834

Add video to what is iac page

---

themes/default/layouts/partials/footer.html

@gthuang added a link to the roadmap on the products page, but i mentioned in that pr that i think we should also add it to the footer https://github.com/pulumi/pulumi-hugo/pull/843#issuecomment-964664641
let me know what you think, super open to placement and link text

adding roadmap to footer

---

themes/default/content/docs/guides/crosswalk/aws/iam.md

Just what it says on the tin.
I manually tested all of the examples. Are we doing any automation for doc examples these days that I should be adding this to?

Add AWS Crosswalk IAM exmaples in all languages

---

themes/default/content/docs/guides/crosswalk/aws/eks.md

sample code imports pulumi eks package as aws. I think it should be imported as eks instead. 
as later in the code eks.cluster is used

Fix import reference to aws to be eks in eks example

---

themes/default/content/blog/azure-container-apps/index.md

i noticed that the links to the example repo were fairly easy to miss, and also weren't descriptive outside of the rest of the text. this adjusts them to clearly describe where they will send you, it also gives them more weight on the page so they arent as easy to miss. i also fixed one here link.
page changed: blog/azure-container-apps/

adjust link text in azure containers blog post

---

themes/default/content/docs/intro/languages/dotnet.md
themes/default/content/docs/intro/languages/go.md
themes/default/content/docs/intro/languages/javascript.md
themes/default/content/docs/intro/languages/python.md

i noticed that the get started sections on the language pages were all different. this aligns them all to direct folks to the get started guides, to match what .net is currently doing

align language get started sections

---

themes/default/layouts/shortcodes/install-go.html

New users who are on older versions of Go may encounter an error with `embed` being required by newer versions of Pulumi. 
Ran into this while I was getting started with the tool -- Debian is shipping 1.15 and Ubuntu LTS ships with 1.13. This won't matter for too long -- Debian will be shipping 1.17 in `testing` soon and the next Ubuntu LTS will likely ship with an up to date version.

Include note about Go 1.16 minimum

---

themes/default/layouts/shortcodes/resource-providers.html

Hypothesis: we can infer the user's intent ("I want API docs") from where these links are located, so we should take them directly to the part of Registry that matches their intent (API docs).

Update /docs/reference/pkg links to go directly to API docs

---

themes/default/content/docs/guides/crosswalk/kubernetes/identity.md

Stumbled upon this one under Azure tab in:
https://www.pulumi.com/docs/guides/crosswalk/kubernetes/identity/
The guide does not pin the dependencies and I believe something might have bit-rotted. I've tested the change compiles against the latest dependencies but I've not done the due diligence here to check the entire guide and deploy it.

Fix code in kubernetes/identity.md that does not compile

---

themes/default/content/aws-reinvent-2021/_index.md
themes/default/content/resources/aws-dev-day-getting-started-with-aws/index.md
themes/default/content/resources/aws-howdy-partner-twitch/index.md
themes/default/layouts/page/aws-reinvent-2021.html

Adding a landing page with the events, newsroom, hiring, and get started CTAs. This page will be linked to QR code at re:Invent in 2021.

Add landing page for reinvent qr code

---

.github/workflows/push.yml
config/_default/config.yml
go.mod
go.sum

It's a bit cumbersome not to have at least some Registry content available while developing in this module. So this change just makes the Registry module available for development and PR previews.

Add Registry for local dev and PR previews

---

themes/default/content/resources/aws-dev-day-getting-started-with-aws/index.md

Fixes a bad link for the AWS Dev Day workshop.

Fix URL slug for aws dev day workshop

---

themes/default/content/resources/cloud-engineering-summit/index.md

Noticed the CES link now 404s (from https://www.pulumi.com/resources/#featured), so hopefully this is the right way to remove it from that page. (If there's some other way to do this, though, let me know!)

Unlist Cloud Engineering Summit

---

scripts/content/new-learn-module.sh
scripts/content/new-learn-topic.sh

We've made a few changes recently to this repo's configuration that seem to have affected the Learn archetypes. This change adds explicit path prefixes in order to unbreak them.

Add path prefixes for Learn content helpers

---

themes/default/layouts/partials/head.html

Fixes #901 
This adds support for a canonical tag for when we cross-post from someone else's blog (only for use for community blogs, etc)
Please do not merge this without approval from @zchase 

Add support for custom canonical tag

---

themes/default/content/docs/intro/console/pulumi-button.md

I re-ordered the explicit vs. implicit sections here and added guidance on not using implicit. I considered removing implicit completely, but felt like someone might choose to consider it knowing the drawbacks? Open to removing it completely though.

Update guidance on implicit templates for Deploy Button

---

themes/default/content/learn/building-with-pulumi/_index.md
themes/default/content/learn/building-with-pulumi/secrets/index.md
themes/default/content/learn/building-with-pulumi/stack-outputs/index.md
themes/default/content/learn/building-with-pulumi/stack-references/index.md
themes/default/content/learn/building-with-pulumi/testing/index.md
themes/default/content/learn/building-with-pulumi/understanding-stacks/index.md
themes/default/layouts/taxonomy/author.html
themes/default/layouts/taxonomy/tag.html

Our author and tag listings are unintentionally showing Learn content (which also happens to have `author` and `tag` metadata), so this change add a filter to those pages to have them show only content from the blog. 
This is a less-than-ideal fix in that it _should_ be possible (one would think) to have Hugo generate section-specific `tag` and `author` taxonomy pages, but a quick look through the docs and some fiddling this morning didn't make that super clear to me. So we'll probably want to revisit this once we start thinking about supporting taxonomy pages outside of just the blog.

Filter author and tag taxonomy templates to blog posts only

---

themes/default/content/blog/aws-quickstart-registry/index.md

When these `` dividers are intentionally placed, Hugo will respect them (https://gohugo.io/content-management/summaries/#automatic-summary-splitting), so this change puts it a little closer to the beginning of the post.
Fixes #952.

Move the `more` break up a bit

---

themes/default/content/docs/intro/concepts/organizing-stacks-projects.md

Somehow, this got linked incorrectly. ([The current redirect 404s.](https://www.pulumi.com/docs/intro/concepts/organizing-stacks-projects/)) This should be the right place.

Fix a bad redirect

---

themes/default/content/docs/guides/continuous-delivery/gitlab-app.md

GitLab projects that have enabled the [Merged Results Pipeline](https://docs.gitlab.com/ee/ci/pipelines/pipelines_for_merged_results.html) feature will not be able to use the Pulumi GitLab integration for MR comments. I have added a note in the guide to setup that integration warning users about the use of that feature.

Add a warning about enabling merged results pipeline in GitLab

---

themes/default/content/docs/guides/crosswalk/kubernetes/app-services.md

fixes #977 
changes are being made to `docs/guides/crosswalk/kubernetes/app-services/`

fix crosswalk links to example repo

---

config/_default/config.yml

Hugo v0.91.0 added a new key to the config, "security", defining allowlists for env vars and other things. This change allows 0.91 and 0.92 to build and serve the Pulumi site.
TODO:

Allowlist env vars for hugo 0.92

---

.github/workflows/pull-request.yml
.github/workflows/push.yml
.github/workflows/scheduled-cleanup.yml
README.md
scripts/ensure.sh

This PR upgrades all workflows to use the latest versions of Hugo, Go, and Node, removes the version checks from the `ensure` script, and updates the README to include minimum versions.
I'll propagate these changes to the Registry and Docs repos next, but I wanted to get these in first to keep folks running `make serve` locally from being unable to work on content simply because their local tool versions didn't line up perfectly with what we run in CI (and some tools, like Hugo, make it fairly painful to move between versions).

Upgrade Hugo, Node, Go versions

---

themes/default/content/docs/troubleshooting/_index.md

The environment variable used/set for getting logs is `TF_LOG` which you can set to `TRACE`.
I believe this is just a simple mistake combining `TF_LOG` and `TRACE` to accidentally have `TF_TRACE` in the docs.

[DOCS] change TF_TRACE -> TF_LOG

---

themes/default/content/docs/guides/saml/okta.md

It seems that the Organization Settings tab has changed and "Access Management" now contains the "Membership Requirements" which controls the SAML SSO configuration. Additionally, there are several IDPs and we need to select the correct one.

Update SSO configuration instructions for Okta

---

themes/default/content/docs/guides/continuous-delivery/github-actions.md

Per: https://www.pulumi.com/docs/intro/languages/go/
> Pulumi supports writing your infrastructure as code using the Go language. Go 1.16 or later is required.
The basic `pulumi new go` setup fails to preview when using Go < 1.16.x in the provided GitHub Actions templates.
Also update to the current GHA release (v2).

chore(go): Update GHA to supported Go version

---

themes/default/content/docs/intro/concepts/resources/options/additionalsecretoutputs.md
themes/default/content/docs/intro/concepts/resources/options/aliases.md
themes/default/content/docs/intro/concepts/resources/options/customtimeouts.md
themes/default/content/docs/intro/concepts/resources/options/deletebeforereplace.md
themes/default/content/docs/intro/concepts/resources/options/dependson.md
themes/default/content/docs/intro/concepts/resources/options/ignorechanges.md
themes/default/content/docs/intro/concepts/resources/options/import.md
themes/default/content/docs/intro/concepts/resources/options/parent.md
themes/default/content/docs/intro/concepts/resources/options/protect.md
themes/default/content/docs/intro/concepts/resources/options/provider.md
themes/default/content/docs/intro/concepts/resources/options/providers.md
themes/default/content/docs/intro/concepts/resources/options/replaceonchanges.md
themes/default/content/docs/intro/concepts/resources/options/transformations.md
themes/default/content/docs/intro/concepts/resources/options/version.md

A follow-up to #997, this change makes the `Providers` menu item appear in the Resource Options menu by specifying explicit menu `identifier`s. (See [this comment](https://github.com/pulumi/pulumi-hugo/pull/997#pullrequestreview-862751882) for additional context.) Also adds page-specific meta descriptions for those that were re-using the description from the Resource Options overview page.

Specify explicit menu identifiers for resource-options items

---

themes/default/archetypes/learn/module/_index.md
themes/default/archetypes/learn/topic/index.md
themes/default/content/learn/_index.md
themes/default/content/learn/abstraction-encapsulation/_index.md
themes/default/content/learn/abstraction-encapsulation/abstraction/index.md
themes/default/content/learn/abstraction-encapsulation/component-resources/index.md
themes/default/content/learn/abstraction-encapsulation/encapsulation/index.md
themes/default/content/learn/building-with-pulumi/_index.md
themes/default/content/learn/building-with-pulumi/secrets/index.md
themes/default/content/learn/building-with-pulumi/stack-outputs/index.md
themes/default/content/learn/building-with-pulumi/stack-references/index.md
themes/default/content/learn/building-with-pulumi/testing/index.md
themes/default/content/learn/building-with-pulumi/understanding-stacks/index.md
themes/default/content/learn/pulumi-fundamentals/_index.md
themes/default/content/learn/pulumi-fundamentals/configure-and-provision/index.md
themes/default/content/learn/pulumi-fundamentals/create-a-pulumi-project/index.md
themes/default/content/learn/pulumi-fundamentals/create-docker-images/index.md

Early on, I included the `block_external_search_index` setting in our module and topic archetypes thinking we might want to publish and iterate on content (behind a "coming soon" home page or something) without risk of exposing that content it to crawlers. Now that we've launched, though, and we have PR previews, etc., we no longer need it.

Remove block_external_search setting from Learn content

---

themes/default/content/docs/guides/self-hosted/_index.md

the note that says why the links don't work is below the actual links which make it difficult for folks to be aware that the links wont work. this moves it up, above the table, with the hope that folks might read it before trying to use the links.

move self-hosted repos note up

---

themes/default/content/crosswalk/_index.md
themes/default/layouts/partials/head.html

We don't currently have any content on this page, and it's been search-engine indexed, so we should probably send those who find it to our current Crosswalk for AWS docs.
This change does two things:
* Asks Google not to index /crosswalk
* Redirects to https://www.pulumi.com/docs/guides/crosswalk/aws/
If we do plan to fill this page out with content, though, we might want to redirect temporarily rather than permanently.

Redirect /crosswalk

---

Makefile
scripts/content/new-learn-module.sh
scripts/content/new-learn-topic.sh

Happened to notice the `make new-blog-post`, `make new-learn-module`, and `make new-learn-topic` helpers stopped working with the most recent version of Hugo, which switched things up a bit. This PR should fix 'em up.
Before: 
```
$ make new-blog-post 
Slug (e.g., my-new-post): how-i-spent-my-summer-vacation 
hugo new --kind blog-post "blog/how-i-spent-my-summer-vacation"
Error: could not determine content directory for "blog/how-i-spent-my-summer-vacation/index.md"
```
After: 
```
$ make new-blog-post 
Slug (e.g., my-new-post): how-i-spent-my-summer-vacation
hugo new --kind blog-post --contentDir themes/default/content \
"blog/how-i-spent-my-summer-vacation"
Content dir "/Users/christian/go/src/github.com/pulumi/pulumi-hugo/themes/default/content/blog/how-i-spent-my-summer-vacation" …
```

Fix archetype scripts

---

themes/default/data/awards.toml

I mistakenly linked to the 2021 awards. 🤦

Fix awards link

---

themes/default/content/blog/announcing-public-preview-update-plans/index.md

the github discussions link at the bottom of the blog was 404ing
[internal slack convo](https://pulumi.slack.com/archives/C011EMDQ8JE/p1644432675934159)

fix link in update plans blog

---

themes/default/layouts/page/pricing.html

this came up in a review, we don't have the hyphen in the heading so its a bit weird to have it in the paragraph
@kimberleyamackenzie figured id just push this out now instead of waiting on the other release, but letting you know in case it messes anything up for you

remove hyphen in pricing intro

---

themes/default/content/docs/guides/crosswalk/aws/lambda.md

The second argument of `aws.s3.Bucket.get` method should be the `id` of the bucket, not`arn`. 
Following the document may cause the error `InvalidARNError`.

Fix s3.Bucket.get usage

---

themes/default/content/learn/abstraction-encapsulation/_index.md

one of the 3 learn cards has a longer description than the rest; we should try to keep these to no more than 3 lines. @nimbinatus happy to adjust the content in a different way if ya don't think my edit will work.

shorten content on learn card

---

BLOGGING.md
themes/default/archetypes/blog-post/index.md

this removes the draft: true from our blog template.
since ive been here ive never seen anyone merge a blog set to draft on purpose.
but i have seen a lot of folks merge it without wanting it to be a draft.
and its slow to get out the fix to undraft it.
alternatively, i can leave draft in and set it to false if we think having it there so folks know about it would be helpful
@cnunciato do you have negative feelings about this? is keeping draft: true important to you?

remove draft from blog template

---

.github/workflows/pull-request.yml
.gitignore
Makefile
scripts/ci/build-full-site.sh

This change adds a step to check out the docs repo and run a full website build for every PR commit. It should help us identify `{{< relref >}}` issues that would otherwise fail when pulled into pulumi/docs PRs later.
Note that this **adds** about 15 minutes to PR build times, and _does not_ push the full website in PR previews, as that'd take much longer. (Preview links will still consist of the same content they do today.) If we find that 15 minutes is too long (and I suspect we might), we could fairly easily convert this work to be done in response to a GitHub slash command later.

Run full website builds for PRs

---

.gitignore

This was a mistake; in #1106, I added a script to build the full site and write it to a local directory, and that directory was initially called `docs`, later changed to `temp-docs`. I ended up doing the post-build cleanup work in the script, though, but forgot to go back and remove the entry from `.gitignore`.

Remove errant ignore

---

themes/default/content/enterprise/_index.md
themes/default/layouts/page/enterprise.html
themes/default/layouts/partials/banner.html

Just as the title states this PR updates the marketplace link and the case study buttons so they don't extend past the box as per the feedback in Slack.

Update marketplace link and case study buttons on /enterprise

---

themes/default/layouts/docs/list.html
themes/default/layouts/index.html

This PR tackles two items affecting small screens:
1) Adds a toggle button for the docs nav at small screens.  Previously the nav content dropped to the bottom of the page which wasn't super clear or easy to use - this PR pulls in the same solution we use for the blog by adding a toggle button that shows the nav at the top of the page when toggled open.   https://github.com/pulumi/pulumi-hugo/issues/315
Since I have worked in docs less, would love some eyes to make sure I got everywhere the nav is (I checked both docs home and individual pages) - not sure if I might be missing something. 
2) Adjusts buttons for the Atlassian case study on the home page so they move to a column at small screen sizes.  https://github.com/pulumi/pulumi-hugo/issues/1111

Add docs nav toggle for small screens; fix overlapping buttons on small screens

---

.github/workflows/push.yml

We've had branch protections disabled for a bit, in order to allow for certain `push` workflows to commit back to `master`, and up to now, those workflows have been running as whoever clicked the merge button. This change has them run as `pulumi-bot` instead, which should allow us to restore those branch protections to the usual set (approvals required for non-admins, etc.).

Use pulumi-bot for auto-commits

---

themes/default/layouts/page/pricing.html

Add properties to the two links inside the pricing page "get started" dialog so that we can have insight into usage of this dialog to navigate to the different pages.

Add track properties for pricing dialog

---

themes/default/layouts/shortcodes/get-started-stepper.html

We've been seeing warning-level error this in the logs for a bit:
```
ERROR 2022/03/15 15:04:17 Page.Dir is deprecated and will be removed in Hugo 0.93.0. Use .File.Dir
```
Now that the current version of Hugo is `0.94` (which definitely does break on this), we should fix this up, as users who run locally will hit start hitting it once they install or upgrade to latest. (h/t @meagancojocar)

Change Page.Dir references to Page.File.Dir

---

themes/default/layouts/_default/baseof.html
themes/default/layouts/partials/head.html

Just as the title states this PR adds the Zoominfo Websights snippet.
Fixes: https://github.com/pulumi/marketing/issues/112
Zoominfo Installation guide: https://university.zoominfo.com/learn/article/implementation-guide-zoominfo-websights

Add zoominfo websights snippet

---

themes/default/layouts/partials/head.html

Add a meta tag in the head for Registry overview pages that re-uses the meta description as the content for the purposes of search results.  This should still accomplish https://github.com/pulumi/registry/issues/558, and we can always add a new frontmatter property if we find there are additional search terms we want to direct to the overview that are missing.  
The change this PR makes is that now, on registry package overview pages (and no other pages), there should be a meta tag in the head of the doc that looks something like this example:
```<meta class="swiftype" name="package-overview-description" data-type="text" content="Learn how you can use Pulumi's AWS Classic Provider to reduce the complexity of provisioning and managing resources on AWS.">```
This should have 0 effects …

Add swiftype meta tag for registry package overview pages

---

themes/default/layouts/partials/docs/feedback.html

noticed this today, _answerable_ reads as kinda rude, and im not sure how a user is supposed to know ahead of time if their question is _answerable_, so rephrased.

remove answerable from feedback msg

---

themes/default/content/docs/reference/service-rest-api/_index.md

Make it clear that audit logs that are OLDER than startTime are returned.

Update description of startTime for audit logs API

---

themes/default/content/resources/_index.md
themes/default/layouts/resources/list.html

The Resources page's tab filters have an item labeled "Whitepaper" that should be "Whitepapers". (Yes, there's only one, but there will be more!)
Requires https://github.com/pulumi/theme/pull/88 which I'll merge simultaneously.

Whitepaper -> Whitepapers

---

themes/default/content/resources/pulumi-up/index.md
themes/default/layouts/partials/content-tile.html

Updates the date and summary copy of the Pulumi Up event resource. Also makes a slight tweak to the hover behavior to underline only the title (instead all of the text on the card).
Fixes https://github.com/pulumi/marketing/issues/122.

Fix the PulumiUP date

---

BLOGGING.md

The setup instructions are currently linking to a different repo, to an index that no longer exists: https://github.com/pulumi/docs#pulumi-documentation-site
It should probably link to the instructions contained in this repo instead.

Send reader to pulumi-hugo not pulumi-docs

---

README.md
themes/default/config.yml

We need a minimum of Hugo v0.89.0 to support new twitter shortcodes, and it should say so in the README and config. Release notes: See also: https://github.com/gohugoio/hugo/releases/tag/v0.89.0

Correct Hugo Version

---

themes/default/content/docs/guides/self-hosted/components/_index.md

originally reported in [internal slack](https://pulumi.slack.com/archives/C85BS3LJZ/p1647816830868659)

add redirect for the old self hosted console page

---

themes/default/layouts/blog/single.html

These needn't be linked, so this change just unlinks them.

Unlink the blog post title on the blog post page

---

themes/default/content/docs/reference/service-rest-api/_index.md

Happened to notice the copy-button functionality in this doc doesn't quite work because `$PULUMI_ACCESS_TOKEN` is contained in single quotes, preventing it from being expanded by the shell:
```
$  curl \
-H 'Accept: application/vnd.pulumi+8' \
-H 'Content-Type: application/json' \
-H 'Authorization: token $PULUMI_ACCESS_TOKEN' \
--request POST \
--data '{"description":"{description}"}' \
https://api.pulumi.com/api/user/tokens
{"code":401,"message":"Unauthorized: No credentials provided or are invalid."}
$  echo $PULUMI_ACCESS_TOKEN
[yep, that's my token all right]
$  curl \
-H 'Accept: application/vnd.pulumi+8' \
-H 'Content-Type: application/json' \
-H "Authorization: token $PULUMI_ACCESS_TOKEN" \
--request POST \
--data '{"description":"{description}"}' \ …
```

Use double-quotes in curl examples

---

themes/default/content/blog/introducing-crd2pulumi/index.md
themes/default/content/docs/get-started/_index.md
themes/default/content/migrate/arm2pulumi.md
themes/default/content/migrate/cf2pulumi.md
themes/default/content/migrate/kube2pulumi.md
themes/default/content/migrate/tf2pulumi.md
themes/default/layouts/partials/docs/toc.html

this is changing our converter labels to their full names which should better help folks find what they are looking for
this also updates the heading on the get started section to be more clear, ive aligned on get started instead of getting started but can switch to getting started if folks feel strongly
there was a previous convo around also updating the get started guide labels, but we decided against that for now
related [internal slack convo](https://pulumi.slack.com/archives/C85BS3LJZ/p1647957689762799)

improving docs left-nav labels

---

themes/default/content/registry/packages/aws/how-to-guides/s3-website.md

The AWS Classic How-To Guide "Host a Static Website on Amazon S3" says that "The Resources tab in the Pulumi Service has a link to the AWS console for the provisioned EC2 instance.", but there are no EC2 instances created in the guide. This change replaces "EC2 instance" with "S3 Bucket."
https://www.pulumi.com/registry/packages/aws/how-to-guides/s3-website/

How-To Guide: Fix Update Check Instruction

---

themes/default/content/docs/guides/continuous-delivery/github-actions.md

Naively upgrades every `python-version` in the Github Actions Continuous Delivery Guide (Python) from `3.6` to `3.9`. I've only tested it with the `push.yaml` action, so it might be better to do a smaller upgrade or limit the scope of the upgrades.
Issue for dropping Python 3.6 support: https://github.com/pulumi/pulumi/issues/8131 "When we do this, we should make sure to update the language docs to reflect the new reality."

Docs: Github Action Fail Due to Python Version

---

themes/default/layouts/community/developer-advocates/single.html

Mainly for mobile, to reduce the profile image size and prevent wrapping of the "see all" link.

Minor visual adjustments to the DA single template

---

themes/default/content/docs/get-started/install/_index.md

After [Pulumi #4676](https://github.com/pulumi/pulumi/issues/4676) was resolved, it is now possible to install Pulumi using `winget` on Windows but also using a standalone Windows x64 installer. This PR extends the installation section to include these options. 
Also makes the distinction for manual installation where "manual" means downloading binaries to distinguish from downloading the standalone installer

Add installation sections on Windows for winget and standalone

---

scripts/serve.sh

Tiny little DX improvement to give you a clickable link when running `make serve` (h/t @mattstratton for the suggestion).

Add a BASEURL to get a link in the console when running locally

---

themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md
themes/default/layouts/partials/banner.html

Fixes: https://github.com/pulumi/marketing/issues/227
This PR updates the site banner for PulumiUP and removes a watch now button for a partner workshop.

Update site banner for PulumiUP

---

themes/default/layouts/shortcodes/console-note.html

Since this image corresponds with the content that's inside the note, it's odd that it's both outside the note and shown before it. Putting it inside the note, and after the content it refers to, makes more sense. (Otherwise, it's unclear until you read the note why this image is even here.)

Put the console image inside the console note

---

themes/default/content/blog/lambda-urls-launch/index.md

Added examples in other languages, including a resource to run the AWS CLI and add the correct permission to allow the URL to be accessed (this is missing in the CC API and the TF provider at the time of writing hadn't updated the lambda permissions resource to handle this)

Updated Lambda Function URL blog post

---

themes/default/content/docs/intro/concepts/inputs-outputs.md

The string interpolation syntax for the C# example was using back-tick string interpolation syntax instead of `$"{}"` interpolation syntax.

Fix string interpolation syntax in C# example for Output.All

---

themes/default/content/blog/full-access-to-helm-features-through-new-helm-release-resource-for-kubernetes/index.md

I believe (based on [this SO question](https://stackoverflow.com/questions/71802926/explanation-of-service-get-from-pulumi/71850966#71850966)) these should be `-master`, not `-redis-master`.

Fix a bug (I think) in a Kubernetes blog-post example

---

themes/default/layouts/page/why-pulumi.html

this was going to the aws begin page, instead of the get started landing page; this fixes it
change to `/why-pulumi/`
[internal slack convo](https://pulumi.slack.com/archives/C7XHM1GNT/p1650640951116219)

fix get started button link on why pulumi 

---

themes/default/content/docs/intro/languages/go.md

Happened to notice this; we probably mean Go here.

Change Python reference to Go

---

themes/default/content/docs/get-started/kubernetes/_index.md
themes/default/layouts/shortcodes/cloud-intro.html

a thing ive learned from @SaraDPH recently is that we should be thoughtful about linking people away from the content at the beginning. i was also talking with Luke about these pages today, and he mentioned that these links arent taking folks to a super useful place. so this is proposing removing them.
im open to hearing alternative thoughts and concerns!

remove links from get started landing pages

---

themes/default/content/pulumi-up/_index.md

Just as the title states, this PR updates the PulumiUP start time to be 8am PDT instead of 9am PDT.

Update PulumiUP start time

---

README.md
STYLE-GUIDE.md

i noticed that we had style content in the readme, and we were not linking to the style guide
this moves content from the readme to the style guide and links to the style guide in the readme

fix up style content in readme

---

themes/default/content/docs/guides/scim/okta.md

Update Okta SCIM public docs to direct user to disable username push updates from Okta.
https://github.com/pulumi/pulumi-service/issues/8237

Disable username updates in OKTA SCIM set up

---

themes/default/content/docs/intro/pulumi-service/organization-access-tokens.md

- fixes a numbering issue
- removed references to growth which we don't use in any user-facing docs, or on the marketing website
- cleaned up table, so headings are headings and not rows in the table

fixes to org tokens docs page

---

themes/default/content/docs/reference/pulumi-sdk.md

Follow-up from https://github.com/pulumi/pulumi-hugo/pull/1466#issuecomment-1118587132. The trailing slash is necessary in order for the redirect rule in https://github.com/pulumi/docs/pull/7476 to be applied properly:

Add trailing slash to the Javadocs link

---

README.md

Adds timing details and instructions for kicking off pulumi/docs PR jobs manually.

Add some details to the Merging and Releasing section of the README

---

BLOGGING.md

Removes the bit about future dates and adds a link to the publishing process note in the README.

Update the blogging README

---

go.mod
go.sum

Hugo merge build is currently failing on some go mod/sum errors: https://github.com/pulumi/pulumi-hugo/runs/6493942813?check_suite_focus=true.  Last time we saw this, a manual update to use the `release` branch of theme fixed things up, so that's what this PR does.

Fix go mod and go sum

---

themes/default/content/blog/testing-in-practice/index.md

this was reported in the new website-notifications slack channel
this is changing `blog/testing-in-practice/`

fix link thats 404ing

---

themes/default/layouts/blog/single.html

This PR adds a CTA to the bottom of the blog posts that asks people to subscribe to the newsletter.
Fixes: https://github.com/pulumi/pulumi-hugo/pull/1535

Add newsletter cta to bottom of blog posts

---

themes/default/content/docs/intro/concepts/state.md

Oh, I've been wanting to do this for almost a year!
Depends on the unreleased version of the cli.
After that's released with the updated go-cloud library, it'll become a breeze to work on multiple projects on AWS without thinking about env vars.
Even though we have a workaround of using direnv to set the `AWS_PROFILE`, this new approach is much cleaner and consistent across multiple people.
This PR is a sibling of #1499, which covers the encryption part.

Add information about "profile" param in state backend

---

themes/default/content/docs/get-started/kubernetes/review-project.md

this came up in two usability studies
as being misaligned from the template: https://github.com/pulumi/templates/blob/master/kubernetes-python/__main__.py
[internal slack convo](https://pulumi.slack.com/archives/C9SGX9QA1/p1653333169391999)

fix kube+python get started

---

themes/default/layouts/partials/right-nav-ad.html

This PR hides the right-hand CTA as we've gotten feedback it is too prominent still. The plan is to create a new image and then re-enable the CTA with the new image.

Hide right hand cta

---

themes/default/content/docs/guides/self-hosted/components/api.md

ServiceFunctionMode determines the mode in which the service runs based
upon the env variable "PULUMI_API_CONTAINER_MODE". If this value is not defined,
then it defaults to "FULL". If the value does not match a known type, it defaults
to "FULL".
Usage:
ServiceModeFull: Runs both the Pulumi API & Background Jobs
ServiceModeAPI: Runs only the Pulumi API
ServiceModeBackgroundJobs: Runs only background jobs
Signed-off-by: Steve Sloka <steve@pulumi.com>

self-hosted: Document FunctionMode env vars

---

themes/default/content/docs/intro/concepts/resources/_index.md

I looked for similar mislinks to this anchor in the vicinity, on the basis that it was caused by a file move or other rearrangement. I think this is the only one though.

Fix relative link to auto-naming in intro

---

themes/default/content/docs/intro/concepts/resources/options/ignorechanges.md

I was trying to use https://www.pulumi.com/docs/intro/concepts/resources/options/ignorechanges/ during a repro using Python for the first time and did not see the very important Note because it was placed on the bottom of the doc.
This PR makes the note appear only for the relevant languages (Go, C#, and Python) where casing for nested resources differs from the Pulumi schema.

Ensure camelCase warning is above nested property excamples for IgnoreChanges

---

themes/default/content/enterprise/_index.md

fixes: https://github.com/pulumi/marketing/issues/343
fixes the broken link to the sans institute case study on the `/enterprise` page.

fix broken sans institute link

---

themes/default/content/docs/guides/self-hosted/components/api.md
themes/default/content/docs/guides/self-hosted/components/console.md

Add the GitLab OAuth environment variable configuration to the self-hosted documentation for the Pulumi Service API. As part of the latest changes to GitLab, we need to make GitLab API calls from our own API in order to authenticate users.
Fixes https://github.com/pulumi/pulumi-service/issues/8797

Add GitLab OAuth vars to api.md for Pulumi Service self-hosted documentation

---

themes/default/content/docs/guides/testing/unit.md

Copied the C# helper method from the c# unit test directory: https://github.com/pulumi/examples/blob/74db62a03d013c2854d2cf933c074ea0a3bbf69d/testing-unit-cs/Testing.cs
This should fix #1566

Copy helper unit test method for C# in tutorial

---

themes/default/content/docs/guides/self-hosted/components/api.md

Looks like there was a linting error in an older commit. It's throwing errors on previews in newer PRs.

fix(lint): patch a lint error in an older commit

---

themes/default/content/blog/pulumi-release-notes-m64/index.md

Addresses: https://pulumi.slack.com/archives/C03G209S6H4/p1654269687768099
Fixes the 3.16.1 release link in this [blog post](https://www.pulumi.com/blog/pulumi-release-notes-m64/)
The link was linking to a release that either got deleted or never existed. There is no 3.16.1 of `pulumi/pulumi`. I did however find a 3.16.0. So I linked to that since at least the minor version is the same. It also looks like the dates align between 3.16.0 and 3.17.0 (i.e. 13 day time span which closely matches the 2 week milestone cadence we were using at that time). So I'm guessing this may have been what was intended based on the context of the sentence in the blog post.

Fix up link in release blog post

---

themes/default/content/docs/support/troubleshooting.md

- mention the --logflow flag and use it in examples, since you will
surely want it to accompany -v
- say where the logs go when you _don't_ supply --logtostderr
- simplify the language a little

Give more troubleshooting advice regarding logs

---

themes/default/layouts/page/cloud-engineering-summit.html
themes/default/layouts/partials/header.html

This PR updates the CES page to have a save the date and updates some of the copy to make it clear the content is from 2021. I am holding on doing more to the page until we have a decision on the platform because potentially this page would be hosted in the platform itself.
Part of: https://github.com/pulumi/marketing/issues/339

Add save the date for Cloud Engineering Summit 2022

---

themes/default/content/docs/guides/self-hosted/components/api.md

fixes https://github.com/pulumi/pulumi-service/issues/8713
fixes https://github.com/pulumi/pulumi-service/issues/8416
Adding documentation for recent performance optimizations. Intentionally omitting kinesis environment variables as these are currently designed for internal usage only (it would require publishing the code and infrastructure requirements for kinesis -> lambda -> dynamo).

Document engine events and audit logs env vars for the pulumi service API

---

scripts/lint.sh
themes/default/content/blog/multicloud-with-kubernetes-and-pulumi/index.md
themes/default/content/docs/guides/self-hosted/components/api.md

When the Prettier check was added to `lint.sh`, we forgot to add a line to tell the script to fail and exit on any error, which has allowed a few Markdown-related changes to sneak by that _should've_ failed, but didn't, because the Prettier check that runs _after_ `markdownlint` passed. (In other words, as of now, only a Prettier failure will cause `lint.sh` to exit nonzero, which means we're essentially no longer linting Markdown.)
This change adds a line to handle this as we do elsewhere and fixes up the Markdown things that've gotten through.

Actually fail when the Markdown linter fails

---

themes/default/content/docs/intro/concepts/secrets.md

The "awssdk=v2" property is required according to the original PR and confirmed by a user in an issue:
- https://github.com/pulumi/pulumi/pull/9590
- https://github.com/pulumi/pulumi/issues/9846
Fixes pulumi/pulumi#9846.

Fix AWS KMS secret provider docs for setting profile

---

themes/default/content/resources/getting-started-with-infrastructure-as-code-on-oracle-cloud/index.md

Addresses: https://github.com/pulumi/marketing/issues/280
Update workshop to link to oracle registration page, since they will be hosting the event.

update oracle workshop with external link

---

config/_default/menus.yml
themes/default/content/docs/guides/pulumi-packages/how-to-author.md
themes/default/content/docs/intro/languages/_index.md
themes/default/content/docs/intro/languages/dotnet.md
themes/default/content/docs/reference/pulumi-sdk.md
themes/default/content/partner/azure.md
themes/default/layouts/partials/carousel.html
themes/default/layouts/partials/supported-languages.html
themes/default/layouts/shortcodes/install-dotnet.html

The technology is now called ".NET" and the latest version is ".NET 6", which is the only current LTS (long-term support) version. It's the default version that users will get if they follow our links to download pages. We are also about to change our templates and examples to .NET 6, which. also brings nice simplifications into programs.
I searched for all mentions of ".NET Core" and updated everything except blog posts, case studies, and old workshop guide.

Change .NET Core to .NET is our docs prose

---

themes/default/content/blog/stack-readme/index.md

Two changes in this PR:
1. Stringifies file in typescript example
2. Adds YAML example.
YAML Screenshot:

Update stack readme example

---

themes/default/content/resources/getting-started-with-infrastructure-as-code-on-aws-7-19-22/index.md
themes/default/content/resources/getting-started-with-infrastructure-as-code-on-aws-9-8-22/index.md

Issue: https://github.com/pulumi/marketing/issues/359, https://github.com/pulumi/marketing/issues/360
Adding workshops for the Getting Started with AWS on  7/19/22 and 9/8/22. The text for the description on the resources page is way too long and ends up overflowing the workshop card. I notice it was 2 paragraphs, I shortened it to only include the first one and it is still too long. Let me know what changes can be made here. Could we shorten "infrastructure as code" to just b abbreviated as "IaC"? That may do the trick.

Add Getting Started w/ AWS IAC workshop

---

themes/default/content/migrate/_index.md
themes/default/content/migrate/arm2pulumi.md
themes/default/content/migrate/cf2pulumi.md
themes/default/content/migrate/kube2pulumi.md
themes/default/content/migrate/tf2pulumi.md
themes/default/layouts/migrate/section.html

Just adds some reasonable content to the page to guide those who land here to the right place. (The page [currently empty](https://pulumi.com/migrate).)
Fixes #672.

Add content to /migrate

---

themes/default/content/docs/intro/concepts/resources/options/additionalsecretoutputs.md
themes/default/content/docs/intro/concepts/resources/options/customtimeouts.md
themes/default/content/docs/intro/concepts/resources/options/ignorechanges.md
themes/default/content/docs/intro/concepts/resources/options/replaceonchanges.md
themes/default/content/docs/intro/concepts/resources/options/retainOnDelete.md

This PR documents the warnings generated as part of https://github.com/pulumi/pulumi/pull/9921
It closes https://github.com/pulumi/pulumi-hugo/issues/1620
(Some) resource options are ignored when applied
to component resources. This commit adds a warning
to the docs explaining this behavior.

Add warning to resource options docs

---

themes/default/content/docs/reference/cli/environment-variables.md

The example for `PULUMI_CONFIG` environment variable uses `PULUMI_HOME` in the example.

Name of environment variable was wrong in the example

---

themes/default/content/blog/how-webiny-built-a-serverless-application-framework/index.md

All of the Webiny GH links were pointing to our `next` branch. Because it changes all the time, this is not a good idea.
So, all of the links are now pointing to our `v5.28.0` branch. That way we're sure none of the links end up being broken over time.
Closes [W1658](https://github.com/pulumi/pulumi-hugo/issues/1658) https://github.com/webiny/webiny-js/issues/2503

Webiny Blog - Update Outdated GH Links

---

themes/default/content/devops-days-2022/_index.md
themes/default/layouts/page/devops-days-2022.html

Issue: https://github.com/pulumi/marketing/issues/369
This PR adds the devops days landing page. Is there a registration link available for the Los Angeles event? I can't seem to find it on their site. Also, will there be any companion workshops to link to, or if not should we put something else in its place?

add devops days landing page

---

themes/default/content/docs/reference/yaml/_index.md

This applies the change made since I moved the spec over (see https://github.com/pulumi/pulumi-yaml/commits/main/README.md). Until https://github.com/pulumi/pulumi-yaml/pull/261 is merged, the two docs must be kept synced by hand (or by automation that I have not developed :-).

Bring YAML spec up to date with Fn::ToJSON

---

themes/default/content/docs/reference/pulumi-sdk.md
themes/default/content/docs/reference/yaml/_index.md

- Retarget the link from the SDK page to the YAML spec, which is here as of https://github.com/pulumi/pulumi-hugo/pull/1665; and,
- Remove the implicit menu item, so https://github.com/pulumi/docs/pull/7764 doesn't result in an item in two different places in the navigation.

Retarget YAML SDK link

---

themes/default/content/resources/introduction-to-infrastructure-as-code-with-yaml/index.md

Update the meta description for the `/resources/introduction-to-infrastructure-as-code-with-yaml/` page. @SaraDPH asked to update the meta description for the  introduction to infrastructure as code with yaml workshop.

Update meta_desc for iac with yaml video

---

themes/default/content/blog/shared-config-with-aws-systems-manager-parameter-store/index.md
themes/default/content/docs/intro/concepts/stack.md
themes/default/content/docs/reference/yaml/_index.md

Stack references will now be a resource that can be declared, rather than accessed via a function

Remove Fn::StackReference doc

---

themes/default/content/blog/applying-attribute-based-access-controls-to-aws-lambda-functions/index.md

Looks like they ended up going with a different URL.

Update an AWS blog post link

---

.github/workflows/pull-request.yml

We do these builds to help guard against broken links introduced in this repo's PRs, but with the OOM errors lately, it isn't completing reliably, which forces submitters to have to re-run their PR jobs until it passes. So I suggest we comment it out temporarily, and re-enable once the OOM errors are figured out.

Temporarily disable full-site builds

---

.husky/pre-commit
package.json
yarn.lock

In the last frontend working group meeting, we discussed the challenge of mis-formatted code causing confusing errors for folks when their branches were pushed.  We decided that we'd try a pre-commit hook that automatically formats code with Prettier, and see if that resolved some of the difficulties.

Add pre-commit hook that formats code

---

themes/default/content/docs/get-started/aws/deploy-stack.md
themes/default/content/docs/get-started/azure/deploy-stack.md
themes/default/content/docs/get-started/gcp/deploy-stack.md

this came up in a recent study, and someone opened up an issue https://github.com/pulumi/pulumi-hugo/issues/1759
its not clear that this command can vary between languages because this was missing
this adds the chooser to reduce confusion
fixes  https://github.com/pulumi/pulumi-hugo/issues/1759

add missing chooser to aws, azure, gcp deploy stack step

---

themes/default/content/docs/guides/pulumi-packages/schema.md

Fixes pulumi/pulumi-java#646
Source of truth is documented more in the doc strings for https://github.com/pulumi/pulumi-java/blob/main/pkg/codegen/java/package_info.go#L35 
I considered including a link here (possibly via sourcegraph) but decided against it.

Document Java codegen options

---

themes/default/content/docs/intro/pulumi-service/organization-access-tokens.md
themes/default/content/docs/intro/pulumi-service/team-access-tokens.md

Added a new document for Team Access Tokens, linked to it in the Pulumi Service documentation nav.

Add Team Tokens documentation

---

themes/default/content/docs/reference/yaml/_index.md

This PR contains an update for the YAML reference documentation about how to create explicit provider instances and how to use version pinning while creating resources.

feat: YAML provider version pinning 

---

themes/default/content/blog/shared-config-with-aws-systems-manager-parameter-store/index.md
themes/default/content/docs/intro/concepts/stack.md
themes/default/content/docs/reference/yaml/_index.md

Seeking to temporarily revert this, as we released docs before YAML support for this change.
Reverts pulumi/pulumi-hugo#1746

Revert "Remove Fn::StackReference doc"

---

.prettierignore

Prettier was taking ~7 minutes on this file during commits
```
yarn run v1.22.19
$ /Users/sarah/workspace/pulumi-hugo/node_modules/.bin/prettier --write .
.devcontainer/devcontainer.json 25ms
.github/workflows/pull-request-closed.yml 18ms
.github/workflows/pull-request.yml 5ms
.github/workflows/push.yml 4ms
.github/workflows/scheduled-cleanup.yml 3ms
.github/workflows/scheduled-upstream-sync.yaml 3ms
.prettierrc.json 3ms
assets/css/bundle.css 431030ms
assets/css/marketing.css 49ms
assets/js/bundle.js 1238ms
assets/js/marketing.js 1ms
```
^ an excerpt

add generated css bundle file to .prettierignore

---

themes/default/content/docs/support/troubleshooting.md
themes/default/layouts/shortcodes/pulumi-host.html
themes/default/layouts/shortcodes/pulumi-language.html

While working through some onboarding tasks, I ran into this bug:
While selecting Java or YAML, the language names and language hosts would revert to `TypeScript` and would not recover without a refresh.  This PR adds those languages and corresponding runtimes.

fix: Adds Java and YAML language-specific shortcodes

---

.husky/pre-commit

Recently we added a pre-commit hook that runs `prettier` and in a recent blog post PR, I hit a lint error which failed my first build. This PR adds the lint script to the pre-commit hook so that folks will see the lint error before they push up to CI, hopefully saving folks time.

Add lint script to pre-commit hook

---

themes/default/content/blog/unlocking-your-data-with-metabase-and-aws/index.md

This PR fixes a typo in the Metabase blog.

Fix typo in metabase blog

---

themes/default/layouts/index.html

Part of https://github.com/pulumi/theme/pull/161
This PR adds a class that will correctly style the button when we disable the `important` flag in the Tailwind config.

Add class for download button styling

---

themes/default/content/docs/intro/languages/python.md

This PR clarifies some unclear language around the minimum supported Python version.
As it was written, I can't imagine how we would support Python 3.x < 3.6.

Clarify Copy on Supported Py Version

---

themes/default/content/blog/shared-config-with-aws-systems-manager-parameter-store/index.md
themes/default/content/docs/intro/concepts/stack.md
themes/default/content/docs/reference/yaml/_index.md

With 3.38.0, StackReference resources are supported in Pulumi YAML and we are deprecating `Fn::StackReference`. At least until Pulumi YAML GA, the latter will continue to work.

Remove Fn::StackReference doc (#1746)

---

themes/default/layouts/shortcodes/configure-gcp.html

We don't, at least in pulumi-gcp, use gcloud config, so we need to ask people to set Project the Pulumi way.

Explicitly set GCP Project via `pulumi config`

---

.github/workflows/pull-request.yml

Ubuntu 18 had a scheduled brownout that caused the workflow not to run. I've never experienced this with other workflows (all of which use `ubuntu-latest`). If we're intentionally using a pinned version of Ubuntu, please refuse this PR, let me know why, and I'll submit another PR to comment as to why we're using v18 and under what conditions we can upgrade.

Change pull-request.yaml to run on ubuntu-latest

---

themes/default/content/docs/intro/concepts/logging.md

context in java has a method log() not as public field

log is a method in context

---

themes/default/content/docs/intro/concepts/resources/_index.md
themes/default/content/docs/intro/concepts/resources/functions.md

This turns the explanation of getter functions into a general explanation of provider functions, with a special case of getter functions.
I found it difficult to uncover the purpose of some of the InvokeOptions fields, and I suspect `version` and `pluginDownloadURL` in particular are more for plumbing than for end users, so I have been a little circumspect in places. Advice on improving those and any other bits is welcome!
Fixes #1628.

General functions documentation

---

themes/default/content/blog/configuring-your-dev-environment/index.md
themes/default/content/blog/pulumi-release-notes-m58/index.md
themes/default/layouts/shortcodes/install-python.html

As per https://github.com/pulumi/pulumi-hugo/pull/1860 3.6 isn't supported anymore. Update docs to tell users to use 3.7.

Update some references of Python 3.6 to 3.7

---

themes/default/content/docs/get-started/install/_index.md

The formatting on this page seems to be jacked up in several places, presumably because of the intermingling of markup and Markdown (which needs whitespace to distinguish them):
This should fix things up.
Fixes #1851.

Fix formatting on the Download page

---

themes/default/content/docs/reference/service-rest-api/_index.md

Add documentation for our RUM APIs to https://pulumi.com/docs/reference/service-rest-api/#resources-under-management-rum.
Specifically looking for feedback on how I formatted these different responses. I added an example for each `granularity` since the response shape is slightly different depending on which granularity you choose. For example, `granularity=weekly` adds a `"weekNumber"` key to the response object. There might be a better way to represent this, very open to other ideas! 
Related To: https://github.com/pulumi/service-requests/issues/87

Add resources under management APIs to REST docs

---

themes/default/content/docs/reference/pulumi-yaml.md

Looking at adding a JSON schema file for this project format as well, see https://github.com/pulumi/pulumi/blob/2db79a54cfc01edbfea51f28324bf96e437cf630/sdk/go/common/workspace/project.json.
Maybe we could start auto-gening this page at some point from that schema?

Update the documenation for what backend is

---

themes/default/content/blog/pulumi-release-notes-77/index.md

Not sure why Hugo doesn't like `relref`s that point to taxonomy pages, but it clearly doesn't. Will look into it, but in the meantime, this should fix.

Fix broken relref

---

themes/default/content/docs/intro/pulumi-service/audit-logs.md
themes/default/content/docs/intro/pulumi-service/billing-managers.md
themes/default/content/docs/intro/pulumi-service/ci-cd-integration-assistant.md
themes/default/content/docs/intro/pulumi-service/organization-access-tokens.md
themes/default/content/docs/intro/pulumi-service/projects-and-stacks.md
themes/default/content/docs/intro/pulumi-service/pulumi-button.md
themes/default/content/docs/intro/pulumi-service/team-access-tokens.md
themes/default/content/docs/intro/pulumi-service/teams.md
themes/default/content/docs/intro/pulumi-service/webhooks.md

we are starting to collect some ux debt on the service docs, this attempts to organize things in a logical order that our users may be able to better understand.
i started this convo in [internal slack](https://pulumi.slack.com/archives/C8A7QG1CZ/p1661217840351789)
i will mention that i have usability concerns that we have token information spread out across 3 separate docs pages, and that we have role information spread out across 3 separate docs pages as well. this requires folks to read all these pages to understand how these things work together. for now, though im trying to do the smallest change to reduce some usability issues.
super open to feedback on the order!!

fix pulumi service docs nav order

---

themes/default/content/docs/reference/pulumi-yaml.md

fixes #1906 
the config option for templates only asks for that config when this template is used as part of `pulumi new`. it does not auto-apply this config for all stacks within a project.
I've tried a pass at more clear words, also open to removing this from the docs. not sure whats best.
this came from a issue report over in pulumi/pulumi: https://github.com/pulumi/pulumi/issues/10581

fix misleading template config mention

---

themes/default/layouts/index.html

Just as the title says, this PR updates the text on the secondary CTA in the home page hero from "Download CLI" to "Download Open Source".

Update secondary button on the home page hero

---

themes/default/content/docs/intro/concepts/resources/options/dependson.md

When I use the syntax currently quoted in the docs, I get an error:
```
error: Error registering resource [record]: Pulumi.yaml:119,18-32: resource option dependsOn value must be a list of resources;
```
This seems to be what's needed.

Fix a syntax issue in the resource options docs

---

themes/default/content/docs/reference/pulumi-yaml.md

https://github.com/pulumi/pulumi/pull/8655 added support for a `nodeargs` runtime option for Node.js projects, but we never explicitly documented it. This PR does that.

Document the `nodeargs` runtime option in Pulumi.yaml

---

themes/default/content/challenge/startup-in-a-box.md

noticed that we ask folks to name this file `styles.css` but then in later content (including the html file) we use `style.css` so if folks copy directly the css wont actually work.
if anyone prefers that i keep this line as styles and change the other 2 lines to styles, happy to do so, let me know

fix css filename in startup challenge

---

themes/default/layouts/partials/header.html

Adds a link to the Templates section in the Learn menu of the main nav. A few notes:
- I chose the `project-diagram` icon because it was the closest thing I could find to an architecture diagram, but open to alternative suggestions if anyone has one!
- For the subhead, the most important words are probably "deploy" (also to align with verbs in other subheads) and "common architectures", but open to suggestions on this as well.
- I chose this placement because I want to make sure Learn has more prominence, and to me, that right side (Blog, etc.) still seems more prominent than the left -- but again, open to discussion!

Add Templates to the Learn menu

---

themes/default/layouts/partials/header.html
themes/default/static/icons/ruler-triangle.svg

Uses a drafting triangle for the Templates icon instead. Follow-up from #1939, [convo](https://pulumi.slack.com/archives/C01E2KK808G/p1663178101821909) for context.

Change the Templates icon

---

themes/default/content/docs/reference/cli/environment-variables.md

This envvar has been removed since Pulumi 3.38.0. https://github.com/pulumi/pulumi/issues/3045

Remove deprecated `PULUMI_TEST_MODE` envvar docs

---

.github/workflows/pull-request.yml
.husky/pre-commit
package.json
yarn.lock

The pre-commit scripts we run today (`lint-markdown`, `prettier --check`, and `prettier --write`) all run on every commit, regardless of the types of files that are about to be committed. This change aims to tighten up this workflow a bit by replacing  the `make lint` and `make format` in the pre-commit hook today with [`lint-staged`](https://github.com/okonet/lint-staged), which is configured to:
* run `lint-markdown` only when one or more content files have changed
* run `prettier --write` only when one or more layout files or YAML files have changed
* stop running `prettier --check` in the pre-commit hook, which should make sense given that (a) the intent is to format these files anyway and (b) as currently written, by the time `prettier --check` does run, the code's already been …

Use lint-staged to lint and format changed files only

---

themes/default/content/templates/static-website/aws/index.md
themes/default/content/templates/static-website/azure/index.md
themes/default/content/templates/static-website/gcp/index.md

Adds Static Website pages for Azure and GCP. As discussed, this initial version leaves out Next Steps sections; our plan is to circle back and add these sections later, once we've finished the first round of template pages.

Add Azure, GCP static-website template pages

---

themes/default/layouts/templates/overview.html
themes/default/layouts/templates/section.html

Little fix to make sure cards with wrapping content stay aligned horizontally.
Before:
After:

Use full height for cards

---

themes/default/content/templates/static-website/gcp/index.md

Looks like these references to Azure and AWS slipped through in the GCP template page. 😬

Fix errant cloud references

---

themes/default/content/templates/static-website/gcp/index.md

This prefix is used to build the source-code links in the right-hand nav. Should be “gcp”, not “google-cloud”.

Fix links for GCP template

---

themes/default/content/templates/static-website/_index.md

Looking closer at the content at the top of this page:
... I'd like to propose that we pull the links to AWS, Azure, etc., out of the header area and into the body of the page instead, for a couple of reasons:
* Right now this reads as though clicking "AWS" may lead me to more information about how to "deploy a static website on AWS", which isn't the case.
* In general, links that pull users away from the page should be limited to the lower 2/3 or so of the page. (We have a note about this [in our style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md#content-design) in fact, which I believe was originally suggested by @SaraDPH.)
I know these links are meant to encourage traffic to the pages they link to, so I don't  want to lose that -- I'd just prefer they weren’t …

Move links out of the header area

---

themes/default/layouts/index.html

The C# image was missing in the Build section of the home. This PR fixes the file name so it is there.

Fix typo in file name for build chooser

---

themes/default/content/docs/reference/pulumi-yaml.md

It's not a boolean, it's a string that should be set to `always` to turn on the functionality.
Related to https://github.com/pulumi/pulumi/issues/10824

Fix documentation for the Pulumi.yaml `refresh` option

---

themes/default/layouts/templates/overview.html
themes/default/layouts/templates/section.html

Makes padding consistent on the section and overview pages and adds a one-pixel border around cards for definition. (We do this also in Registry.)

Add some space above the headings on template overview cards

---

themes/default/content/docs/support/faq.md

The link to Transferring Stacks was broken, so this fixes that and makes a few tweaks to better comply with the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md#links).

Fix broken link, tweak a few words

---

themes/default/content/_index.md
themes/default/layouts/index.html

Fixes: https://github.com/pulumi/pulumi-hugo/issues/822
Part of https://github.com/pulumi/marketing/issues/416
This PR updates the home page slow machine component based on the new mockup. I also moved up the benefits section because it looked weird having the code example present twice so quickly.
Note: There is follow up PR in `theme` to randomize the order of slot items on each page load: https://github.com/pulumi/theme/pull/258

Update home page slot machine component

---

themes/default/content/docs/reference/pulumi-yaml.md

- Update pulumi-yaml.md to include the `buildTarget` option.
- Also updates the `binary` option for go to be up to date with internal details.
https://github.com/pulumi/pulumi/issues/10473

Update pulumi-yaml.md to include the `buildTarget` option.

---

themes/default/content/docs/intro/concepts/state.md

to use cli auth
Related to https://github.com/pulumi/pulumi/pull/10900
Related to https://github.com/google/go-cloud/pull/3159

Add storage_account parameter to Azure Blob Storage backend

---

themes/default/content/docs/reference/yaml/_index.md

To enforce consistency and reduce confusion in the YAML ecosystem, we decided to strongly suggest that YAML is written in camelCase. This PR adjusts our docs to reflect the new case system.

camelCase YAML reference docs

---

themes/default/content/docs/reference/yaml/_index.md

A previous PR (#1714) removed columns from the resource options table, but left a few rows with too many values, which crowded out the descriptions. This removes the extra values so the description column has all the descriptions.
Fixes #2034.

Remove vestigial column values in Resource Options table

---

themes/default/layouts/shortcodes/configure-gcp.html

Add a type parameter to the `configure-gcp.html` shortcode which has a default of `gcp`. This will accommodate the current (gcp) while also allowing reuse for google-native.

Add Type Parameter to `configure-gcp.html` Shortcode 

---

themes/default/archetypes/templates/template/index.md
themes/default/content/templates/container-service/_index.md
themes/default/content/templates/container-service/aws/index.md
themes/default/content/templates/kubernetes/aws/index.md
themes/default/content/templates/serverless-application/aws/index.md
themes/default/content/templates/serverless-application/azure/index.md
themes/default/content/templates/serverless-application/gcp/index.md
themes/default/content/templates/static-website/aws/index.md
themes/default/content/templates/static-website/azure/index.md
themes/default/content/templates/static-website/gcp/index.md
themes/default/layouts/partials/templates/right-nav.html
themes/default/layouts/shortcodes/templates/pulumi-new.html

This change adds a new shortcode, `{{< templates/pulumi-new >}}`, that reads from template frontmatter to build the language chooser and `pulumi new` commands. Also adjusts the right-hand nav to use that same list to build the links to the templates repository. 
cc @gthuang as this makes a few tweaks to the templates archetype, which now expects that list of languages, along with the name to use for the Pulumi project directory (with defaults included of course).

List languages in template frontmatter

---

themes/default/content/docs/intro/pulumi-service/webhooks.md

- fixed contact us link going to about us
- wording clean up

Webhooks doc fixes

---

themes/default/content/docs/get-started/_index.md

This PR adds the newly shipped templates as options in the Getting Started Guide. The main goal here is increase awareness and usage of the templates, and by offering them as options on the getting started page we should get more visibility.
**Hypothesis**
By presenting users more use case specific options in the getting started guide we will increase the CTR of users to these templates/guides and in turn increase the conversion rate of the website resulting in new users.

Add templates as options on getting started landing page

---

themes/default/content/challenge/one-quickstart.md

Noticed a few mentions of rough edges in the current challenge, so I wanted to run through it myself. The only major-ish thing I saw was that after we manually paste over the contents of `requirements.txt`, we fail to mention that `pip install` needs to be run again -- otherwise, the subsequent `pulumi preview` fails:
```
ModuleNotFoundError: No module named 'requests'
```
The rest are just tiny things: deleting the whitespace at the top of the page (where I think we'd planned to put an image), deleting some unused code, and adjusting the content in the final paragraph to remove the "first" (since it's actually the second).

Fix a couple of small issues with the quickstart challenge

---

themes/default/layouts/partials/footer.html

This PR adds the Slack Archive to the footer, which should be helpful when crawling the archive for SEO purposes.
Part of https://github.com/pulumi/pulumi-hugo/issues/2019

Add link to slack archive

---

themes/default/layouts/blog/list.html
themes/default/layouts/community/developer-advocates/single.html
themes/default/layouts/partials/blog/authors.html
themes/default/layouts/partials/blog/sidebar.html
themes/default/layouts/partials/blog/summary.html
themes/default/layouts/taxonomy/author.html
themes/default/layouts/taxonomy/tag.html
themes/default/layouts/what-is/list.html

Hugo's `.Permalink` builds fully-qualified URLs (using the configured URL), but in most cases, relative URLs are preferable because they're more portable). This PR replaces all occurrences but in the `<head>` tag, which we should keep for canonical URLs and social media images.

Use RelPermalink instead of Permalink

---

themes/default/content/docs/guides/crosswalk/aws/ecs.md

Fixes 
Line No: 211
From: const cluster = new awsx.ecs.Cluster("custom", { vpc });
To: const cluster = new aws.ecs.Cluster("custom", { vpc });

Fixes typo for cluster creation

---

themes/default/content/docs/intro/pulumi-service/organization-access-tokens.md

The Org Tokens docs were erroneously showing audit log events list/export features as possible. This is not possible at this time as org tokens are given only Member-level permissions, and these are Admin endpoints. As we receive feedback we [may opt to change this](https://github.com/pulumi/service-requests/issues/135).
Fixes https://github.com/pulumi/service-requests/issues/131

Corrected error in Organization Access Tokens docs that listed Audit Log Export/List as possible

---

themes/default/content/docs/guides/crosswalk/aws/vpc.md

Changed Line No: 739
From:     cidrBlocks: ["0.0.0.0"],
To:     cidrBlocks: ["0.0.0.0/0"],
Reason: To fix  "problem: "0.0.0.0" is not a valid CIDR block: invalid CIDR address: 0.0.0.0. Examine values at 'SecurityGroup.Ingresses'."

Updated CIDR block for Security Group

---

.husky/pre-commit
scripts/lint/check-file-size.sh

This PR adds a file size check to the pre-commit hook to warn users about committing large files since we are starting to get close to hitting a size limit with our hugo build. See https://github.com/pulumi/docs/issues/8220#issuecomment-1309325148
I set this to warn for files greater than 1MB, but open to other suggestions. I only added this to warn for newly committed files as a pre-commit hook since this would continue fail for existing large files. Users can also get around the hook by committing with `--no-verify` in the event they really need to add such a large file.

Add precommit hook for file size

---

themes/default/content/docs/reference/deployments-rest-api/_index.md

Adds some missing information from deployments api
Fixes: https://github.com/pulumi/service-requests/issues/130

[deployments] - Document missing information

---

themes/default/content/docs/guides/continuous-delivery/github-actions.md

okay i got totally hung up on this tonight; as pulumi was creating things in my individual account or trying to, when the stack really existed in an org. im not sure if this is the best way to make this clear. super open to other ideas and suggestions!
the downside is that this wont just automatically work for folks if they copy and paste this directly, they will need to change this value. 
we could try working it into the prose somehow.
edit: i realized that this may frustrate folks that are using their own backend since they don't have the org concept. i do still think its important to figure out how to include this info somewhere on this page.

clarify stack name in actions docs

---

BLOGGING.md

This is the result of running Gifsicle on all GIFs greater than 5MB, resizing them to 800px wide (the width at which they're rendered in the blog) and running Gifsicle's built-in optimizer. Wins back about 120MB worth of space.
For reference, the command was: 
```bash
find themes/default/content/**/*.gif -type f -size +5M | xargs gifsicle --resize-width=800 --optimize=3 --batch
```
Also adds a bit to the blogging README showing how to do this for individual files going forward.
Fixes https://github.com/pulumi/docs/issues/8220 ... I think?

Resize and optimize some GIFs

---

themes/default/layouts/page/pricing.html

its currently failing on
>ERROR 2022/11/17 01:44:26 [en] REF_NOT_FOUND: Ref " /docs/intro/pulumi-service/organization-access-tokens/" from page "pricing/_index.md": page not found

fix link failing pulumi/docs link check

---

themes/default/content/docs/intro/pulumi-service/_index.md

Align with changes to the Team Plan reducing the maximum seat count from 15 to 10

Update Team seat limit

---

themes/default/content/templates/serverless-application/aws/index.md

Noticed this page was missing the `template` layout setting (so losing the left and right nav, breadcrumb, styling, etc.):
This should fix it up.

Add layout for AWS serverless template

---

themes/default/content/docs/guides/self-hosted/components/_index.md

The current link points to the wrong page, and with the `alias` on this page, it redirects to itself rather than the components subpage.

Point `Web console` to correct page

---

themes/default/content/docs/intro/languages/javascript.md

See https://github.com/pulumi/pulumi/issues/11488

NodeJS warning

---

themes/default/content/docs/reference/deployments-rest-api/_index.md

These changes document support for exporting environment variables from pre-run commands via the PULUMI_ENV file.

[deploy] Document PULUMI_ENV

---

themes/default/content/docs/get-started/aws/modify-program.md

bucket.getId() was deprecated - bucket.id() is the new method.

Change from getId() to id() in Java

---

themes/default/content/learn/pulumi-fundamentals/configure-and-provision/index.md

Adds text to further explain purpose and use of configuration values. Fixes an incorrect path reference to the application source code repository. Clarifies that the configuration values are required.
Fixes #1840

Improve clarity of text per user feedback

---

themes/default/content/learn/pulumi-fundamentals/create-docker-images/index.md

This PR attempts to clarify that users are not expected to use the application code shared in the "Pulumi Fundamentals" Learn pathway; the Docker images have already been built for them.
Closes #1842.

[Learn] Clarify role of application code in Fundamentals pathway

---

themes/default/content/docs/intro/concepts/inputs-outputs.md

The code snippets of JS and TS under https://www.pulumi.com/docs/intro/concepts/inputs-outputs/#lifting appeared both at the same time on the page because they were missing the wrapping of `{{< chooser...`

Add missing "chooser" around a couple of JS and TS snippets

---

themes/default/content/docs/guides/self-hosted/components/api.md

The SMTP environment variables weren't documented in our self-hosted component documentation.

Documented the missing SMTP environment variables.

---

themes/default/content/blog/tag.md
themes/default/layouts/blog/tags.html
themes/default/layouts/partials/blog/sidebar.html
themes/default/layouts/partials/head.html

Adds a page that lists all blog tags alphabetically. This is helpful mainly for reference, as blog-post authors frequently want to know what tags we've already defined so they can use them.
Also fixes a bug with the sidebar logic. (It now works as intended -- not sure what happened there, but in any case, should be good now!)

Add a page listing all blog tags

---

themes/default/content/docs/get-started/aws/create-project.md

This comment isn't needed and interferes with copy-paste functionality.

aws/create-project: Delete GOPATH comment

---

themes/default/content/docs/guides/oidc/_index.md
themes/default/content/docs/guides/oidc/aws.md
themes/default/content/docs/guides/oidc/azure.md
themes/default/content/docs/guides/oidc/gcp.md
themes/default/content/docs/reference/deployments-rest-api/_index.md

These changes add a new set of guides that explain how to configure Pulumi Deployments' OpenID Connect integration with AWS, Azure, and GCP.
These changes also add documentation for OpenID Connect in the Pulumi Deployments API.

Add Pulumi Deployments OIDC docs.

---

themes/default/content/docs/get-started/azure/create-project.md
themes/default/content/docs/get-started/gcp/create-project.md

This is a follow up to #2372,
making the same change to the Azure and GCP guidance.
Go projects no longer need to use GOPATH.

get-started/{azure, gcp}: Don't mention GOPATH

---

themes/default/content/docs/get-started/aws/create-project.md
themes/default/content/docs/get-started/azure/create-project.md
themes/default/content/docs/get-started/gcp/create-project.md
themes/default/content/docs/get-started/kubernetes/create-project.md

In the Get Started documentation,
when we tell users to Create a New Project with `pulumi new`,
we include a handful of short paragraphs next to each other
with instructions.
This is not very skimmable:
- keywords like project name/description/stack name
are hidden in the text
- the actual instruction of what to do is also just hidden
in the text
For someone following along, it's better to have keywords
related to prompts they're seeing highlighted,
and to include a sample output they can follow along to.
This changes the create-project sections
of all four Get Started with Pulumi pages
in the following way:
- project name and description are bold
- change "name of a stack" to "a stack name", and bold "stack name"
- bold out any provider-specific configuration prompts
- add the output of …

get-started/*/create-project: Add prompt examples

---

themes/default/content/docs/intro/concepts/stack.md

Before:
[..] a Promise (effectively, the same as an Input. The actual [..]
Now:
[..] a Promise (effectively, the same as an Input). The actual [..]

intro/stacks: Missing closing paren

---

themes/default/content/docs/intro/pulumi-service/deployments.md
themes/default/content/docs/reference/deployments-rest-api/_index.md

This would be a lot less gnarly if the container had `nvm` pre-installed

[deployments] - Add example to user different node version

---

themes/default/content/learn/pulumi-fundamentals/configure-and-provision/index.md

This PR updates the Pulumi Fundamentals pathway with a correct environment variable that allows the frontend container to listen on a different port. The usage of an incorrect variable was discovered during work to add Go support to the Building with Pulumi pathway.
Fixes https://github.com/pulumi/devrel-team/issues/485

[Learn ]Update Pulumi Fundamentals with correct environment variable

---

themes/default/layouts/partials/head.html

Currently our taxonomy pages are taking away from the ranking of some of more core pages pages for certain terms. To avoid it, this PR adds the `noindex` tag to the taxonomy pages so search engines will crawling those pages.
Based on Hugo's docs, taxonomy pages have specific added variables that we can key off to add the tag: https://gohugo.io/variables/taxonomy/#example-usage-of-site-taxonomies

Add noindex to taxonomy pages

---

BLOGGING.md

I thought we had a note about how future dates don't prevent blog posts from getting published, but I don't see it, so adding it here.

Add a note about future-dated posts

---

themes/default/content/docs/intro/concepts/state.md

One of the snippets for `pulumi login s3://..` does not quote the URI. This won't work if someone tries to copy and run it because the '&' will be interpreted as a shell command to start a background process.
Fix by adding quotes around the login command.

backends/s3: Quote login argument

---

themes/default/content/docs/intro/concepts/secrets.md
themes/default/layouts/shortcodes/pulumi-config-getsecret.html
themes/default/layouts/shortcodes/pulumi-config-requiresecret.html
themes/default/layouts/shortcodes/pulumi-secret-new.html

Some of the documentation for secrets hard-codes
links to the Python APIs.
Replace these with shortcodes for those APIs
that change as different languages are selected.
Additionally, the following changes were made to the shortcodes:
- getsecret, requiresecret, secret-new: teach about Java
- secret-new: Fix Go API -- there's no "NewSecret", only "ToSecret"
Supersedes #2404
---
Before:
After:

concepts/secrets: Use language shortcodes for APIs

---

.github/workflows/push.yml

Removing the step that was accidentally re-introduced in https://github.com/pulumi/pulumi-hugo/commits/master

Remove merge step that was re-added in

---

themes/default/content/blog/pulumi-kubernetes-operator/index.md
themes/default/content/docs/guides/continuous-delivery/pulumi-kubernetes-operator.md

This change updates the references to https://github.com/metral/pulumi-nginx to point to a comparable project in pulumi/examples (https://github.com/pulumi/examples/tree/master/kubernetes-ts-nginx) instead, as metral/pulumi-nginx no longer installs. The replacement project is essentially identical, so should be a drop-in replacement. Internal thread for additional context: https://pulumi.slack.com/archives/C85BS3LJZ/p1674053144702009
Fixes https://github.com/pulumi/pulumi-hugo/issues/2408.

Update Kubernetes docs repo references

---

themes/default/content/docs/intro/languages/javascript.md

The upstream issue should be resolved, with details in https://github.com/pulumi/pulumi/pull/11932 and https://github.com/pulumi/pulumi/issues/11488.
This should be merged after pulumi/pulumi#11932 has merged in case there are any other issues with Node current.

Remove warning for Node 19.x

---

themes/default/content/resources/infrastructure-as-code-google-cloud/index.md

issue: https://github.com/pulumi/marketing/issues/679
create workshop for getting started with google cloud on 2/9/2023

add getting started with google cloud workshop 2/9/2023

---

themes/default/content/docs/guides/continuous-delivery/github-actions.md

With deployments, GitHub app permissions have been updated to include repo access to pull and deploy code. Updating the phrasing in the doc accordingly.

Update comments on github app permissions

---

themes/default/content/docs/intro/languages/dotnet.md
themes/default/content/docs/intro/languages/go.md
themes/default/content/docs/intro/languages/java.md
themes/default/content/docs/intro/languages/javascript.md
themes/default/content/docs/intro/languages/python.md
themes/default/content/docs/intro/languages/yaml.md

This change makes a few tweaks to the frontmatter params of our language pages in order to shorten the items in the TOC navigation and make the titles themselves a bit more consistent. 
Right now, these list items are pretty verbose, so they aren't quite as amenable to scanning as they used to be. With this change, we should be able to keep the desired SEO changes introduced with https://github.com/pulumi/pulumi-hugo/pull/2214 (as page titles and H1s won't be affected), but restore the navigation to its previous state.
Before:
After:
Hopefully this is acceptable; if the current UX is intentional, and it'd be significantly better to keep the longer titles in the navigation as well, let me know and I'll close. But this does seem like a better overall UX, and hopefully strikes a good …

Shorten language nav items

---

themes/default/content/docs/guides/crosswalk/aws/vpc.md

This PR ensures export names are consistent across all languages in the AWS Crosswalk guide. 
Fixes https://github.com/pulumi/docs/issues/8426

Standardize export names in Crosswalk guide

---

themes/default/content/docs/intro/concepts/config.md

Users often ask how to retrieve namespaced configuration values like `aws:region` and the like. This change adds some examples that show how to do that.

Clarify how to retrieve namespaced configuration

---

.github/workflows/push.yml
.github/workflows/scheduled-upstream-sync.yaml

part of issue: https://github.com/pulumi/home/issues/2566
This PR adds slack notifications on failures for workflows in this repo. These are enabled for the workflows that run on push to master and the upstream sync job. They are not turned on any jobs that run before a pull request merges. These notifications will get posted to the docs-ops channel in slack, which contains a link to the failed job and the name of the workflow that failed (listed as the actions url in the image below). 
The image below says "Pull Request" as the name of the workflow that failed, because I was using that workflow just for testing (they are not actually turned on for pull request failures though).

add slack alerting to notify on build failures

---

.github/workflows/push.yml
.github/workflows/scheduled-upstream-sync.yaml

There was a bug with the github action that is being used and there has been a [PR](https://github.com/rtCamp/action-slack-notify/pull/142) open in that repo for a few weeks to fix it and looks like the action maintainer has not gotten around to addressing it.  I went and forked the repo and applied the fix. I then rebuilt the action's docker image and published a new docker image with the fix for this to use. This PR just updates the action to reference the new docker image I published with the fix. We switch back to using the "official" action once they get around to addressing that PR.
The problem was that the action was coded to reference the workflow by a specific commit. The issue with that, is that often times when things are merged to master or pulled in from upstream, it kicks …

Fix action url link in slack alert

---

themes/default/layouts/product/pulumi-deployments.html

changes per https://github.com/pulumi/pulumi-hugo/pull/2469
buttons changed to "Get Started" and link to docs page rather than anchor to registration form, registration form removed.

remove deployments registration form, link buttons to docs page

---

STYLE-GUIDE.md

Per Slack discussion,
changes the recommendation on writing paragraphs
to suggest semantic line breaks instead.
The rationale behind the original recommendation was that
it made it easier to suggest changes to a pargraph during code review.
However, that's also possible with multi-line pargraphs
because GitHub supports multi-line comments and suggestions.
This new recommendation includes a new rationale for the choice
as well as a note about leaving existing documentation alone
until it's modified.
---
Rendered: https://github.com/pulumi/pulumi-hugo/blob/abhinav/sembr/STYLE-GUIDE.md#paragraphs-and-line-breaks

STYLE-GUIDE: Suggest semantic line breaks

---

themes/default/layouts/shortcodes/install-go.html

Some of our documentation currently states that
we support Go 1.18 or higher.
This is not accurate.
We support only those versions of Go that are supported by upstream Go:
typically the latest two minor versions (e.g., 1.20 and 1.19 right now).
This tweaks the wording there to just "supported versions"
instead of hard-coding 1.18 or 1.19
and having to update that 6 months from now.
---
This shortcode is used on the following pages:
```
% rg -l install-go
themes/default/content/docs/get-started/aws/begin.md
themes/default/content/docs/get-started/gcp/begin.md
themes/default/content/docs/get-started/kubernetes/begin.md
themes/default/content/docs/get-started/azure/begin.md
themes/default/content/docs/guides/automation-api/getting-started-automation-api.md
```
Previews:
- …

shortcode/install-go: Recommend "supported" versions of Go

---

themes/default/content/docs/guides/continuous-delivery/github-actions.md

Our documentation for how to use Pulumi with GitHub Actions
included GitHub Workflow files using setup-go@v2
referencing specific Go releases.
[actions/setup-go@v3](https://github.com/actions/setup-go#v3)
added support for a 'stable' (and 'oldstable') alias.
With this alias, the action will always use the latest stable Go release
instead of a specific version.
This updates our GitHub integration documentation
to recommend setup-go v3 and the 'stable' alias
over a specific pinned version.
That leaves this documentation and the sample workflow files
more future-proof as newer versions of Go are released.

cd/github: Recommend setup-go v3 with latest go-version

---

themes/default/content/docs/guides/continuous-delivery/github-actions.md

A few code fences on the GitHub Actions page use 'diff'
even though they contain YAML.
This switches those fences to YAML.

cd/github: Fix language on code fences

---

themes/default/content/blog/finops-with-pulumi/index.md

- Updated blog image
- Added the "automation-api" tag
- The section "Basic Tag Policy for FinOps will include" the items following it don't appear as a list, fixing it so it shows correctly.

FinOps with Pulumi: image + list + tag

---

themes/default/content/docs/guides/continuous-delivery/github-app.md

we still reguarly have people report issues installing the github app.
it will not install correctly if people install it direct from github.
they need to use the button from the service ui for it to work correctly.
this removes the direct links to the github app to hopefully reduce the number of people with issues.

remove direct links to github app

---

themes/default/content/docs/reference/deployments-rest-api/_index.md

See [this customer report](https://pulumi-community.slack.com/archives/C048NVDH6DV/p1677066467172729) in Slack. It looks like we have labeled the field as `"privateKey"` when it [expects](https://github.com/pulumi/pulumi-service/blob/master/pkg/apitype/deployments_git.go#L39) a field called `"sshPrivateKey"`

FIx bug with deploy docs: privateKey -> sshPrivateKey

---

themes/default/data/awards.toml
themes/default/layouts/page/about.html

A couple of awards URLs are no longer valid and don't seem to have good replacements. This change removes them and updates the page template to handle records with no URLs. (The Awards page already seems to handle this.)

Remove dead links, handle missing URLs on the About page

---

themes/default/content/docs/guides/pulumi-packages/how-to-author.md

Added the documentation for the `gitlab://` support for plugin hosting.
Implemented in https://github.com/pulumi/pulumi/releases/tag/v3.56.0

Document support for Gitlab releases to host plugin binaries

---

themes/default/theme/src/scss/_api-python.scss

Sphinx is now emitting a private unicode character ("\F0C1") corresponding to a FontAwesome chain icon next to headers, which renders as an empty box on our site.
Previously, it emitted a "¶" symbol ("\B6"), which we hid with CSS since we have our own way of injecting header links client side with JavaScript.
This change updates the styles to also hide the new unicode character.

Hide broken icon in python docs

---

themes/default/content/docs/get-started/gcp/deploy-changes.md
themes/default/content/docs/get-started/gcp/modify-program.md

Addressing two issues I discovered while going through the GCP Golang Get Started guide:
1. On the Modify Program step of the guide, `bucketEndpoint` is assigned but never used and therefore cannot compile. If a User wanted to run this program before proceeding to the Deploy Changes step, they would get an error like this: `./main.go:47:3: bucketEndpoint declared and not used`.
2. At the Deploy Changes step, `bucketEndpoint` is assigned before error handling for the previous call, which means it may proceed to attempt to access attributes from a `nil` value during interpolation when it should be providing the error from the `NewBucketObject` call.

Clean up `bucketEndpoint` use in GCP Golang Get Started

---

themes/default/content/docs/guides/testing/integration.md

original intent was to fix the 404 from the recent move of dotnet to its own repo
but i also saw some links in here to old branches, that seemed weird so i fixed them
imma be out so someone else pls take merging this
and feel free to push commits

fix 404 in testing docs

---

themes/default/layouts/page/product.html

fixing rendering of language chooser on mobile. it was a bit off in the mobile view.

fix width of language chooser on mobile

---

themes/default/content/blog/kubernetes-architecture-templates/index.md
themes/default/content/blog/pulumi-azure-2-0/index.md

`make serve` fails on master with different errors
because of unclosed shortcodes in some documents.
This change, along with pulumi/registry#2229 and pulumi/registry#2231
fixes `make serve` with the latest version of Hugo.
This change does not update to the latest copy of registry
because that'll happen automatically once this lands.
Resolves #2572

fix: Close unclosed shortcodes

---

themes/default/archetypes/blog-post/index.md
themes/default/archetypes/learn/module/_index.md
themes/default/archetypes/learn/topic/index.md
themes/default/archetypes/templates/template/index.md
themes/default/archetypes/templates/type/_index.md
themes/default/archetypes/video-transcript/index.md
themes/default/archetypes/webinar/index.md
themes/default/archetypes/whitepaper/index.md

We changed the style guide in #2474
to recommend Semantic Line Breaks for new content
while leaving old content as-is.
This had less of an effect
because our generated sample content does not comply with the guidance.
This updates all archetypes (templates for generated files)
to use semantic line breaks in both content and comments,
so that future content is more likely to match the guidance.

archetypes: Use Semantic Line Breaks per Style Guide

---

themes/default/content/resources/_index.md
themes/default/layouts/resources/rss.xml

Adds the rss feed to surface events sorted by date desc.

Add rss feed for events

---

themes/default/content/resources/advanced-infrastructure-as-code-2020-04-08/index.md
themes/default/content/resources/advanced-infrastructure-as-code-2020-04-16/index.md
themes/default/content/resources/armory-continuous-delivery-for-infrastructure/index.md
themes/default/content/resources/ask-the-expert/index.md
themes/default/content/resources/automating-infrastructure-as-code-workflows/index.md
themes/default/content/resources/aws-howdy-partner-twitch/index.md
themes/default/content/resources/azure-infrastructure-as-code-workshop-2020-07-23/index.md
themes/default/content/resources/azure-infrastructure-as-code-workshop-2020-10-19/index.md
themes/default/content/resources/cloud-engineering-in-aws-with-python/index.md
themes/default/content/resources/docker-show-multi-language-components/index.md
themes/default/content/resources/end-to-end-infrastructure-apps-and-auth-with-pulumi-and-auth0/index.md
themes/default/content/resources/getting-started-infrastructure-as-code-2020-03-30/index.md
themes/default/content/resources/hacktoberfest-2020/index.md
themes/default/content/resources/how-to-test-cloud-infrastructure/index.md
themes/default/content/resources/infrastructure-as-code-workshop-2020-04-09/index.md
themes/default/content/resources/intro-to-aws-crosswalk/index.md
themes/default/content/resources/introduction-to-infrastructure-as-code/index.md
themes/default/content/resources/multicloud-oss-database-deployments-with-aiven/index.md
themes/default/content/resources/sharing-and-reusing-infrastructure-best-practices/index.md
themes/default/content/resources/using-pulumi-to-supercharge-your-deployments/index.md
themes/default/content/resources/workshop-london-2020-09-23/index.md
themes/default/content/resources/workshop-nyc-2020-07-08/index.md
themes/default/content/resources/workshop-redmond-2020-03-12/index.md

List of changed resources (in case you don't want to crawl through a ton of files to figure this out)
https://www.pulumi.com/resources/advanced-infrastructure-as-code-2020-04-08/
https://www.pulumi.com/resources/advanced-infrastructure-as-code-2020-04-16/
https://www.pulumi.com/resources/armory-continuous-delivery-for-infrastructure/
https://www.pulumi.com/resources/ask-the-expert/
https://www.pulumi.com/resources/automating-infrastructure-as-code-workflows/
https://www.pulumi.com/resources/aws-howdy-partner-twitch/
https://www.pulumi.com/resources/azure-infrastructure-as-code-workshop-2020-07-23/
https://www.pulumi.com/resources/azure-infrastructure-as-code-workshop-2020-10-19/
cloud-engineering-in-aws-with-python (aliased)
https://www.pulumi.com/resources/docker-show-multi-language-compo …

block external search indexing on unlisted resources

---

themes/default/layouts/page/pricing.html

The rest of the links redirect with the alias, but these three appear to fail the docs build

fix deploy relrefs on pricing page

---

themes/default/content/pricing/_index.md

i believe google is scanning our pricing page for the word `cost` or an actual dollar amount
to inform the meta description, as its not currently displaying the actual meta description and instead is displaying...
>Estimated resources: 24 · Estimated monthly cost without applying free credits: $8.76 USD / 17,520 credits ...
[internal slack convo](https://pulumi.slack.com/archives/C0331801TGE/p1679864803005889)
very open to feedback on this, pls share your ideas if you have a better one!!!

adjust pricing meta description to appease google

---

themes/default/content/docs/intro/concepts/inputs-outputs.md

This PR adds documentation for the JSON stringify/parse methods added to the SDKs.
Fixes #2556

`[docs/intro/concepts/inputs-outputs]` document JSON output helpers

---

STYLE-GUIDE.md

Per discussion with @cnunciato,
change the style guide to allow for one-line pargraphs
as well as sembr paragraphs.
The only form explicitly forbidden is reflowing text.
Moved the rationale into a `<details>` section
with examples demonstrating value of each case.

STYLE-GUIDE: Allow one-line-pargraph and sembr

---

.github/workflows/pull-request-closed.yml
.github/workflows/push.yml
.github/workflows/scheduled-cleanup.yml

CI jobs appear to be failing with the message:
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead.
For more details see https://github.com/actions/virtual-environments/issues/6002
Switch them all to ubuntu-latest.

ci: Use ubuntu-latest

---

themes/default/content/docs/intro/concepts/stack.md

This adds a new section to the StackReference section,
explaining how to get values out of a stack reference.
It covers both getOutput and getOutputDetails,
with examples of when one is preferred over the other.
getOuput is primarily suggested when the result
is input to another resource (after some transforms)
and getOutputDetails is suggested when you need direct access.
Code samples for getOutput were adapted from existing cases.
For getOutputDetails, all code samples were manually verified
with a sample project locally.
Notes:
- This functionality does not currently work in Python
because we do not provide the ability to use `await`
in Python programs. Ref: pulumi/pulumi#12172
- Although this works in Java, that version of pulumi-java
has not yet been released.
We will not land this …

concepts/stacks references: explain OutputDetails

---

themes/default/content/resources/pulumi-up-2023/index.md

I think the timezone on this is wrong and it is affecting the date that will get displayed on the dashboard card we want to show in the console since it is compensating for the timezone which was enough to make it show the day before. So it is showing June 14 instead of June 15. It should be 8:00am pacific time (-7:00) from what I understand.

fix pulumi up timezone

---

themes/default/content/docs/intro/concepts/stack.md

We updated our documentation to mention project-scoped stacks for self-managed backends recently.
The documentation is accurate except that if a backend was initialized with an older version, it does not support this format.
Clarify that the new format is only available on new backends, or on migrated backends.
Resolves pulumi/pulumi#12633

concepts/stack: Clarify project scoping is available in new stacks only

---

themes/default/content/docs/intro/deployments/oidc/azure.md

Removing this note as the [linked issue](https://github.com/pulumi/pulumi-azure-native/issues/1324) has been merged.

Remove outdated OIDC Azure warning

---

themes/default/content/blog/pulumi-release-notes-85/index.md
themes/default/content/blog/pulumi-release-notes-m58/index.md
themes/default/content/blog/pulumi-release-notes-m59/index.md
themes/default/content/blog/pulumi-release-notes-m60/index.md
themes/default/content/blog/pulumi-release-notes-m61/index.md
themes/default/content/blog/pulumi-release-notes-m62/index.md
themes/default/content/blog/pulumi-release-notes-m63/index.md
themes/default/content/blog/pulumi-release-notes-m64/index.md
themes/default/content/blog/pulumi-release-notes-m65/index.md

the changelog file in the azure-native provider repo was renamed from CHANGELOD.md to CHANGELOG_OLD.md. This caused links to break where the file was being referenced. I see it says it is now deprecated, since we are moving it to github releases, but this will fix up the links so they don't 404.

update broken links

---

themes/default/layouts/index.html

Since these are same-site links, we should open them in the same tab.

Remove `target=_blank`s

---

themes/default/content/docs/get-started/aws/deploy-changes.md
themes/default/content/docs/get-started/aws/deploy-stack.md
themes/default/content/docs/get-started/aws/destroy-stack.md
themes/default/content/docs/get-started/aws/modify-program.md
themes/default/content/docs/get-started/aws/review-project.md
themes/default/layouts/shortcodes/cloud-intro.html

Fixes #2720.
The code changes here are based on a new repo, [pulumi/getting-started](https://github.com/pulumi/getting-started), that I've set up to test that each step of the guide continues to work as expected.

Restore the website workflow to the AWS getting-started guide

---

scripts/ci/common.sh
scripts/ci/pull-request-closed.sh

part of: https://github.com/pulumi/home/issues/2779
This PR removes the parameters used to track the preview buckets associated with PR commits once the PR. We have a limit for how many parameters we can store, so this will clean up the parameter used to track that particular bucket once the bucket gets deleted, since it is no longer needed at that point. We also need to do this in docs and registry repos as well, but will start here and verify this works since this repo does not run against the prod account.

delete parameter for bucket on closed PRs

---

themes/default/content/blog/pulumi-release-notes-80/index.md

Update github handle reference in release notes 80. User has updated their handle.

Update github handle reference in release notes 80

---

themes/default/content/blog/building-a-data-warehouse-on-aws-with-redshift-and-pulumi/index.md
themes/default/content/blog/create-manage-confluent-kafka-cluster-with-pulumi/index.md
themes/default/content/blog/how-to-create-and-share-a-pulumi-template/index.md
themes/default/content/blog/redshift-etl-with-pulumi-and-aws-glue/index.md

This PR updates four blog posts to add relevant/related Modern Infrastructure Wednesday (MIW) videos via the `youtube` shortcode.
This blog embeds related MIW videos into four blog posts:
- Building a data warehouse on AWS with Redshift and Pulumi
- Create and Manage Confluent Kafka Cluster with Pulumi
- How to Create and Share a Pulumi Template
- Redshift ETL with Pulumi and AWS Glue
Merging this PR will close https://github.com/pulumi/devrel-team/issues/542

Add MIW videos to blog posts

---

themes/default/layouts/blog/single.html
themes/default/theme/src/scss/main.scss

the newsletter input looks like a button without a label making a small change to make this look a bit more like an input
i don't think its possible to add a label cause this is hubspot
but this should make it a bit better
fixes https://github.com/pulumi/pulumi-hugo/issues/1707

make the newsletter input look more like an input

---

themes/default/content/blog/mapbox-iot-as-code-with-pulumi-crosswalk-for-aws/index.md
themes/default/content/blog/protecting-your-apis-with-lambda-authorizers-and-pulumi/index.md

follow on to https://github.com/pulumi/pulumi-hugo/pull/2766
missed 2 img links
`/blog/mapbox-iot-as-code-with-pulumi-crosswalk-for-aws`
`/blog/protecting-your-apis-with-lambda-authorizers-and-pulumi`

fix img links

---

themes/default/layouts/partials/header.html
themes/default/layouts/partials/top-nav.html

adding pulumi ai to practitioner nav
to those worried about the amount of space, docs+registry is collapsing into one soon
related
https://github.com/pulumi/registry/pull/2434
https://github.com/pulumi/pulumi-service/pull/13426

adding pulumi ai to practitioner nav

---

themes/default/content/resources/introduction-to-redis-and-pulumi/index.md
themes/default/layouts/resources/list.html
themes/default/layouts/webinars/single.html

Adds a workshop for Redis and Pulumi with date set as "to be announced".

Add workshop for redis

---

themes/default/layouts/docs/list.html

today i noticed we have a list layout and a single layout for docs. and the list layout is for all parent pages.
the parent pages have content on them, but i think they were previously not being indexed in swifttype
this adds it there
i might be totally wrong, pls tell me if i am
here's the single layout
https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/layouts/docs/single.html#L23-L25

adding swifttype to parent pages in docs

---

themes/default/content/blog/iac-recommended-practices-code-organization-and-stacks/index.md
themes/default/content/blog/iac-recommended-practices-developer-stacks-git-branches/index.md
themes/default/content/blog/iac-recommended-practices-structuring-pulumi-projects/index.md
themes/default/content/blog/iac-recommended-practices-using-stack-references/index.md
themes/default/content/blog/local-testing-with-pulumi/index.md

Update all GitHub links in all Zephyr posts to reflect switch from tags to branches
To make it possible to update the code at "older" points in time that correspond to previous blog posts, we needed to switch from using git tags to git branches. That change has been made, and this PR updates all Github links and references for all Zephyr posts to properly reference the correct git branch instead of the old git tag.

Update GitHub links for all Zephyr posts

---

go.mod
go.sum
themes/default/archetypes/templates/template/index.md
themes/default/layouts/shortcodes/choosable.html
themes/default/layouts/shortcodes/chooser.html

Adds a bit of validation logic to the `chooser` and `choosable` shortcode to ensure they receive the arguments they need to render choosers properly.
The PR checks here will fail until https://github.com/pulumi/registry/pull/2472 is merged (as that PR corrects the broken shortcode that led to this issue).

Validate choosers and choosables

---

themes/default/content/docs/clouds/aws/_index.md
themes/default/content/docs/clouds/gcp/_index.md

remove how-to guide buttons for aws-native and google cloud native cause they have no guides

---

themes/default/content/resources/pulumi-up-2023/index.md
themes/default/layouts/resources/rss.xml

Render the external link in place of the actual resource page link when the workshop is external. [We set the url_slug property in the workshop templates to that external link when the workshop is external.](https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/content/resources/production-ready-kubernetes-for-python-devs/index.md?plain=1#L35-L37)
https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/content/resources/production-ready-kubernetes-for-python-devs/index.md?plain=1#L35-L37
this is how it looks now for that workshop that was giving issues:

if external, render external link in rss feed

---

themes/default/content/docs/concepts/secrets.md

fix alias that is missing a slash

---

themes/default/layouts/resources/rss.xml

apparently the rss parsing library we are using in the service has some weird parsing logic where it is returning the guid as the link in some cases.... this will make the guid match the link for external resources as we are doing for the other events

make guid match link in rss feed

---

themes/default/theme/src/scss/_search.scss

i think we overlooked blog search when we updated the docs search
this should fix it up quickly
but we may want to revisit this
it seems for blog you have to type 2 letters to get results

fix blog search results

---

themes/default/layouts/partials/templates/breadcrumb.html

had no idea these marketing pages were using docs styles
this should fix it up

fix templates breadcrumbs

---

themes/default/content/learn/building-with-pulumi/stack-outputs/index.md

I think this is a typo, there is no `format` function in `pulumi` module.

Update "Understanding Stack Outputs" Python code

---

themes/default/layouts/partials/docs/search.html

changing the tab label
not planning any other changes quiet yet
if we get negative feedback we can revert this

change "registry" tab in docs to "packages"

---

themes/default/content/docs/languages-sdks/javascript/_index.md

The Platform team is often asked about support for different Node package managers. We're working on an epic to support PNPM, Yarn Berry, and NX, but for now our support is limited to Yarn Classic (without P'n'P) and NPM. 
This commit adds a short section explaining which managers are supported and how to use Yarn over NPM.
In the interest of "documenting what is, not what isn't", I've kept this section super narrow, not mentioning that some users have success with Yarn Berry and PNPM. As we advance through the monorepo epic, we're likely to add official support for PNPM; at that point, this section will fill out a bit more.

Node: Add description of support package managers

---

themes/default/content/docs/pulumi-cloud/access-management/saml/okta.md
themes/default/content/docs/pulumi-cloud/access-management/saml/sso.md

If we're going to improve the way we handle SAML expirations, we should also have this info in our docs. Most of our SAML users are using Okta as their IdP, so this also adds some instructions for setting that up with Okta specifically since it's not super straightforward.

Add docs on configuring SAML session lifetime

---

.github/workflows/pull-request.yml

Update action version. This version of the aws action is giving the set-output deprecation warnings which will be no longer usable at end of month.

update aws credentials action version

---

themes/default/content/docs/languages-sdks/_index.md
themes/default/content/docs/languages-sdks/dotnet/_index.md
themes/default/content/docs/languages-sdks/go/_index.md
themes/default/content/docs/languages-sdks/java/_index.md
themes/default/content/docs/languages-sdks/javascript/_index.md
themes/default/content/docs/languages-sdks/python/_index.md
themes/default/content/docs/languages-sdks/yaml/_index.md

the get started sections on these pages is confusing, and community convos makes people feel like they are in the wrong place. we also have a link to the get started page in the left nav, and the button at the top of the page. we also link to them from each of the cloud pages. dropping this content.

remove get started content from language pages

---

themes/default/content/docs/using-pulumi/pulumi-packages/how-to-author.md

Adds information to the Package Authoring guide.
This PR adds a link to the Pulumi Package publishing action for others to use.
It relies on the README in the Actions' repository for the details - that way we only update documentation in one place.
Fixes pulumi/home#2704.

Add Package Publisher to Authoring Guide

---

.github/workflows/pull-request-closed.yml
.github/workflows/scheduled-cleanup.yml

set-output is deprecated, so this bumps the version of these actions since they are now addressed there.

update aws action version to remove set-output

---

themes/default/content/docs/using-pulumi/pulumi-packages/how-to-author.md

sometimes the future never comes
we should document what is, not what might happen in the future as it often disappoints users or confuses them

remove future mention

---

themes/default/content/docs/concepts/projects/project-file.md

The plugins properties are lists, not single element. This is described in our schema here: https://github.com/pulumi/pulumi/blob/af3dea6e2d3ad15282835f19a9550c5b71b2fca6/sdk/go/common/workspace/project.json#L204-L231

Fix plugins in Pulumi.json reference

---

themes/default/content/docs/clouds/aws/_index.md
themes/default/content/docs/clouds/azure/_index.md
themes/default/content/docs/clouds/gcp/_index.md
themes/default/content/docs/clouds/kubernetes/_index.md
themes/default/layouts/partials/docs/cloud-overview.html
themes/default/theme/src/scss/docs/_cloud-overview.scss

reviewers note: i know i can refactor this and make it better and more dry
only trying to get this out quickly
this...
- adds the associated kube template to the cloud providers pages
- adds the missing kube template to the kube page

add missing kube template

---

themes/default/content/learn/abstraction-encapsulation/encapsulation/index.md

- Fixed issue with non existing `bucket` callable.
- Added `public_access_block_configuration` argument, because without it creating a public policy raises an error on AWS side: `Error putting S3 policy: AccessDenied: Access Denied`.
- Fixed and refactored `OurBucketClass` classes to align more closely with TypeScript examples.
- Reformatted examples with [black](https://pypi.org/project/black/) formatter.

Update "Understanding Encapsulation" Python code

---

themes/default/content/_index.md
themes/default/layouts/index.html

Primary CTA now [Get Started](https://www.pulumi.com/docs/get-started/)
Secondary CTA now [Contact Sales](https://www.pulumi.com/contact/?form=sales)

update CTAs on homepage to 'Get Started' and 'Contact Sales'

---

themes/default/theme/src/scss/_copy-button.scss
themes/default/theme/src/scss/components/_choosable.scss

- makes them float above code
- hides icon on smaller screens
- hides button on mobile screens
- 
an

fix up copy buttons

---

themes/default/content/confirmation/_index.md
themes/default/content/support/_index.md
themes/default/content/whitepapers/_index.md

block edit links on support, confirmation, and whitepapers pages. looks like this works.

block edit links

---

themes/default/theme/src/scss/_notes.scss

fixes https://github.com/pulumi/pulumi-hugo/issues/3009
if ya wanna see it live in the preview the concepts state and backends page has one
`/docs/concepts/state/#aws-s3`

fix code blocks in notes

---

themes/default/content/docs/clouds/gcp/get-started/_index.md

The code snippets under “review project” don’t actually match the created templates; for now I just made sure everything is consistent, but it might be better to somehow set them to auto-sync together? In particular, the code snippets under “review project” for typescript/javascript/python all fail because they don’t set location, so I added the equivalent of “location=US” everywhere (as it is in the current template code).
Also currently the tutorial tells you to configure Pulumi to access Google Cloud before making a project, which violates causality

fixing gcp template code

---

themes/default/assets/js/bundle.js
themes/default/theme/src/ts/algolia/autocomplete.ts

To help us better understand how our users are using search, this change [enables Algolia insights](https://www.algolia.com/doc/guides/building-search-ui/events/js), which sends anonymous usage data (such as click events) to Algolia.
Fixes https://github.com/pulumi/devrel-team/issues/573.

Enable Algolia insights

---

themes/default/content/docs/languages-sdks/yaml/yaml-language-reference.md

fixes table-formatting for clarity and correct columns
Updates formatting in tables of YAML documentation ( https://www.pulumi.com/docs/languages-sdks/yaml/yaml-language-reference/ ). Adds `|` in correct places to put text in correct column and add a single \` to format `config` correctly.

Update yaml-language-reference.md table-formatting

---

themes/default/content/docs/concepts/how-pulumi-works.md
themes/default/content/docs/concepts/programming-model.md

This change removes an alias to a placeholder page that we still need in order to properly redirect client-side requests based on HTML anchors. We have a number of places still linking to this page, at this particular URL (`/docs/intro/concepts/programming-model`), so we need this page to continue to exist in order to handle those requests.

Remove programming-model docs alias

---

themes/default/content/docs/clouds/gcp/get-started/begin.md

This change removes the use of a shortcode from the GCP getting-started guide because the shortcode's content doesn't quite work in this context. The change restores the content that belonged to the shortcode before this additional content (which is otherwise used only [in](https://github.com/pulumi/registry/blob/30b15aaa0aee99e8f734f252be1da57b5831b358/themes/default/content/registry/packages/gcp/installation-configuration.md?plain=1#L23) [the](https://github.com/pulumi/registry/blob/30b15aaa0aee99e8f734f252be1da57b5831b358/themes/default/content/registry/packages/gcp-global-cloudrun/installation-configuration.md?plain=1#L18) [Registry](https://github.com/pulumi/registry/blob/30b15aaa0aee99e8f734f252be1da57b5831b358/themes/default/content/registry/packages/google-native/installation-confi …

Pull shared content out of the GCP begin page

---

themes/default/layouts/partials/head.html

We've seen an uptick recently in Sentry errors originating from browsers that look like scrapers. This change adds a quick check to look at the user-agent string and bypass sending events to Sentry for browsers we know are problematic.

Don't send Sentry events for browsers we don't support

---

themes/default/content/docs/concepts/options/replaceonchanges.md

Seems like some Go syntax accidentally made it into the C# example snippet.

Fix C# code example

---

themes/default/content/docs/concepts/secrets.md

This PR adds an alias for the secrets docs page for `/secrets/` as requested by @SaraDPH .

Add alias for secrets docs page

---

themes/default/theme/src/scss/docs/_docs-main.scss

Small change to set height of ToC wrapper class to allow scrolling in _docs-main.scss
Currently navigating docs is a bit frustrating because your ToC can overflow offscreen as you scroll down long pages.
Ideally we'd make the ToC individually scrollable, remove/style the scrollbar for visual consistency, and also have it scroll to follow your position relative to the content. For now, this at least makes the ToC navigable again.
Fixes #3132.

Ease docs navigation experience by allowing ToC to be scrolled separately

---

themes/default/layouts/robots.txt

Adds a rule to prevent the docs we're adding temporarily for azure-native-v1 from being indexed by search engines.
Part of https://github.com/pulumi/registry/issues/2879.

Add a robots.txt exclusion for /registry/packages/azure-native-v1

---

themes/default/content/docs/concepts/resources/dynamic-providers.md

There was a change in the @octokit/rest package usage.
fixes:[[<link to issue>](https://github.com/pulumi/pulumi-hugo/issues/3120)](https://github.com/pulumi/pulumi-hugo/issues/3120)

Fix broken typescript example in dynamic-providers.md

---

.github/workflows/add-to-project.yml

Updates the Add Issues to Project workflow to post new issues to the Docs board instead of Developer Relations.
Part of https://github.com/pulumi/devrel-team/issues/607.

Post new issues to the Docs board instead

---

themes/default/content/docs/clouds/gcp/get-started/deploy-changes.md

Location is a required field on GCP bucket.
Fixes https://github.com/pulumi/pulumi-hugo/issues/3207

Fix missing location for gcp get-started guide

---

themes/default/content/docs/pulumi-cloud/access-management/access-tokens.md

Add admin tokens to the tokens permissions table to help surface more detail on the permissions available to these tokens.

Add admin tokens to access tokens perms table

---

themes/default/content/docs/concepts/resources/providers.md

Adds more clarification to the example in our explicit provider configuration section, to not the example does not apply to azure, which has cause some confusion in our community.
fixes :[#2614]

Update providers.md to add clarity on AWS vs Azure Example

---

themes/default/content/docs/clouds/gcp/get-started/deploy-changes.md
themes/default/content/docs/clouds/gcp/get-started/deploy-stack.md
themes/default/content/docs/clouds/gcp/get-started/destroy-stack.md
themes/default/content/docs/clouds/gcp/get-started/modify-program.md
themes/default/content/docs/clouds/gcp/get-started/review-project.md

This change fixes a number of issues with the GCP getting-started tutorial. There are a lot of little changes here, so I apologize for the noise. The primary changes are these:
* Adds required `location` properties to bucket declarations. These exist in the `gcp-*` templates, but were missing from the code samples. Without these, initial deployments would fail.
* Fixes a Go variable name in the modify-program step. Without this, the Go program would not compile.
* Fixes a warning about using a deprecated syntax for the `FileAsset` in YAML.
* Adds the `BucketIAMBinding` declaration earlier on in the program, removing the need for an additional `BucketIAMMember`. This was the main issue, and it broke in a few ways: 
* First, in Go, the `bucketMember` variable was unused, leading to a …

Fix GCP getting-started tutorial

---

themes/default/content/docs/concepts/resources/names.md

To resolve [this issue](https://github.com/pulumi/docs/issues/9591), I have added additional text to the Resource concept page to indicate/highlight that changing a resource's name will create a new resource and delete the old one.

Updated resource name change info

---

themes/default/content/docs/clouds/aws/guides/_index.md

On the Crosswalk for AWS Guides page, in the [Getting Started](https://www.pulumi.com/docs/clouds/aws/guides/#getting-started) section, the [try the Getting Started tutorial](https://www.pulumi.com/registry/packages/aws/how-to-guides/ecs-fargate/) part links to a How-To guide for ECS Fargate.
I was expecting to be sent to the equivalent of one of "Get Started" series (ex: [Get started with Pulumi & AWS](https://www.pulumi.com/docs/clouds/aws/get-started/)). I initially thought that I was redirected to an incorrect page altogether, but this How-To has a focus on deploying using Pulumi Crosswalk for AWS so I believe this was intentional.
This PR changes the verbiage so that the call to action is less confusing.
Fixes [#9650](https://github.com/pulumi/docs/issues/9650)

Updated "Get Started" verbiage

---

themes/default/layouts/shortcodes/install-python.html

We don't support Python 3.7 (it's end of life), but the install instructions still referred to it.
Rather than having to keep coming back and updating this number I've just removed the version text entirely, the link to the python downloads page clearly shows which versions are considers "active".

Remove erroneous reference to Python 3.7

---

themes/default/layouts/webinars/single.html

A recent UI change (https://github.com/pulumi/pulumi-hugo/pull/3259) accidentally removed the titles we show for a subset of these pages (upcoming workshops). This PR adds them back in.

Restore the title to upcoming workshops pages

---

themes/default/layouts/partials/header.html

fixes: https://github.com/pulumi/pulumi-hugo/issues/3236
change getting started CTA to link to getting started instead of console in the header

change cta getting started link

---

themes/default/content/docs/using-pulumi/adopting-pulumi/migrating-to-pulumi/from-terraform.md

Until we have built-in support for importing from tfstate, update the docs to not point at the archived (and not currently working for v4 state) import scripts.
Fixes #3265

Don't mention archived tfstate import scripts

---

themes/default/content/docs/pulumi-cloud/cloud-rest-api/_index.md

Curl example for Get Stack was related to user tokens (probably a copy-paste bug).

Update _index.md - Fix Get Stack curl example

---

themes/default/layouts/page/home-b.html

Removes the usage of relref on the b version of the homepage.

Remove relrefs from b version of home page

---

themes/default/content/docs/clouds/kubernetes/get-started/deploy-changes.md
themes/default/content/docs/clouds/kubernetes/get-started/modify-program.md

The [Kubernetes Getting Started guide](https://www.pulumi.com/docs/clouds/kubernetes/get-started/deploy-changes/) is not showing the updated output in the preview as expected when following the Python code.
This PR resolves this discrepancy by updating the code in the corresponding `else` statement to better accommodate for the asynchronous nature of Pulumi Outputs and to also provide a value to `result` which was previously being populated with `None`. This `None` value is what was preventing the new output from being shown in the preview.
Related to #1553

Updated Python code snippet to resolve Output discrepancy

---

themes/default/content/blog/announcing-6-0-of-the-pulumi-aws-classic-provider/index.md

A user [reported](https://github.com/pulumi/pulumi-aws/pull/2584#issuecomment-1699344037) that a breaking change was missing from the blogpost, and didn't look at the migration guide. When I went to point out the migration guide in the blogpost, I didn't see the link since it looked like it was part of "### MaxItemsOne and Deprecations".

Make the migration guide link more noticeable

---

themes/default/content/blog/managing-aws-credentials-on-cicd-part-1/index.md
themes/default/content/docs/using-pulumi/continuous-delivery/gitlab-ci.md

fixes: https://github.com/pulumi/docs/issues/9734
fix Gitlab links that are 404-ing. This is the most reasonable place I could find to link to as these pages no longer seem to exist.

fix broken GitLab links

---

themes/default/content/blog/introducing-azure-native-v2/index.md
themes/default/content/blog/kubernetes-4-0-even-more-kubernetes-native/index.md
themes/default/content/resources/azure-github-workshop/index.md

Add workshops to the launch blogs for Azure Native v2 and Kubernetes v4, along with minor changes to help with ongoing marketing. Also small tweaks to the Azure Native workshop page.

Changes to launch blogs

---

themes/default/layouts/partials/head.html

We've seen significant bot traffic from two specific user agents that are driving about 50% of our active users on Segment, driving us to overages. We'd like to filter them out from ever reaching Segment, to avoid renewing for a bigger contract with them for no reason.
These are the two user agents we've detected that are bringin up consumption considerably:
Mozilla/5.0 (compatible; SiteAuditBot/0.97; +http://www.semrush.com/bot.html)
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
e.g. for August, we've seen 187k bot users, out of a total of 314k users.
Solves https://github.com/pulumi/marketing/issues/794

Skip loading segment for specific user agents to filter bot traffic

---

themes/default/content/blog/iac-recommended-practices-code-organization-and-stacks/index.md
themes/default/content/blog/iac-recommended-practices-developer-stacks-git-branches/index.md
themes/default/content/blog/iac-recommended-practices-rbac-and-security/index.md
themes/default/content/blog/iac-recommended-practices-structuring-pulumi-projects/index.md
themes/default/content/blog/iac-recommended-practices-using-stack-references/index.md

This PR adds links to the latest Zephyr post to all earlier posts. This should have been done in the PR to publish the latest post, but it was missed.

Update links in earlier Zephyr posts

---

themes/default/content/docs/languages-sdks/yaml/_index.md

The example has a few issues:
1. It doesn't work - since AWS made breaking changes to public buckets earlier this year
2. It doesn't show off `config` or `options`
3. It uses the now-deprecated capitalized `Fn::` syntax
These changes address all three.

Improve the first YAML example

---

themes/default/content/docs/using-pulumi/continuous-delivery/gitlab-ci.md

Related to #1076 
Due to limited details in the original issue as well as the slack thread being over 90 days old, I was unable to acquire the context that I needed to reproduce the initial problem.
The updates made to this content were to provide more clarity on the topics covered and to update the NodeJS installation scripting which had soon to be deprecated code.
URL: /docs/using-pulumi/continuous-delivery/gitlab-ci/

Fix: GitLab CI pipeline integration docs not working

---

themes/default/content/blog/deploy-ai-ml-vercel-app/index.md

Fix an incorrect link pointing to the wrong Pulumiverse repository

Fix incorrect link to Katwalk repository

---

themes/default/layouts/shortcodes/install-go.html

We were calling 1.20 to 1.21 a minor release. Go calls that a major release.

Update install-go.html to align with Go terms

---

themes/default/content/blog/go-generics-preview/index.md

- Add example that shows off migrating from `ApplyT` to `pulumix.Apply`.
- Bunch of edits
- Promote the workshop and GopherCon
I still need to update the meta description and there's a TODO to mention how to reference branch of the AWS SDK in `go.mod`.

Go generics blog post edits

---

themes/default/layouts/partials/docs-top-nav.html
themes/default/layouts/partials/header.html
themes/default/layouts/partials/top-nav.html

In #3394, we removed the content page for /ai, which surfaced a number of `relref` failures from pages still using that shortcode to link to `/ai`. This change removes all `relref`s from the main and docs navs to fix that up.

Remove relrefs from the main and docs navs

---

themes/default/layouts/partials/footer.html

Fixes the broken links in the footer from removing relrefs.

Fix broken links for removing relref

---

themes/default/content/docs/using-pulumi/crossguard/configuration.md

The TypeScript examples for configuring policies is using `validateTypedResource`, but that should be `validateResourceOfType`.
Fixes #3426

Fix example code bug for configuring policies

---

themes/default/content/docs/pulumi-cloud/projects-and-stacks.md

Updating docs to reflect the new restore stacks limit of 25. Cloud PR for reference: https://github.com/pulumi/pulumi-service/pull/15863

Increase restore stacks limit to 25

---

themes/default/content/docs/install/_index.md

Redirect `/get-started/install` to `/docs/get-started/install`

add redirect get-started

---

themes/default/content/docs/install/esc.md

Fix https://github.com/pulumi/pulumi-hugo/issues/3469

Add brew update command to ESC install guide

---

themes/default/layouts/partials/head.html

Adds the page number to page 2+ of the blog lists so that in search it is clear what page the user is clicking on.

Add page number to blog list pages after the first page

---

themes/default/content/blog/introducing-crd2pulumi/index.md

Removes the front matter from this blog post to fix a sorting issue on the main blog listings.

Remove menu definition from front matter to fix sorting issue

---

themes/default/content/docs/pulumi-cloud/esc/get-started/_index.md

Latest update to ESC CLI no longer requires the Pulumi api URL. Updated content to remove this.

removed url from esc login command

---

themes/default/content/docs/pulumi-cloud/cloud-rest-api/_index.md

We weren't including the `preview` path in the esc API routes, causing them to error.

Fix esc api route URLs

---

themes/default/content/docs/support/faq.md

The IPs documented are the ones used by pulumi-service. This two new IPs are the NAT gateways configured in the workflow runners account

Update pulumi's outbound IPS with the ones used by workflow runners

---

themes/default/layouts/blog/single.html

We were loading the same hubspot form twice on a page which was leading to an error. This PR changes the blog nesletter form to have its own form id.

Use different form handler for blog newsletter form

---

themes/default/content/blog/pulumi-and-epsagon-define-deploy-and-monitor-serverless-applications/index.md

Epsagon was acquired by Cisco and rolled into their full-stack observability suite. Updated the previous Epsagon links to direct to this instead.

Updated Epsagon link to Cisco

---

themes/default/content/docs/languages-sdks/dotnet/_index.md

Noticed that official C# documentation has a code which doesn't compile: https://www.pulumi.com/docs/languages-sdks/dotnet/#example
Snippet was simply missing a `class` modifier.

Fix C# snippet

---

themes/default/content/learn/pulumi-fundamentals/configure-and-provision/index.md
themes/default/content/learn/pulumi-fundamentals/create-docker-images/index.md

I fixed a missing "fmt" import in the go program, without i the tutorial is not working.
I have also improved the tutorial with more information to guide the user.

fix: missing fmt in the go program and improve the "Pulumi Fundamentals" tutorial

---

themes/default/layouts/page/kubecon.html

Kubecon CTAs were all content aligned rather than card aligned

pin all the buttons on the kubecon page to the bottoms of the cards

---

.github/workflows/push.yml
Makefile
config/_default/config.yml
go.mod
go.sum
package.json
scripts/ci/await-in-progress.js
yarn.lock

As a follow-up to https://github.com/pulumi/pulumi-hugo-private/issues/112, this change does a couple of things, both aimed at reducing the likelihood of the merge conflicts we see when running the `push` and `upstream-sync` workflows:
* Removes the `hugo mod get` that attempts to pull in the latest from pulumi/registry (along with the reference to that module in the Hugo config). There's no technical need to import this module, particularly since the Registry now runs as a completely separate app; the only purpose it serves is to show something at /registry in PR previews and in local development. (Removing this therefore means navigating to /registry in PR previews and in local development will 404, but I'm assuming that won't cause too much pain for contributors to this repo.)
* Adds a …

Remove Registry module and await in-progress workflows

---

themes/default/content/blog/generative-ai-apps-devops-talks-pulumi-user-group/index.md

Google's ai is BARD not BERT https://bard.google.com

[bug] typo fix to replace s/BERT/BARD

---

themes/default/content/docs/pulumi-cloud/esc/get-started/_index.md

Remove `imports:` from docs which was deprecated before shortly the launch of Pulumi ESC.

Fix docs removing imports section

---

themes/default/content/docs/pulumi-cloud/esc/environments.md

Fix typo: Referencing an(d) environment

---

themes/default/content/docs/languages-sdks/dotnet/_index.md

We don't support .NET 3.1 and 5 anymore (EoL) but the install instructions still referred to it.
Rather than having to keep coming back and updating this number I've just removed the version text entirely, the link to the .NET support page clearly shows which versions are considers "active".
Fixes #3553.

Remove erroneous reference to .NET 3.1 and 5.

---

themes/default/content/docs/install/esc.md

Moves and consolidates headers up a level so that these are not nested within the language choosable shortcode. This then prevents the right nav from rendering duplicates. Headers level 1 through level 3 are updated.
The install script section was duplicated and this has been refactored into the OS-relevant sub-sections.
Fixes #3548

Updates markdown to avoid right nav duplicate entries

---

themes/default/content/docs/pulumi-cloud/deployments/get-started.md
themes/default/content/docs/pulumi-cloud/esc/get-started/_index.md
themes/default/content/docs/pulumi-cloud/insights/import.md
themes/default/content/docs/using-pulumi/define-and-provision-resources/index.md
themes/default/content/docs/using-pulumi/stack-outputs-and-references/index.md

Following up from https://github.com/pulumi/pulumi-hugo/pull/3554, this fixes up a few links that showed up in the most recent crawl:
- /docs/pulumi-cloud/deployments/get-started/ → https://www.pulumi.com/docs/pulumi-cloud/deployments/oidc/ (HTTP_403)
- /docs/pulumi-cloud/insights/import/ → https://www.pulumi.com/docs/pulumi-cloud/deployments/oidc/ (HTTP_403)
- /docs/using-pulumi/define-and-provision-resources/ → https://www.pulumi.com/docs/tutorials/stack-outputs-and-references/ (HTTP_404)
Also fixes a couple lil' typos.

Fix a few broken links

---

themes/default/content/docs/clouds/aws/get-started/next-steps.md
themes/default/content/docs/clouds/azure/get-started/next-steps.md
themes/default/content/docs/clouds/gcp/get-started/next-steps.md

Mentions ESC at the end of each getting-started guide as a thing to follow up with, and links to the new AWS tutorials instead of Learn, since that's there now.
Also tweaks a few words in the headings and bodies to make them a bit tighter and more engaging (verbs!).
Fixes https://github.com/pulumi/docs/issues/10214.

Add ESC as a next step to the AWS, Azure and GCP guides

---

themes/default/content/docs/pulumi-cloud/cloud-rest-api/_index.md
themes/default/content/docs/pulumi-cloud/esc/environments.md

This changes takes a thorough pass over Pulumi Cloud > Environments to fix several syntactical issues and flesh things out a bit more.

Updates to the ESC environments docs

---

themes/default/content/docs/pulumi-cloud/oidc/aws.md

This PR removes the word "Deployments" from the meta description.

Removed 'Deployments' from meta description

---

themes/default/content/docs/pulumi-cloud/oidc/vault/_index.md

This changes makes a few fixes to this page:
* Fixes some broken links
* Moves `vault.md` into the `vault` folder so it can live alongside the images that go with it
* Makes all links root-relative
* Fixes a few little typos
* Corrects the product name (Pulumi Console -> Pulumi Cloud console)

Fix a few issues with the Vault OIDC docs

---

themes/default/content/docs/clouds/gcp/get-started/review-project.md

Update gcp getting started guide go import to v7
Part of (https://github.com/pulumi/pulumi-gcp/issues/1243)

Update gcp getting started guide go import to v7

---

themes/default/content/docs/clouds/aws/get-started/deploy-changes.md

This change fixes a bug in the YAML path that references a non-existent `homepage` variable.
Fixes #3617. 
The automated tests didn't catch this because while the code in the getting-started repo was correct, a portion had been omitted (the `variables` block) when it was copied into the guide.
Related PR to update the automated tests to match what's included here: https://github.com/pulumi/getting-started/pull/12

Fix missing reference to 'homepage' variable

---

themes/default/content/resources/getting-started-with-1password-and-pulumi/index.md

Sales get a lot of requests about this workshop.
I am adding it to  Resources as there is clearly a demand for it.

Making the 1Password workshop on demand

---

themes/default/content/docs/pulumi-cloud/oidc/aws.md

As mentioned in
- pulumi/pulumi#14509 
both AWS and Azure currently send a subject claim ending in `<yaml>` rather then the actual environment name being used when utilising environments in IaC config. 
This adds a warning until this is resolved.

update AWS OIDC docs to highlight <yaml> issue when using environment in pulumi IaC

---

themes/default/content/docs/pulumi-cloud/oidc/gcp.md

Prompted by [this PR](https://github.com/pulumi/pulumi-hugo/pull/3637), I am adding the warning note to the GCP OIDC page about the [known `<yaml>` sub ID bug](https://github.com/pulumi/pulumi/issues/14509). This was originally noticed with Azure, but it seems to be a Pulumi ESC thing in general.

Adding warning note about <yaml> sub to GCP page

---

themes/default/content/docs/concepts/_index.md

Fix issue in javascript example on the "Pulumi" concepts page.
In the javascript code, the use strict mode was written as "user mode" and it was fixed.
- [] I added aliases (i.e., redirects) for all filename changes.

docs: fix issue in javascript example

---

themes/default/layouts/partials/header.html

Update the menu from "Cloud Engineering" to "Platform Engineering"

Change cloud engineering to platform engineering

---

themes/default/content/docs/pulumi-cloud/esc/get-started/_index.md

Addresses feedback and fixes https://github.com/pulumi/pulumi-hugo/issues/3656
New:
There may be scenarios where the value you need to retrieve is stored in a different environment file. For example, since your base application endpoint URL will be the same across environments, it would be more efficient to define it once in one place rather than multiple times across multiple environment files.

Adding clarity to importing environments section, also minor fixes

---

themes/default/layouts/shortcodes/example-program.html

This seems to be [causing a problem on the docs repo](https://github.com/pulumi/docs/actions/runs/7027215653/job/19121220357?pr=10309#step:9:84), so removing for now as it's not needed.

Remove os.Stat call for now

---

themes/default/content/what-is/what-is-aws-secrets-manager.md
themes/default/content/what-is/what-is-azure-key-vault.md

This PR corrects some linting errors in the AWS Secrets Manager and Azure Key Vault SEO pages. This will unblock merging the serverless SEO page.

Fix linting errors

---

.github/workflows/scheduled-test.yml

The access token we've applied to the repo doesn't work against the staging API, so removing that, and fixing the name up to align with other scheduled ones.

Fix example test workflow

---

themes/default/content/docs/pulumi-cloud/esc/reference.md

Spoke to a customer who got confused because of the current syntax. Changing it to improve clarity.

Changing the aws oidc environment variables in-line with the provider

---

themes/default/static/programs/aws-eks-cluster-go/go.mod.txt
themes/default/static/programs/awsx-ecr-eks-deployment-service-go/go.mod.txt
themes/default/static/programs/awsx-ecr-image-go/go.mod.txt
themes/default/static/programs/awsx-ecr-repository-go/go.mod.txt
themes/default/static/programs/awsx-elb-multi-listener-redirect-go/go.mod.txt
themes/default/static/programs/awsx-elb-private-subnet-go/go.mod.txt
themes/default/static/programs/awsx-elb-vpc-go/go.mod.txt
themes/default/static/programs/awsx-elb-web-listener-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-ec2-instances-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-fargate-ecr-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-fargate-nginx-go/go.mod.txt
themes/default/static/programs/awsx-vpc-fargate-service-go/go.mod.txt

Examples are all currently written for Go 1.20, and this is what we run in CI as well (as we currently support 1.20 and 1.21), so this change sets all `go.mod` files to use that.
Fixes https://github.com/pulumi/pulumi-hugo/issues/3702.

Set Go version to 1.20 to align with currently supported

---

themes/default/content/blog/continuous-delivery-with-gitlab-and-pulumi-on-amazon-eks/index.md
themes/default/content/blog/coronavirus-plan/index.md
themes/default/content/blog/gitlab-project-integration/index.md
themes/default/content/docs/using-pulumi/continuous-delivery/gitlab-app.md
themes/default/content/docs/using-pulumi/continuous-delivery/gitlab-ci.md

:link: [/blog/continuous-delivery-with-gitlab-and-pulumi-on-amazon-eks/](https://www.pulumi.com/blog/continuous-delivery-with-gitlab-and-pulumi-on-amazon-eks/) → https://docs.gitlab.com/ee/ci/multi_project_pipelines.html#passing-variables-to-a-downstream-pipeline (HTTP_404)
:link: [/blog/coronavirus-plan/](https://www.pulumi.com/blog/coronavirus-plan/) → https://about.gitlab.com/company/culture/all-remote/ (HTTP_404)
:link: [/blog/gitlab-project-integration/](https://www.pulumi.com/blog/gitlab-project-integration/) → https://docs.gitlab.com/ee/ci/merge_request_pipelines/ (HTTP_404)
:link: [/docs/using-pulumi/continuous-delivery/gitlab-app/](https://www.pulumi.com/docs/using-pulumi/continuous-delivery/gitlab-app/) → https://docs.gitlab.com/ee/ci/pipelines/pipelines_for_merged_results.html …

fixing broken gitlab links

---

themes/default/content/docs/pulumi-cloud/esc/providers/gcp-secrets.md

GCP secret manager provider page had sample example output of Azure's. Fixing that.

ESC - fixing azure example output in gcp provider page

---

themes/default/layouts/partials/example-program.html

Forgot to add this in #3720! It adds the GitHub icon to any `example-program`s we show on marketing pages as well (via the `example-program` _partial_):

Add GitHub icon to the example-program partial also

---

themes/default/content/blog/environments-secrets-configurations-management/index.md

The ESC post was using referencing `environments` instead of `environment` in the IaC integration section. This PR fixes up the typo.

Fix typo in esc blog post

---

themes/default/content/docs/concepts/_index.md
themes/default/content/docs/concepts/config.md
themes/default/content/docs/concepts/how-pulumi-works.md

This PR:
- Reorders the concept cards in the Overview page to match the order in the left navigation. 
- Promotes the "How pulumi works" page as the first page under the Concepts (this is how it was in the cards).
- Fixes the duplicate wording and icons on some of the cards.

Sync left nav + Concept cards ordering

---

themes/default/content/docs/clouds/kubernetes/get-started/review-project.md

- Fixes #3730
- Correctly displays the python filename `__main__.py` in a markdown bulleted item by adding a `choosable` for `python`.

Fix python markdown display

---

themes/default/content/docs/clouds/aws/get-started/review-project.md
themes/default/content/docs/clouds/azure/get-started/review-project.md
themes/default/content/docs/clouds/gcp/get-started/review-project.md

- Correctly displays the python filename `__main__.py` in a markdown bulleted item by adding a `choosable` for `python`.  This is updated across all the cloud getting started/review project pages.

Fix python markdown display (for all clouds)

---

scripts/test.sh

We seem to be exceeding available disk on the GHA runners (causing the tests to fail), so this change adds a cleanup step after each test run.
Fixes https://github.com/pulumi/pulumi-hugo/issues/3737
May also fix https://github.com/pulumi/pulumi-hugo-private/issues/184

Remove test artifacts after each test

---

themes/default/content/pricing/b.md
themes/default/layouts/page/pricing.html

This PR moves the pricing calculator out of the A/B test and into the main pricing page.

Move pricing calc to main pricing page

---

themes/default/layouts/partials/docs/main-nav.html

Similar to .NET (and Go and Java), open Python SDK docs in a new tab, since it's a different style from the rest of the site.
This will work when https://github.com/pulumi/docs/pull/10279 is merged & published, which changes the menu link for Python SDK docs to this particular URL.

Open Python SDK docs in a new tab

---

themes/default/content/docs/pulumi-cloud/oidc/gcp.md

I just spent several days trying to get this Google Cloud OIDC connection working with Pulumi Deployments. I believe the issue was trying to use a wildcard in the subject identifier as specified in this doc. After a/b testing with the subjects:
- `pulumi:deploy:org:ORG_NAME:project:PROJ_NAME:stack:STACK_NAME:operation:*:scope:write` 
- `pulumi:deploy:org:ORG_NAME:project:PROJ_NAME:stack:STACK_NAME:operation:update:scope:write`
<br>
I was only able to get the one without a wildcard to work. 
I saw the [Azure page documentation](https://www.pulumi.com/docs/pulumi-cloud/oidc/azure/#pulumi-deployments) regarding explict subject use, and roughly copied that over here. 
- [ X ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ X ] If …

Update gcp.md - modify subject claim documentation for clarity

---

themes/default/content/docs/concepts/options/aliases.md

Elide redundant type name for the array element for both examples on the page and add missing parenthesis for second example.

Fix Go example for resource aliases

---

themes/default/content/docs/concepts/projects/project-file.md

Template blocks now support optional `displayName` and `metadata` fields that are used by the console to aid in the discovery of any template (pulumi-hosted or self-hosted).

[project-file] add newly supported template fields

---

themes/default/content/docs/pulumi-cloud/esc/environments.md

Adds an info note to clarify that esc open is the correct command when opening a secret.

Add note wrt opening ESC secrets

---

themes/default/content/docs/languages-sdks/python/_index.md

There is an upstream issue that is currently preventing us from being able to support Python 3.12. Add a note about this in the docs until we're able to support Python 3.12.
Part of https://github.com/pulumi/home/issues/3259 (internal)

Note that Python 3.12 is not yet supported

---

themes/default/content/docs/install/_index.md

Fixes #3772
Updates the Pulumi CLI install page to include a link to the changelog.

Add changelog link to install page.

---

themes/default/layouts/index.html

Adds a bit of padding to even things out. Before:
After:

Add a bit of padding to the top of the home-page hero

---

themes/default/layouts/shortcodes/install-pulumi.html

Adds a brief note to the guide about how to verify Pulumi installed successfully.
Fixes #1671.

Add a post-install note to the getting-started guide

---

themes/default/content/docs/esc/_index.md
themes/default/content/docs/esc/faq.md
themes/default/content/docs/esc/reference.md

In #3828 we moved ESC to the top level, but missed adding redirects for a couple of pages. This should fix 'em up.

Add ESC aliases

---

themes/default/content/docs/clouds/aws/get-started/deploy-stack.md
themes/default/content/docs/clouds/gcp/get-started/deploy-stack.md
themes/default/content/docs/clouds/kubernetes/get-started/deploy-changes.md
themes/default/content/docs/clouds/kubernetes/get-started/deploy-stack.md
themes/default/content/docs/clouds/kubernetes/get-started/destroy-stack.md
themes/default/layouts/shortcodes/auto-naming-note.html

Fixes #247, and does a bit of cleanup around the Kubernetes output.

Add a note about auto-naming to the geting-started guides

---

themes/default/content/docs/concepts/resources/names.md

python dicts do not accept assignments {test='blub'}. There is also a parenthesis closing which was not needed.

fix(names.md): Wrong python syntax in examples

---

themes/default/content/docs/languages-sdks/python/_index.md

Python 3.12 is now supported with the v3.103.0 release of the Pulumi Python SDK (https://pypi.org/project/pulumi/).
Ref: https://github.com/pulumi/pulumi/pull/15190

Remove note about Python 3.12 not being supported

---

themes/default/content/docs/concepts/logging.md

The current python logging example does only work if you do `import pulumi as log`. 
This PR corrects that and make it compatible with the quickstart tutorial and other examples in this documentation by relying on `import pulumi`.

Correct python logging call in logging.md

---

themes/default/content/docs/install/_index.md

Redirects `pulumi.com/install` to `pulumi.com/docs/install` for easier access to installation instructions

Add install alias to root of web site

---

themes/default/content/docs/concepts/resources/components.md

After running `pulumi new typescript` and pasting the snippet as it exists today into `index.ts`, the compiler complains about `name` and `opts` being untyped. This fixes that.
Fixes #3907.

Add typings to the Components doc

---

themes/default/content/docs/clouds/aws/get-started/deploy-changes.md

This PR adds a missing `dependsOn` resource which was likely causing some actions to be taken before appropriate permissions were applied. This will update the code in the guide to match the code found in the Getting Started repo, and this should resolve the intermittent ACL/403 errors that were coming up.
Solves [this issue](https://github.com/pulumi/pulumi-hugo/issues/3902).

Add missing dependson

---

themes/default/content/blog/building-developer-portals/index.md
themes/default/content/blog/developer-portal-gallery/index.md
themes/default/content/blog/developer-portal-platform-teams/index.md
themes/default/content/blog/environments-secrets-configurations-management/index.md
themes/default/content/blog/future-cloud-infrastructure-10-trends-shaping-2024-and-beyond/index.md
themes/default/content/blog/mlops-huggingface-llm-aws-sagemaker-python/index.md
themes/default/content/blog/remediation-policies/index.md

Multiple articles relate to developer portals & platform engineering, but they need to be tagged to be found together.
The following tags will be added for SEO purposes (since they become part of the page itself) and for easy findability via tags. 
- developer-portals
- platform_engineering
Update: I also added other missing tags  on other somewhat related articles

Blog: adding tags, mainly for Dev portal and platform engineering

---

themes/default/content/blog/managing-github-with-pulumi/index.md

Since `pulumi-github` [v5.9.1](https://github.com/pulumi/pulumi-github/releases/tag/v5.9.1) released in May 2023, the `parentTeamId` property of `Team` accepts a `string` instead of an `int`.
The official Registry docs show the type as `string`, but this blog article still demonstrated the case when it accepted an `int`.

Since pulumi-github v5.9.1, `parentTeamId` is of type `string`

---

themes/default/layouts/robots.txt

Updates the robots.txt file to refer to our sitemap index files. (All of these sitemaps and indexes have already been submitted to Google and are fully indexed; this change just codifies this in the proper canonical location.)
Fixes #3938.

Update robots.txt to reference sitemap indexes

---

themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md

This PR fixes a missing video on Kubernetes workshop page (the video URL was inadvertently commented out; this PR removes the comment mark).

Fix missing video

---

themes/default/content/resources/building-a-kubernetes-platform-in-amazon-eks/index.md

The "Building a Kubernetes Platform in AWS EKS with Pulumi" workshop will not be hosted. It needs to be removed from resources.

Remove workshop from resources

---

themes/default/content/pricing/_index.md

In #3979, we removed a blog post for an offer that no longer exists, but we forgot to redirect to a new location. This change redirects requests for that page to the pricing page, which mentions that TF migration is available at Enterprise and above.
[Internal discussion](https://pulumi.slack.com/archives/CCBFCGU94/p1709143875085719?thread_ts=1709143472.696799&cid=CCBFCGU94).

Add an alias for the TF migration post

---

themes/default/content/docs/pulumi-cloud/projects-and-stacks.md

Fix the location in the portal where to find default stack permissions. It is under `Access Management` rather than `General`.

Fix the location in the portal where to find default stack permissions.

---

themes/default/content/docs/concepts/projects/project-file.md

Clarifies that `Pulumi.yaml`'s `main` value takes precedence over `package.json`'s and that paths are relative to `Pulumi.yaml`. Does a bit of minor cleanup as well.
Fixes #2189.

Add a note about  precedence in Node.js projects

---

themes/default/content/resources/exploring-the-intersection-of-cluster-api-and-infrastructure-as-code.md
themes/default/content/resources/nginx-deploy-kubernetes-and-the-kitchen-sink.md
themes/default/content/resources/winning-the-product-agility-jackpot.md

We deleted a number of outdated pages recently, but several are still being linked to from external sources (email, etc.). This change adds a few redirects to handle those while we await a more complete restoration and proper de-listing of the pages that were removed.
Fixes https://github.com/pulumi/marketing/issues/983.

Temporarily redirect some deleted content

---

themes/default/content/docs/concepts/_index.md
themes/default/static/programs/aws-ec2-instance-with-sg-csharp/Program.cs

Uses `id` attribute in explanatory text and in the C# example code rather than `name`.
Fixes #3999

fix(concepts): use `id` attribute for security group

---

themes/default/content/docs/clouds/aws/get-started/deploy-changes.md

While I was following the guide I stumble upon the following error:
```
./main.go:47:8: undefined: ownershipControls
./main.go:54:16: undefined: fmt
```
~~I was able to successfully create the infrastructure by adding the missing fmt library and removing the ownershipControls dependency.~~ 
- This could be fixed by adding the missing fmt library and set correctly the ownershipControls variable definition.

Fix ownershipControls definition and add fmt to go imports

---

themes/default/content/docs/concepts/secrets.md

Adds a note to clarify that checking these in is also safe and recommented. Also tidies up a bit of formatting and adds a few keywords to make this easier to find. ([Internal thread for reference](https://pulumi.slack.com/archives/C011EMDQ8JE/p1710371997870229).)

Add a note about checking encryption salts into source control

---

themes/default/content/docs/esc/providers/1password-secrets.md
themes/default/content/docs/esc/providers/_index.md
themes/default/content/docs/esc/reference.md

This updates the syntax reference page and adds a new Pulumi ESC provider page, 1Password. The syntax of the examples was tested using the `zephyr` Pulumi Org.
Closes https://github.com/pulumi/pulumi-hugo/issues/4047

Adds docs for Pulumi ESC 1Password provider

---

themes/default/content/resources/getting-started-with-iac-google-cloud/index.md
themes/default/content/resources/getting-started-with-iac-on-aws/index.md
themes/default/content/resources/getting-started-with-infrastructure-as-code-aws/index.md
themes/default/content/resources/mastering-ci-cd-pipelines-gitlab-pulumi/index.md
themes/default/content/resources/real-world-platform-engineering-spot-netapp-pulumi/index.md

redoing [this PR](https://github.com/pulumi/pulumi-hugo/pull/4048) due to extra files in the commit
added the following workshops:
https://github.com/pulumi/marketing/issues/979
https://github.com/pulumi/marketing/issues/980
https://github.com/pulumi/marketing/issues/981
https://github.com/pulumi/marketing/issues/982
https://github.com/pulumi/marketing/issues/965

add batch of April workshops to events page

---

themes/default/content/docs/concepts/inputs-outputs/outputs-and-strings.md

Fixes https://github.com/pulumi/docs/issues/11041.
Nothing was particularly _wrong_ here -- it's just that the leading quotes were running afoul of our link-translation tool, and in fixing that, I realized we could just use `redirect_to`, which effectively does the same thing as manually adding a `meta` tag to the content of the page (albeit in a uniform way across the site).

Use  for a client-side redirect

---

.prettierignore

Running `make lint` shouldn't warn on files that are produced by the CSharp build process. Add those paths to the `.prettierrc` file

Remove some lint warnings

---

themes/default/layouts/community/community-engineering/single.html
themes/default/static/programs/aws-simulated-server-interpolate-go/go.mod.txt

The docs build is failing due to this broken relref link that is trying to link to `/community/community-engineering`. This appears to be a top level page that I'm guessing would list out all the community engineers. This page seems to no longer exist. So I'm removing the link for now, to unblock the build  and we can decide if we want to bring that page back later and then we can add back the link.

Remove broken link to community-engineering page.

---

themes/default/content/docs/clouds/aws/guides/api-gateway.md
themes/default/content/docs/clouds/aws/guides/autoscaling.md
themes/default/content/docs/clouds/aws/guides/aws-index-of-services.md
themes/default/content/docs/clouds/aws/guides/cloudwatch.md
themes/default/content/docs/clouds/aws/guides/ecr.md
themes/default/content/docs/clouds/aws/guides/ecs.md
themes/default/content/docs/clouds/aws/guides/eks.md
themes/default/content/docs/clouds/aws/guides/elb.md
themes/default/content/docs/clouds/aws/guides/lambda.md
themes/default/content/docs/clouds/aws/guides/vpc.md
themes/default/layouts/shortcodes/crosswalk-header.html

This change adds documentation for how to configure `CallbackFunction` resources with Lambda layers and adjust the files and folders that are included (or excluded) in a function package. Also adds a few much-needed details, including links to source code (while we await actual SDK docs), event types (as I constantly forget these myself), and keywords to make all this content more easily findable. 
Note the link to an [accompanying example here](https://github.com/pulumi/examples/pull/1623) that should be merged before this change goes in (so the link doens't break). I'll work on getting its README fleshed out while folks review the changes included here.
Fixes https://github.com/pulumi/pulumi-aws/issues/1950.
Fixes https://github.com/pulumi/pulumi-hugo/issues/4025.
Fixes …

Add documentation for using CallbackFunction with Layers

---

themes/default/static/programs/aws-iampolicy-jsonparse-csharp/Program.cs
themes/default/static/programs/aws-iampolicy-jsonparse-go/go.mod.txt
themes/default/static/programs/aws-iampolicy-jsonparse-go/main.go
themes/default/static/programs/aws-iampolicy-jsonparse-javascript/index.js
themes/default/static/programs/aws-iampolicy-jsonparse-python/__main__.py
themes/default/static/programs/aws-iampolicy-jsonparse-typescript/index.ts

Fixes the C# example by using plain Dictionary types instead, and adds a bit of clarity (hopefully!) to the comments about what's going on in the code. (Also runs black, Prettier, Csharpier for formatting.)

Fix C# JsonDeserialize example

---

themes/default/content/docs/pulumi-cloud/oidc/aws.md

I'm looking to ensure that the `aud` claim strictly matches the organization name. I propose using the `StringEquals` condition rather than the `StringLike` condition to enforce this strict match.
In the event a user decides to remove or not specify a subject, and the `StringLike` condition remains for the audience, then the door is open for a malicious actor (who has knowledge of the role ARN) to assume the AWS OIDC role. For example, a malicious actor could create a Pulumi org called *contoso-malicious*, which can be leveraged to assume a role in the *contoso* org.
Also, I am changing reference from Azure to AWS in the warning note.

Proposing Modification to the Subject Claim Examples for AWS OIDC

---

themes/default/content/docs/install/_index.md

Add instructions for installing the dev version of the pulumi CLI to our installation page.  This helps make it more discoverable and may get more people to use it and report bugs early.
Part of https://github.com/pulumi/docs/issues/11100

add instructions for installing dev CLI

---

themes/default/content/docs/languages-sdks/dotnet/_index.md
themes/default/content/docs/languages-sdks/go/_index.md
themes/default/content/docs/languages-sdks/javascript/_index.md
themes/default/content/docs/languages-sdks/python/_index.md

Similar to how we are adding instruction for installing the dev channel CLI, we want to do the same for the SDKs.  This feels a little more awkward, since the pages don't give super clear instructions how to install our SDKs in the first place.  Any suggestions where to place this are welcome!
Part of https://github.com/pulumi/docs/issues/11100

add instructions for installing dev releases of SDKs

---

themes/default/content/resources/cicd-for-aws-with-pulumi-and-github-actions/index.md
themes/default/content/resources/deploying-langchain-apps-on-aws-with-pulumi/index.md
themes/default/content/resources/mastering-ci-cd-pipelines-gitlab-pulumi/index.md
themes/default/content/resources/real-world-platform-engineering-spot-netapp-pulumi/index.md
themes/default/content/resources/scaling-ai-apps/index.md
themes/default/static/programs/aws-iampolicy-jsonparse-go/go.mod.txt

[workshops] Adding/Updating the tags for workshops

---

themes/default/content/docs/esc/environments.md

Two of the provided context options were missing the `pulumi` part of the path.

Fix ESC context options

---

themes/default/static/programs/aws-s3-bucket-resources-csharp/Program.cs
themes/default/static/programs/aws-s3-bucket-resources-go/main.go
themes/default/static/programs/aws-s3-bucket-resources-java/pom.xml
themes/default/static/programs/aws-s3-bucket-resources-java/src/main/java/myproject/App.java
themes/default/static/programs/aws-s3-bucket-resources-javascript/index.js
themes/default/static/programs/aws-s3-bucket-resources-python/__main__.py
themes/default/static/programs/aws-s3-bucket-resources-typescript/index.ts
themes/default/static/programs/aws-s3-bucket-resources-yaml/Pulumi.yaml

`17` is a valid version, but we run `11` in CI (as this is the [earliest supported version](https://www.pulumi.com/docs/languages-sdks/java/)).
Fixes https://github.com/pulumi/pulumi-hugo/issues/4153.

Fix failing program test

---

themes/default/content/docs/languages-sdks/javascript/_index.md

Add section about TypeScript versions

---

themes/default/content/blog/nx-monorepo/index.md

Add an info note about typescript versions to the nx monorepo blog
http://pulumi-hugo-origin-pr-4189-b3809a13.s3-website.us-west-2.amazonaws.com/blog/nx-monorepo/#typescript

Add link to the new TypeScript versioning setup to the monorepo blog

---

themes/default/content/blog/pulumi-release-notes-103/index.md
themes/default/content/blog/pulumi-release-notes-85/index.md
themes/default/content/blog/pulumi-release-notes-87/index.md

fix up some broken links. Changelogs no longer exist in the pulumi-aws-native repo. The changes are now itemized in the released notes so linking there.

fix broken links

---

themes/default/content/resources/getting-started-with-iac-on-aws-python/index.md
themes/default/content/resources/how-to-migrate-to-pulumi-from-terraform/index.md

https://github.com/pulumi/marketing/issues/998
https://github.com/pulumi/marketing/issues/999
https://github.com/pulumi/marketing/issues/1024

add a batch of May workshops to resources

---

themes/default/content/docs/pulumi-cloud/oidc/provider/_index.md
themes/default/content/docs/pulumi-cloud/oidc/provider/aws.md

Once this is merged, will copy over the format to Azure, GCP, and Vault OIDC pages as well.

Updating ESC OIDC Token Claims & Subject Customization

---

themes/default/content/docs/pulumi-cloud/deployments/drift.md
themes/default/content/docs/pulumi-cloud/deployments/schedules.md

couple of minor fixes while building docs

---

themes/default/content/docs/languages-sdks/yaml/yaml-language-reference.md

Small fix in the yaml reference - was missing the resources declaration.

Fix indentation in yaml reference for explicit providers

---

themes/default/content/blog/next-level-iac-pulumi-runtime-logic/index.md

Forgot to update the code snippets before publishing. This ought to do it.

Update snippets to match the checked-in/tested code

---

themes/default/content/resources/managing-team-secrets-1password-pulumi-esc/index.md

add 1password workshop youtube url for on-demand workshops

add 1password workshop youtube link

---

themes/default/content/docs/esc/other-integrations/_index.md
themes/default/content/docs/esc/other-integrations/direnv.md
themes/default/content/docs/esc/other-integrations/docker.md
themes/default/content/docs/esc/other-integrations/kubernetes.md

Adds an ESC documentation page for Kubernetes integration.
Closes: https://github.com/pulumi/pulumi-kubernetes/issues/2965

K8 - Pulumi ESC Docs

---

themes/default/theme/src/scss/_chroma.scss

This makes a small change to the CSS for code blocks that have highlighted lines. I ran the bundler to update the `bundle.css` file and also changed it in the source `.scss` file.
A code block like this:
```typescript {hl_lines=[2]}
import * as aws from "@pulumi/aws";
import * as childProcess from "child_process";
```
Will currently render with this background color, which is hard to read:
After this change it will look like this:

Fix CSS background color to be more readable for code listings with highlighted lines

---

config/_default/config.yml
themes/default/static/programs/aws-simulated-server-interpolate-go/go.mod.txt

Updates "Request a change" link to open issues in docs instead of pulumi-hugo, since we are moving everything there.
I updated the contentRepositoryURL prop to do this. [This](https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/layouts/partials/docs/table-of-contents.html#L77) is the only place I have found it being referenced, i.e. in the TOC for the request a change link.

update request change issue link

---

themes/default/content/docs/concepts/update-plans.md

"than" was incorrectly used instead of "then". Also made a couple of other grammatical improvements.

Fix typo update-plans.md
