pulumi/pulumi-hugo

themes/default/content/blog/amazon-eks-anywhere-bare-metal/index.md

imma be out so someone else pls take merging this
feel free to push commits

fix 404 bare metal link in blog

---

themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md

The meta description and speakers were also updated.

Update to show video

---

themes/default/content/docs/guides/continuous-delivery/github-actions.md

Change note to past tense

---

themes/default/content/docs/reference/project-file.md

Nitpicking - fixed some typos and improved some sentences.
pr addressing issue - #2508
please let me know if you want more changes.

Updated project.md

---

themes/default/layouts/page/about.html

Remove extra period

---

themes/default/content/docs/guides/continuous-delivery/github-app.md

There was no opening parenthesis to match

Fix out of place parenthesis

---

themes/default/content/pulumi-up/_index.md
themes/default/layouts/page/pulumi-up-2023.html

Makes a few minor adjustments to draw a clearer distinction between last year's content and this year's.

Minor tweaks to PulumiUP page content

---

themes/default/content/_index.md

im assuming when folks update their images these break
this is fixing them
fixes #2640

fix broken imgs

---

themes/default/content/blog/project-scoped-stacks-in-self-managed-backend/index.md

Flesh out the intro a little more, and adjust the title.

Intro edits for project support blog

---

themes/default/content/blog/create-aks-clusters-with-monitoring-and-logging-with-pulumi-azure-open-source-sdks/index.md

addressing this comment
https://github.com/pulumi/pulumi-hugo/pull/2639#issuecomment-1493189343

fix aks clusters blog grammar

---

themes/default/layouts/_default/baseof.html

this isnt being used, so removing

remove unused div from baseof html

---

themes/default/content/blog/if-you-liked-ksonnet-youll-love-pulumi/index.md

i missed part of eric's feedback since it was in a quote; this is the addressing the rest of it
https://github.com/pulumi/pulumi-hugo/pull/2639#issuecomment-1493189343

remove irrelevant link

---

themes/default/layouts/page/reinvent.html

this link isnt a thing anymore

remove link thats 404ing on reinvent page

---

themes/default/content/blog/2022-03-10-hierarchical-config/index.md

Update older post to link to announcement of support for hierarchical config
Fixes https://github.com/pulumi/devrel-team/issues/458

Update older hierarchical config post

---

themes/default/content/kubecon/_index.md

remove 'KubeCon' from happy hour

---

themes/default/theme/src/scss/main.scss

attempt to fix safari api docs nav bug

---

themes/default/content/blog/advanced-aws-networking-part-1/index.md

Fix links on AWS advanced networking blog post.

---

themes/default/layouts/page/pricing.html

https://github.com/orgs/pulumi/projects/33/views/3?filterQuery=assignee%3Akimberleyamackenzie&pane=issue&itemId=24292771
Fixes https://github.com/pulumi/pulumi-hugo/issues/2624, which was originally from https://github.com/pulumi/pulumi-service/issues/8473.  
This updated link points to sign up, and then a new org dialog should open automatically after signing up (as per existing behavior).

Update pricing page link

---

themes/default/content/blog/pulumi-kubernetes-operator/index.md

fixing a link thats 500ing, and using the direct link
also adding slashes to the end of a bunch of URLs to eliminate redirects

fix 500 link

---

themes/default/content/docs/guides/scim/faq.md
themes/default/content/security/_index.md
themes/default/layouts/partials/help-links.html

try and fix suport 403s

---

themes/default/content/blog/pulumi-kubernetes-operator/index.md

remove 404

---

STYLE-GUIDE.md

addressing this comment https://github.com/pulumi/pulumi-hugo/pull/2673#pullrequestreview-1378247605

address feedback on style guide

---

themes/default/content/docs/intro/deployments/_index.md
themes/default/content/docs/intro/pulumi-cloud/_index.md
themes/default/content/docs/intro/pulumi-cloud/accounts.md
themes/default/content/docs/intro/pulumi-cloud/audit-logs.md
themes/default/content/docs/intro/pulumi-cloud/billing-managers.md
themes/default/content/docs/intro/pulumi-cloud/ci-cd-integration-assistant.md
themes/default/content/docs/intro/pulumi-cloud/organization-access-tokens.md
themes/default/content/docs/intro/pulumi-cloud/organizations.md
themes/default/content/docs/intro/pulumi-cloud/projects-and-stacks.md
themes/default/content/docs/intro/pulumi-cloud/pulumi-button.md
themes/default/content/docs/intro/pulumi-cloud/team-access-tokens.md
themes/default/content/docs/intro/pulumi-cloud/teams.md
themes/default/content/docs/intro/pulumi-cloud/webhooks.md

fix deployments alias

---

themes/default/content/docs/reference/cloud-rest-api/_index.md

fix rest api link

---

.github/pull_request_template.md

updating pr template

---

themes/default/content/kubecon/_index.md

KubeCon Info correction

---

themes/default/layouts/partials/header.html

Remove menu item

---

themes/default/content/product/pulumi-cloud.md
themes/default/layouts/product/pulumi-cloud.html

This PR removes a relref for case studies.

Fix up relref for case studies

---

themes/default/content/blog/pulumi-insights/index.md
themes/default/data/newsroom.toml
themes/default/layouts/partials/banner.html

Update banner and newsroom

---

themes/default/content/blog/pulumi-insights/index.md

Pulumi Insights blog post had a bad Youtube video link.

Fix Pulumi AI youtube video link

---

themes/default/content/docs/intro/insights/import.md

fix links on pulumi cloud import docs page

---

.github/pull_request_template.md
themes/default/content/docs/guides/self-hosted/_index.md
themes/default/content/docs/guides/self-hosted/requirements/_index.md
themes/default/content/docs/guides/self-hosted/requirements/network.md

Information about ingress and egress for Pulumi cloud

Added information about Pulumi cloud networking requirements

---

scripts/ci/sync.sh

Update s3 bucket permissions, since AWS has changed the default setting for newly created buckets. 
https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/

Update s3 bucket permissions

---

themes/default/content/resources/getting-started-with-pulumi-insights/index.md

Pulumi Insights workshop per https://github.com/pulumi/marketing/issues/728

add Pulumi Insights workshop

---

config/_default/config.yml

https://github.com/pulumi/pulumi-hugo/issues/2722

update homepage title to reflect new messaging

---

themes/default/layouts/page/pricing.html

fixing links for the rest of my life

fix broken contact links

---

themes/default/content/docs/intro/concepts/resources/options/version.md

add more deets to resource version docs

add more deets to resource version docs

---

themes/default/content/docs/guides/crosswalk/aws/vpc.md

Fix CIDR block

---

themes/default/content/docs/_index.md
themes/default/content/docs/get-started/_index.md

Removing universal from this page

Remove universal from IaC description

---

themes/default/content/blog/upcoming-aws-pulumi-webinar-on-feb-5/index.md
themes/default/content/case-studies/learning-machine.md
themes/default/layouts/partials/learning-machine.html

machine learning isnt a thing anymore
its hyland now
i believe marketing will be following up with more changes

fix machine learning links

---

themes/default/content/docs/intro/deployments/oidc/azure.md

Fixing some incorrect environment variables. Pulled the new values from source code.

Fix environemnt variables in Azure OIDC docs

---

themes/default/content/docs/intro/pulumi-cloud/_index.md

I updated the messaging, added new features, and cleaned up the organization of this page since it was outdated.

Update pulumi cloud docs page

---

themes/default/content/docs/guides/crosswalk/aws/ecr.md

It seems the command changed between the publishing of this document and now.

Update command to current CLI version

---

themes/default/content/about/_index.md
themes/default/content/about/leadership.md
themes/default/content/about/newsroom.md
themes/default/content/blog/easily-bring-your-team-to-pulumi/index.md
themes/default/content/blog/getting-started-with-k8s-part1/index.md
themes/default/content/blog/getting-started-with-k8s-part2/index.md
themes/default/content/blog/getting-started-with-k8s-part3/index.md
themes/default/content/blog/kubernetes-fundamentals-part-one/index.md
themes/default/content/blog/kubernetes-fundamentals-part-two/index.md
themes/default/content/blog/pulumi-challenge-september/index.md
themes/default/content/blog/pulumiup-bring-your-whole-team-to-pulumi/index.md
themes/default/content/cloud-engineering-summit/_index.md
themes/default/content/cloud-engineering-summit/agenda.md
themes/default/content/cloud-engineering-summit/sessions.md
themes/default/content/cloud-engineering-summit/speakers.md
themes/default/content/docs/get-started/aws/deploy-changes.md
themes/default/content/docs/get-started/aws/deploy-stack.md
themes/default/content/docs/get-started/azure/deploy-changes.md
themes/default/content/docs/get-started/azure/deploy-stack.md
themes/default/content/docs/guides/_index.md
themes/default/content/docs/guides/automation-api/_index.md
themes/default/content/docs/guides/scim/_index.md
themes/default/content/docs/reference/pkg/_index.md
themes/default/content/docs/reference/pulumi-sdk.md
themes/default/content/resources/creating-business-logic-interfaces-automation-api/index.md
themes/default/content/resources/getting-started-with-aws/index.md
themes/default/content/resources/getting-started-with-iac-aws/index.md
themes/default/content/resources/getting-started-with-iac-pulumi-aws/index.md
themes/default/content/resources/getting-started-with-kubernetes-google-cloud/index.md
themes/default/content/resources/kubernetes-on-google-cloud/index.md

This PR addresses duplicate title tags and meta descriptions which are part of the following issues:
- fixes https://github.com/pulumi/registry/issues/2285
- fixes https://github.com/pulumi/registry/issues/2286

SEO fixes for duplicate title tags and meta descriptions

---

themes/default/content/blog/pulumi-release-notes-80/index.md

Capitalize Git references where applicable

Capitalize Git references where applicable

---

themes/default/layouts/ai/section.html

This allows using the env var configured in `build.sh` for Pulumi AI development with alternative backends.

Enable local pulumi.ai dev

---

themes/default/data/newsroom.toml

remove broken links from newsroom

remove broken links from newsroom

---

themes/default/content/blog/peace-of-mind-with-cloud-secret-providers/index.md

fixes https://github.com/pulumi/devrel-team/issues/551

fix aws 404

---

themes/default/data/awards.toml

a broken link.
to a news article.
removing it.

update broken news link

---

themes/default/content/resources/production-ready-kubernetes-for-python-devs/index.md

update CNCF workshop description

---

themes/default/content/docs/guides/adopting/from_terraform.md

from_terraform.md: use v5 of github.com/pulumi/pulumi-terraform

---

themes/default/content/blog/stack-readme/index.md

Templates reference stack outputs, not arbitrary resources in the stack.

Fix a typo in stack readmes

---

themes/default/theme/src/scss/_registry.scss
themes/default/theme/src/scss/main.scss

part of https://github.com/pulumi/registry/pull/2437

add styles for pulumi ai button on registry resource pages

---

themes/default/content/blog/join-pulumi-user-group-community/index.md

Adding Austin PUG and updating number of PUGs to 8

---

themes/default/theme/src/scss/_registry.scss

forgot the & in here.. 😞 
follow on to.. https://github.com/pulumi/pulumi-hugo/pull/2781

fix hover styles on resources pulumi ai button

---

.github/pull_request_template.md

its easy to forget to rebuild the bundle, since it works locally; adding a checklist item 
especially when working cross-repo (e.g., with registry)

add a checklist item about css changes

---

themes/default/layouts/index.html

Change homepage secondary button and link per https://github.com/pulumi/pulumi-hugo/issues/2791

Update secondary homepage button to 'Get Started'

---

themes/default/content/about/_index.md

Update Dream Big value

---

themes/default/content/testimonials/_index.md
themes/default/layouts/page/testimonials.html
themes/default/layouts/partials/header.html

Add pulumi AI quote to testimonial page. Update the nav menu a bit to make it more practitioner focused.

update developer testimonials

---

themes/default/layouts/product/pulumi-deployments.html
themes/default/layouts/product/pulumi-insights.html

[See this thread](https://pulumi.slack.com/archives/C7XHM1GNT/p1683490940836959) for context.

Update button labels (Get Started -> Get Started with X)

---

go.mod
go.sum

fix up mod files

---

themes/default/content/docs/intro/insights/import.md

Add Kubernetes section to import page

---

themes/default/theme/src/scss/_search.scss

update tab selected  state  padding to match unselected state.

fix selected tab padding

---

themes/default/layouts/partials/banner.html

Banner updated per https://github.com/pulumi/pulumi-hugo/issues/2811

Update banner to advertise PulumiUP

---

themes/default/data/glossary.toml

last one in hugo

---

themes/default/content/resources/introduction-to-redis-and-pulumi/index.md

This PR lists the redis workshop on the resources page.

List redis workshop on resources page

---

themes/default/layouts/partials/header.html

Update header link to language sdks

---

themes/default/content/blog/aws-lambda-container-support/index.md

Part of https://github.com/pulumi/pulumi-hugo/issues/2790.

Fix buildAndPushImage reference

---

themes/default/content/docs/pulumi-cloud/access-management/saml/_index.md

add missing slash to alias

---

themes/default/content/blog/managing-containers-on-aws-with-pulumi/index.md

Part of https://github.com/pulumi/pulumi-hugo/issues/2790.

Fix buildAndPushImage references

---

themes/default/theme/src/ts/misc.ts

Saw this locally and totally thought it was me. 😂

Remove console.log

---

themes/default/content/blog/gitlab-project-integration/index.md
themes/default/content/docs/concepts/update-plans.md
themes/default/content/docs/pulumi-cloud/access-management/scim/azuread.md
themes/default/content/docs/pulumi-cloud/access-management/scim/okta.md
themes/default/content/docs/pulumi-cloud/access-management/scim/onelogin.md
themes/default/content/docs/pulumi-cloud/self-hosted/_index.md
themes/default/content/docs/using-pulumi/continuous-delivery/gitlab-app.md
themes/default/content/docs/using-pulumi/continuous-delivery/gitlab-ci.md
themes/default/content/docs/using-pulumi/continuous-delivery/octopus-deploy.md
themes/default/content/docs/using-pulumi/continuous-delivery/spinnaker.md
themes/default/content/docs/using-pulumi/crossguard/configuration.md
themes/default/content/docs/using-pulumi/crossguard/faq.md

fix image links

---

themes/default/content/microsoft-build/_index.md
themes/default/content/resources/microsoft-build/index.md
themes/default/layouts/page/microsoft-build.html

https://github.com/pulumi/pulumi-hugo/issues/2862
- Added event to /resources
- Fixed a typo
- Fixed tab title to remove break element
- Meetup URL/CTA changed

updates for microsoft build

---

themes/default/content/docs/reference/_index.md
themes/default/content/docs/reference/pulumi-sdk/_index.md

i added these cause i hit a flurry of errors trying to release the docs nav
now that i think i understand things these are not needed;
will release this tonight, so i can do it when folks arent trying to get things out and confirm all is well

remove unneeded pages

---

themes/default/content/docs/cli/environment-variables.md

fix env var table wrapping

---

themes/default/content/docs/pulumi-cloud/access-management/scim/_index.md
themes/default/content/docs/pulumi-cloud/access-management/scim/azuread.md
themes/default/content/docs/pulumi-cloud/access-management/scim/faq.md
themes/default/content/docs/pulumi-cloud/access-management/scim/okta.md
themes/default/content/docs/pulumi-cloud/access-management/scim/onelogin.md
themes/default/content/docs/pulumi-cloud/deployments/faq.md
themes/default/content/docs/pulumi-cloud/deployments/platform.md
themes/default/content/docs/pulumi-cloud/deployments/reference.md
themes/default/content/docs/pulumi-cloud/deployments/versus.md
themes/default/content/docs/pulumi-cloud/insights/export.md
themes/default/content/docs/pulumi-cloud/insights/import.md
themes/default/content/docs/pulumi-cloud/insights/search.md
themes/default/content/docs/pulumi-cloud/self-hosted/_index.md
themes/default/content/docs/pulumi-cloud/self-hosted/components/api.md
themes/default/content/docs/pulumi-cloud/self-hosted/components/console.md
themes/default/content/docs/pulumi-cloud/self-hosted/deployment-options/aks-hosted.md
themes/default/content/docs/pulumi-cloud/self-hosted/deployment-options/byo-infra-hosted.md
themes/default/content/docs/pulumi-cloud/self-hosted/deployment-options/ecs-hosted.md
themes/default/content/docs/pulumi-cloud/self-hosted/deployment-options/eks-hosted.md
themes/default/content/docs/pulumi-cloud/self-hosted/deployment-options/gke-hosted.md
themes/default/content/docs/pulumi-cloud/self-hosted/deployment-options/local-docker.md
themes/default/content/docs/pulumi-cloud/self-hosted/deployment-options/quickstart-docker-compose.md
themes/default/content/docs/pulumi-cloud/self-hosted/network.md
themes/default/content/docs/pulumi-cloud/self-hosted/saml-sso.md

fixes: https://github.com/pulumi/pulumi-hugo/issues/2878
fix alias property to be aliases in front matter.

fix aliases property in front matter

---

themes/default/content/docs/pulumi-cloud/self-hosted/deployment-options/quickstart-docker-compose.md

fix missing slash in alias

---

themes/default/content/docs/using-pulumi/continuous-delivery/github-app.md

fix redirect

---

themes/default/content/docs/languages-sdks/dotnet/_index.md
themes/default/content/docs/languages-sdks/go/_index.md
themes/default/content/docs/languages-sdks/javascript/_index.md
themes/default/content/docs/languages-sdks/python/_index.md

add identifiers to language files

---

themes/default/content/docs/concepts/_index.md
themes/default/content/docs/install/_index.md
themes/default/content/docs/pulumi-cloud/_index.md

removing some weird icons
fixing some casing on index pages

fixing up a few pieces of content

---

themes/default/layouts/partials/docs/toc.html

open some nav items in new tab

---

themes/default/content/docs/pulumi-cloud/cloud-rest-api/_index.md
themes/default/content/docs/pulumi-cloud/webhooks.md

Update webhooks docs

---

themes/default/content/docs/languages-sdks/java/_index.md
themes/default/content/docs/languages-sdks/yaml/_index.md
themes/default/layouts/partials/docs/toc.html

few more sdk doc fixes

---

themes/default/content/docs/pulumi-cloud/insights/_index.md

this was doing lists within lists; this should fix it up

fix weird markdown on insights page

---

themes/default/content/docs/clouds/azure/get-started/review-project.md

Fixes https://github.com/pulumi/pulumi-hugo/issues/2914

Update Azure getting started ts example to match current

---

BLOGGING.md
themes/default/archetypes/blog-post/index.md
themes/default/content/blog/aws-eks-managed-nodes-fargate/index.md
themes/default/content/blog/embrace-kubernetes-part1/index.md
themes/default/content/blog/kubecon-review/index.md
themes/default/content/blog/managing-containers-on-aws-with-pulumi/index.md
themes/default/content/blog/meals-for-ukraine/index.md
themes/default/content/blog/pulumi-2-0/index.md
themes/default/content/blog/pulumi-is-imperative-declarative-imperative/index.md

remove tweets

---

themes/default/layouts/partials/docs/toc.html

fix sdk dot net docs link

---

themes/default/layouts/partials/docs/toc.html

really fix dotnet sdk docs link

---

themes/default/content/blog/pulumi-and-localstack/index.md

This link seems to have stopped working, so this hopefully works as a replacement.

Fix broken link

---

themes/default/content/docs/languages-sdks/dotnet/_index.md

remove get started mention from dotnet

---

themes/default/theme/src/scss/marketing/_dismissable-banner.scss

fix close x

---

themes/default/content/blog/pulumi-recommended-patterns-the-basics/index.md

Little thing, noticed while testing with search.

Remove quotation marks from meta description

---

themes/default/content/docs/clouds/_index.md

fix up all clouds link

---

themes/default/theme/src/scss/docs/_docs-main.scss

fix layoutz

---

themes/default/theme/src/scss/docs/_docs-main.scss

another layout fix

---

themes/default/theme/src/scss/_search.scss
themes/default/theme/src/scss/docs/_docs-main.scss

layout followups

---

themes/default/theme/src/scss/docs/_docs-main.scss

fix up the table of contents min width

---

themes/default/content/docs/clouds/kubernetes/get-started/_index.md

add missing redirect

---

themes/default/content/docs/clouds/kubernetes/get-started/_index.md

fix kube get started h1

---

themes/default/content/docs/clouds/aws/get-started/_index.md

fiddle with aws get started heading

---

themes/default/content/docs/clouds/aws/get-started/_index.md

add redirect for get started page

---

themes/default/content/docs/clouds/aws/get-started/_index.md
themes/default/content/docs/clouds/azure/get-started/_index.md
themes/default/content/docs/clouds/gcp/get-started/_index.md
themes/default/content/docs/clouds/kubernetes/get-started/_index.md

i forgot to add the redirects for the pages i deleted
this adds them
in case anyone bookmarked them, or they are used in other peoples blogs and thingz

add redirects for get started guides

---

themes/default/content/pulumi-up/_index.md

make keynote 40 minutes, shift all other times up by 20 minutes

---

themes/default/theme/src/scss/docs/_docs-main.scss

fix resource h1 sizes

---

themes/default/content/docs/clouds/aws/_index.md

Add clarity around AWS classic vs native

---

themes/default/content/whitepapers/_index.md

fix extra weird blank whitepapers page

---

themes/default/content/ai/_index.md

Fixes https://github.com/pulumi/pulumi.ai/issues/58

Add a sidebar link to open issues in pulumi-ai repository

---

themes/default/content/docs/pulumi-cloud/deployments/reference.md

- [X ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ na] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [na ] I have manually confirmed that all new links work.
- [na ] I added aliases (i.e., redirects) for all filename changes.
- [ na] If making css changes, I rebuilt the bundle.

Add a note re Github Org member vis for PR preview

---

themes/default/layouts/partials/docs/table-of-contents.html

make edit page link to correct repository

edit this page - links

---

themes/default/layouts/page/pulumi-for-startups.html

text change needed to be applied for all screen sizes

fix text for line wrapping handler

---

themes/default/content/pugs/_index.md
themes/default/layouts/pugs/pugs.html

fixes: https://github.com/pulumi/pulumi-hugo/issues/3001

add redirect for /pugs

---

themes/default/content/docs/clouds/aws/get-started/_index.md
themes/default/content/docs/clouds/azure/get-started/_index.md
themes/default/content/docs/clouds/gcp/get-started/_index.md
themes/default/content/docs/clouds/kubernetes/get-started/_index.md

we are adding a quickstart, so this names the get started thingz tutorials, so there is some naming clarity

---

themes/default/content/docs/install/_index.md

fix bad markdown

---

themes/default/layouts/partials/footer.html

fixes: https://github.com/pulumi/pulumi-hugo/issues/3010

remove url route from footer

---

themes/default/assets/css/marketing.css
themes/default/theme/src/scss/_code.scss

fiddle with type

---

themes/default/theme/src/scss/_code.scss

wrap code in tables

---

themes/default/theme/src/scss/_code.scss

fiddle with table

---

themes/default/content/docs/languages-sdks/yaml/yaml-language-reference.md

fix tables in yaml ref

---

themes/default/content/docs/languages-sdks/java/_index.md

add language to code block

---

themes/default/content/docs/clouds/kubernetes/_index.md
themes/default/layouts/partials/docs/special-pages/cloud-overview.html

fixes https://github.com/pulumi/docs/issues/9071

fix up external links on cloud pages

---

themes/default/content/docs/cli/_index.md
themes/default/content/docs/cli/commands/_index.md

fix some cli links

---

themes/default/theme/src/scss/docs/_docs-home.scss

fixes https://github.com/pulumi/pulumi-hugo/issues/3040

fix a couple docs landing papercuts

---

themes/default/layouts/partials/docs/special-pages/pulumi-quickstart.html

fix k8s template options. remove invalid templates

fix k8s templates options

---

themes/default/content/contact.md

Fixes: https://github.com/pulumi/pulumi-hugo/issues/3046

Add terraform migration form

---

themes/default/layouts/migrate/terraform.html
themes/default/layouts/page/pricing.html

Updating pricing page to add a link for the TF offer

Update pricing page with TF offer

---

themes/default/content/docs/quickstart/_index.md

See https://www.apple.com/macos/

Correctly case macOS: macOs => macOS

---

themes/default/layouts/partials/banner.html
themes/default/theme/src/scss/_header.scss

Homepage banner updated per https://github.com/pulumi/pulumi-hugo/issues/3004
To be merged alongside [this pr](https://github.com/pulumi/pulumi-hugo/pull/3036)

update homepage banner for stacks blog

---

themes/default/content/docs/pulumi-cloud/deployments/faq.md

Removing items we have shipped from the roadmap and editing service requests URL + label.

Update Deploy FAQs

---

themes/default/layouts/page/pulumi-up-2023.html

PulumiUP landing page updated per https://github.com/pulumi/pulumi-hugo/issues/3065

replace event registration modal with airmeet link for PulumiUP

---

.github/CODEOWNERS

Update CODEOWNERS for docs ownership

---

themes/default/content/docs/pulumi-cloud/insights/import.md

Fix capital in title for Cloud Import

---

themes/default/layouts/page/cloud-engineering-summit.html
themes/default/layouts/page/cloud-engineering.html
themes/default/layouts/page/product.html
themes/default/layouts/page/pulumi-up.html
themes/default/layouts/page/solutions.html
themes/default/layouts/page/superpowers.html
themes/default/layouts/page/why-pulumi.html
themes/default/layouts/partials/cta/primary-get-started.html
themes/default/layouts/partials/footer.html
themes/default/layouts/partials/how-pulumi-works.html
themes/default/layouts/partials/sidebar-cta.html
themes/default/layouts/partials/top-nav.html
themes/default/layouts/product/pulumi-cloud.html
themes/default/layouts/shortcodes/get-started-note.html
themes/default/layouts/webinars/cloud-engineering-days-replay.html
themes/default/layouts/webinars/cloud-engineering-summit-replay.html
themes/default/layouts/what-is/single.html

update relrefs to point back to get-started

fix relrefs

---

themes/default/layouts/page/cloud-engineering-summit.html
themes/default/layouts/page/cloud-engineering.html
themes/default/layouts/page/product.html
themes/default/layouts/page/pulumi-up.html
themes/default/layouts/page/solutions.html
themes/default/layouts/page/superpowers.html
themes/default/layouts/page/why-pulumi.html
themes/default/layouts/partials/cta/primary-get-started.html
themes/default/layouts/partials/footer.html
themes/default/layouts/partials/how-pulumi-works.html
themes/default/layouts/partials/sidebar-cta.html
themes/default/layouts/partials/top-nav.html
themes/default/layouts/product/pulumi-cloud.html
themes/default/layouts/shortcodes/get-started-note.html
themes/default/layouts/webinars/cloud-engineering-days-replay.html
themes/default/layouts/webinars/cloud-engineering-summit-replay.html
themes/default/layouts/what-is/single.html

Reverts pulumi/pulumi-hugo#3081

Revert "fix relrefs"

---

themes/default/layouts/page/cloud-engineering-summit.html
themes/default/layouts/page/cloud-engineering.html
themes/default/layouts/page/product.html
themes/default/layouts/page/pulumi-up.html
themes/default/layouts/page/solutions.html
themes/default/layouts/page/superpowers.html
themes/default/layouts/page/why-pulumi.html
themes/default/layouts/partials/cta/primary-get-started.html
themes/default/layouts/partials/footer.html
themes/default/layouts/partials/how-pulumi-works.html
themes/default/layouts/partials/sidebar-cta.html
themes/default/layouts/partials/top-nav.html
themes/default/layouts/product/pulumi-cloud.html
themes/default/layouts/shortcodes/get-started-note.html
themes/default/layouts/webinars/cloud-engineering-days-replay.html
themes/default/layouts/webinars/cloud-engineering-summit-replay.html
themes/default/layouts/what-is/single.html

Reverts pulumi/pulumi-hugo#3082

Revert "Revert "fix relrefs""

---

themes/default/data/team/team/meagan-cojocar.toml

Update my title

---

themes/default/content/docs/clouds/aws/get-started/create-project.md
themes/default/content/docs/clouds/azure/get-started/deploy-changes.md
themes/default/content/docs/clouds/azure/get-started/deploy-stack.md
themes/default/content/docs/clouds/azure/get-started/modify-program.md
themes/default/content/docs/clouds/azure/get-started/review-project.md
themes/default/layouts/shortcodes/configure-gcp.html
themes/default/layouts/shortcodes/console-note.html

Handful of minor fixes after running through these (as it'd been a while):
More to come in a follow up!

A few getting-started fixes

---

themes/default/content/ai/_index.md

This PR adds a disclaimer on the Pulumi AI project that data may be used to improve the results of Pulumi AI in the future
Fixes: https://github.com/pulumi/pulumi-ai/issues/25

Add data disclaimer for pulumi ai

---

themes/default/content/case-studies/menta-network.md

I'm removing this link for now. This page at the url no longer exists and I haven't been able to locate it anywhere else on the web

remove broken link

---

themes/default/theme/src/scss/docs/_docs-main.scss

adding back shadow to registry cards

add shadow to registry package cards

---

themes/default/content/docs/pulumi-cloud/access-management/access-tokens.md

Fix misspelling of Organization

fix:Update access-tokens.md

---

themes/default/content/resources/dash-by-datadog/index.md
themes/default/content/resources/google-next/index.md
themes/default/content/resources/gophercon/index.md
themes/default/content/resources/new-relic-o11y-day/index.md
themes/default/content/resources/platform-engineering-happy-hour/index.md
themes/default/content/resources/wearedevelopers-world-congress/index.md

https://github.com/pulumi/pulumi-hugo/issues/3100

add external workshops/events to resources for 2023 summer

---

themes/default/content/blog/converting-full-terraform-programs-to-pulumi/index.md
themes/default/content/blog/introducing-azure-native-v2/index.md
themes/default/content/blog/property-search/index.md
themes/default/content/blog/review-stacks/index.md
themes/default/content/docs/pulumi-cloud/deployments/review-stacks.md
themes/default/content/docs/pulumi-cloud/insights/_index.md
themes/default/layouts/product/pulumi-insights.html

Adding demo videos of Review Stacks, Property Search, TF conversion, and Azure Native to blogs, docs, and webpages.

Add PulumiUP demo videos to pages

---

.github/workflows/add-to-project.yml
.github/workflows/add-triage-label.yml

Adds automation workflows to post new and reopened issues to the team's project board.

Add issue automation workflows

---

themes/default/theme/src/scss/_api-nodejs.scss

Flex-positions the icon container to fix a vertical-alignment issue.
https://github.com/pulumi/pulumi-hugo/assets/274700/cbacb0f8-a0f2-4f08-bae2-62d2d5c69bd2
Fixes https://github.com/pulumi/registry/issues/2623.

Fix icon alignment

---

themes/default/content/docs/using-pulumi/pulumi-packages/schema.md

Rectify spelling of `availble`

Change spelling of availble to available

---

themes/default/content/blog/introducing-azure-native-v2/index.md

Edit Azure Native 2.0 post to reflect GA

---

themes/default/content/docs/pulumi-cloud/cloud-rest-api/_index.md

Update the API docs to correct resource search cursor query param syntax.

Update API Docs for Resource Search cursor pagination

---

.prettierignore
.prettierrc.json
package.json
themes/default/layouts/crosswalk/kubernetes.html
themes/default/layouts/page/crossguard.html
yarn.lock

Fixes #2576.
Also removes the Prettier plugin that was responsible for this malformatting, and adds a rule to the Prettier config to ignore these files.

Fix formatting issues on the CrossGuard page

---

themes/default/content/blog/introducing-azure-native-v2/index.md

Update migration guide link

---

themes/default/content/resources/azure-github-workshop/index.md

updating the azure github workshop date

update workshop date

---

BLOGGING.md
themes/default/archetypes/blog-post/index.md

Updates the comment of the `date` frontmatter field to clarify that dates have no effect on publishing. Also reflows comments and placeholder text.

Update the blog archetype

---

themes/default/content/docs/pulumi-cloud/self-hosted/deployment-options/local-docker.md

- [X ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [N/A ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [N/A ] I have manually confirmed that all new links work.
- [N/A ] I added aliases (i.e., redirects) for all filename changes.
- [N/A ] If making css changes, I rebuilt the bundle.

update mysql version prereq

---

themes/default/layouts/partials/head.html

Add vwo snippet

---

themes/default/data/team/team/kat-morgan.toml

Update Kat Morgan (usrbinkat) meta
closes #3187

upgrade kat morgan

---

themes/default/content/docs/pulumi-cloud/access-management/access-tokens.md

Add documentation outlining the admin tokens feature.

Admin tokens docs

---

themes/default/content/docs/using-pulumi/automation-api/_index.md

auto api update from website

---

themes/default/content/docs/pulumi-cloud/projects-and-stacks.md

Adding restore stacks docs

---

themes/default/layouts/partials/header.html

Adds an item to the Learn menu point to the What Is ...? index.
Fixes https://github.com/pulumi/devrel-team/issues/611
Reviewers, please feel free to suggest changes to my words -- I'm completely open to adjusting them. 😄

Add What Is to the Learn menu

---

themes/default/content/resources/getting-started-with-1password-and-pulumi/index.md

https://github.com/pulumi/marketing/issues/782

add 1password workshop to resources

---

themes/default/content/resources/kubernetes-platforms-on-google-cloud/index.md

workshop time updated to 8am eastern

update time for kubernetes workshop

---

themes/default/content/docs/clouds/gcp/get-started/deploy-changes.md

Addresses #3171
@scottslowe need you to double check the Java, and Yaml versions. Rest looks ok.

Fixes #3171 (docs)

---

themes/default/content/docs/clouds/aws/guides/eks.md

Fix EKS docs

---

themes/default/content/blog/pulumi-release-notes-80/index.md

No longer works, so unlinking.

Remove bad link

---

themes/default/content/docs/clouds/aws/guides/iam.md

Remove the Sid property (#3215)

Remove the Sid property

---

themes/default/layouts/webinars/single.html

Add prerequisite section to resources pages with signup prompt

add signup text to resources pages

---

themes/default/content/docs/concepts/resources/functions.md

fixes https://github.com/pulumi/pulumi-hugo/issues/3218

Update functions.md for grammar error

---

themes/default/content/resources/getting-started-with-iac-pulumi-aws/index.md

https://github.com/pulumi/marketing/issues/785

add 9/7 workshop to resources

---

themes/default/content/docs/concepts/options/dependson.md

Update dependson.md for go example syntax error

---

themes/default/layouts/page/pricing.html

resolves https://github.com/pulumi/pulumi-hugo/issues/3149

add restore stacks to the pricing page

---

themes/default/content/docs/concepts/vs/terraform/_index.md

Terraform has switched from MPL to BSL https://github.com/hashicorp/terraform/commit/b145fbcaadf0fa7d0e7040eac641d9aef2a26433
https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license

Update Pulumi vs. Terraform with new Terraform license

---

themes/default/content/resources/how-to-start-building-a-self-service-infrastructure-platform-kubernetes/index.md

https://github.com/pulumi/marketing/issues/788

add CNCF on-demand workshop to resources list

---

themes/default/content/docs/clouds/aws/guides/vpc.md

- Added code examples for Go, Java, and YAML. 
- Updated the first Python code example to include missing outputs
- Added info note regarding deploying in regions that support 4+ AZs

Aws vpc guide languages

---

themes/default/content/docs/concepts/secrets.md

Update secrets.md to specify GCP KMS key's required purpose.

---

themes/default/content/blog/pulumi-hearts-opensource/index.md

Adding a quick link to the post

Update pulumi hearts open source blog post

---

themes/default/content/blog/join-pulumi-user-group-community/index.md

Adding Prague to the list and updating the number of groups and countries

Update PUG article to include new meetup in Prague

---

themes/default/content/docs/using-pulumi/adopting-pulumi/_index.md

Adding a checkmark since we support this with cf2pulumi.

Add a checkbox for CloudFormation conversion

---

themes/default/content/docs/pulumi-cloud/deployments/oidc/aws.md

Fix typo in AWS OIDC docs.

---

themes/default/content/docs/concepts/resources/dynamic-providers.md

- [x ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).

Fix a typo in the typescript dynamic provider example

---

themes/default/content/docs/concepts/resources/dynamic-providers.md

See the PR for discussion. My mistake, sorry for the noise.
Reverts pulumi/pulumi-hugo#3279

Revert "Fix a typo in the typescript dynamic provider example"

---

themes/default/content/docs/concepts/resources/dynamic-providers.md

- Fixed tpyo in TypeScript example

docs: Update dynamic-providers.md

---

themes/default/content/pricing/b.md
themes/default/layouts/page/pricing-b.html

This PR adds a "B" version of the pricing page for A/B testing. This version includes updated CTAs to direct people towards the SaaS and renaming "Credits" to "Resource Hours" as to align with the terminology on competitive pricing pages.

Add B version of the pricing page

---

themes/default/layouts/page/pricing-b.html

This PR fixes some links in the "B" version of the pricing page so they point to the correct place 🤦

Fix up links in b version of the pricing page

---

themes/default/content/docs/pulumi-cloud/cloud-rest-api/_index.md
themes/default/content/docs/pulumi-cloud/webhooks.md

Add info for Microsoft Teams webhooks

Add info for Microsoft Teams webhooks

---

themes/default/content/resources/kubernetes-platforms-on-google-cloud/index.md

Fix the workshop time (10am eastern)

fix kubernetes workshop time

---

themes/default/content/docs/using-pulumi/pulumi-packages/schema.md

fixing python npm to PyPi and adding lang selectors

---

themes/default/content/_index.md
themes/default/layouts/index.html

homepage tagline updated per https://github.com/pulumi/pulumi-hugo/issues/3317

update homepage tagline

---

themes/default/content/_index.md

Updates the headline as requested in today's Marketing Meeting.

Update hero headline

---

themes/default/content/blog/announcing-6-0-of-the-pulumi-aws-classic-provider/index.md

Correct release tag link

---

themes/default/content/blog/pulumi-hearts-opensource/index.md

Fixes an issue with showing emojis in Google search results.

Update the title tag of the Pulumi OSS blog post

---

themes/default/content/blog/mlops-the-ai-challenge-is-cloud-not-code/index.md

specify python 3.11+ & fix chatbot URL example

---

themes/default/content/blog/sam-cogan-testing-best-practices/index.md

Update index.md - setting to draft for edits

---

themes/default/content/docs/languages-sdks/go/_index.md
themes/default/content/docs/languages-sdks/java/_index.md
themes/default/content/docs/languages-sdks/javascript/_index.md
themes/default/content/docs/languages-sdks/python/_index.md

This PR adds language aliases for a couple of languages that did not have aliases. Additionally, the PR adds a few aliases for greater consistency across the languages.

Standardize language aliases

---

themes/default/content/resources/platform-with-aws-proton-and-pulumi/index.md

https://github.com/pulumi/marketing/issues/796
awaiting time confirmation before merging

add october 12 AWS Proton workshop to resources

---

themes/default/layouts/_default/baseof.html

https://github.com/pulumi/marketing/issues/795

add propensity tracking script to website

---

themes/default/content/docs/pulumi-cloud/deployments/reference.md

Add versioning policy for Pulumi Deployments default container

Add pulumi-docker-containers versioning policy

---

themes/default/content/blog/mlops-huggingface-llm-aws-sagemaker-python/index.md

blog tweaks

---

themes/default/content/docs/clouds/kubernetes/get-started/review-project-b.md
themes/default/content/docs/clouds/kubernetes/get-started/review-project.md

Fix Kubernetes Go snippet

---

themes/default/content/docs/clouds/azure/get-started/review-project-b.md
themes/default/content/docs/clouds/azure/get-started/review-project.md

Fix Azure Go references

---

themes/default/content/resources/build-web-scale-cloud-app-golang-iac/index.md

https://github.com/pulumi/marketing/issues/797

add golang iac workshop to resources

---

themes/default/content/what-is/what-is-devops-automation.md

Initial draft of what is devops automation

Initial draft of what is devops automation

---

themes/default/content/docs/concepts/vs/terraform/_index.md

Update TFvsPulumi with SEO recommendation

---

themes/default/layouts/partials/learnmore-ai.html

fix relref

---

themes/default/content/docs/pulumi-cloud/deployments/reference.md

Update Deployment limitations

---

themes/default/content/docs/concepts/options/_index.md
themes/default/content/docs/concepts/options/deletedwith.md
themes/default/content/docs/concepts/options/dependson.md
themes/default/content/docs/concepts/options/ignorechanges.md
themes/default/content/docs/concepts/options/import.md
themes/default/content/docs/concepts/options/parent.md
themes/default/content/docs/concepts/options/protect.md
themes/default/content/docs/concepts/options/provider.md
themes/default/content/docs/concepts/options/providers.md
themes/default/content/docs/concepts/options/replaceonchanges.md
themes/default/content/docs/concepts/options/retainOnDelete.md
themes/default/content/docs/concepts/options/transformations.md

Add docs per https://github.com/pulumi/pulumi-hugo/issues/2401

Add deletedWith documentation

---

themes/default/content/_index.md
themes/default/content/contact.md
themes/default/content/docs/support/troubleshooting.md
themes/default/content/enterprise/_index.md
themes/default/content/product/self-hosted.md
themes/default/content/show/_index.md
themes/default/content/topics/containers.md
themes/default/content/topics/serverless.md
themes/default/layouts/migrate/terraform.html
themes/default/layouts/page/crosscode.html
themes/default/layouts/partials/footer.html
themes/default/layouts/partials/learnmore-contactus.html
themes/default/layouts/product/self-hosted.html
themes/default/layouts/security/section.html
themes/default/layouts/whitepapers/single.html

This PR updates the Contact Us messaging from "Contact Us" -> "Talk to a human".
It also removes a few `relref`s I can across while updating the text.

Update the "contact us" messaging

---

themes/default/layouts/partials/header.html

Adding pulumi AI Answers to Nav

adding ai/answers to site nav

---

themes/default/content/docs/using-pulumi/crossguard/_index.md

- pulumi.com/policy-as-code that goes to https://www.pulumi.com/docs/using-pulumi/crossguard/
Relates to https://github.com/pulumi/marketing/issues/798

Aliases for marketing content usage

---

themes/default/content/partner/azure.md
themes/default/layouts/page/product-packages.html
themes/default/layouts/partials/header.html
themes/default/layouts/partner/aws.html
themes/default/layouts/partner/azure.html
themes/default/layouts/partner/gcp.html
themes/default/layouts/shortcodes/aws-eks-prereqs.html
themes/default/layouts/shortcodes/aws-js-prereqs.html
themes/default/layouts/shortcodes/azure-aks-prereqs.html
themes/default/layouts/shortcodes/install-pulumi.html
themes/default/layouts/shortcodes/multilang-tutorial-prereqs.html

I need to remove registry relrefs in order to stop importing the hugo module into docs since it is causing relref errors.  I also fixed up a few more while I was in the area.

Remove registry relrefs

---

themes/default/content/resources/friend-or-foe-ai-devops-developers/index.md
themes/default/content/resources/generative-ai-apps-devops/index.md

Hey Sara here is the PR I opened with the clones files and you can edit them here how you want. For each new URL you can see it by the name of the folder they are in.

clone gophercon workshops

---

themes/default/content/docs/concepts/inputs-outputs/_index.md

fix go code for ApplyT examples

---

themes/default/content/blog/2022-03-31-go-generics-with-pulumi/index.md

Add outdated warning and link for Go Generics

---

themes/default/layouts/page/pulumi-up.html

I'm removing this large mp4 since our module size is hitting the limit again and need to unblock the pipelines. I relocated this file to the uploads bucket and can be accessed via pulumi.com/uploads. I also update the ref.
I am going to YOLO this through so we can unblock.

remove large mp4

---

themes/default/content/resources/build-web-scale-cloud-app-golang-iac/index.md

fixing property name for meta image

Fix meta image property name

---

README.md

Updates the Merging and Releasing section to reflect recent changes to the pipeline.

Update the Releasing section of the README

---

themes/default/content/blog/kubecon-review/index.md
themes/default/content/blog/kubernetes-server-side-apply/index.md
themes/default/content/blog/pulumi-deployments/index.md
themes/default/content/blog/pulumi-insights-ai-cli/index.md
themes/default/content/blog/pulumi-recommended-patterns-the-basics/index.md
themes/default/content/blog/pulumi-service-improvements_02-2020/index.md
themes/default/content/challenge/deployments.md
themes/default/content/docs/using-pulumi/continuous-delivery/spinnaker.md

We moved several large files in #3447 and missed a few references. This should fix 'em up.

Fix broken links

---

themes/default/layouts/partials/header.html

Fixing the missing icon and description

fixing nav for ESC

---

themes/default/content/docs/pulumi-cloud/esc/get-started/_index.md

A PR to fix some initial issues
- Fixed link to OIDC doc
- Separated Pulumi account and access token URLs
- Updated cleanup section to accommodate for deletion of stacks with unique stack names
- Updated stack Outputs examples to include StackName output

Update ESC Get Started _index.md

---

themes/default/content/blog/environments-secrets-configurations-management/index.md

Very minor edits to the ESC blog post

---

themes/default/content/docs/pulumi-cloud/esc/get-started/_index.md

For the bash scripts, added a line of code to change the permissions of the script so that the user can run it.

Added script permission change code

---

themes/default/content/blog/environments-secrets-configurations-management/index.md

Intro ESC blog, add link to product page 

---

themes/default/content/docs/pulumi-cloud/esc/get-started/_index.md

Removed sourcing periods from the shell script executions

Removed sourcing periods

---

themes/default/content/product/_index.md
themes/default/content/product/esc.md
themes/default/layouts/partials/banner.html
themes/default/layouts/product/esc.html

changing instances of Configurations and configurations to align product name : Pulumi ESC (Environments, Secrets and Configuration)

fixing configuration(s) terms

---

themes/default/layouts/partials/header.html

Fixing the missing icon from nav from tonights launch

Nav: 10_11 fixing missing icon

---

themes/default/layouts/product/esc.html

ESC product page: fixing github links

---

themes/default/content/blog/developer-portal-platform-teams/index.md

fixing the link to the backstage blog

Platform Teams blog link fix

---

themes/default/content/product/esc.md

Correcting the description for this card on the product page

ESC Product Page: fixing description for versionable card

---

themes/default/content/resources/securing-deployments-policy-as-code/index.md

https://github.com/pulumi/marketing/issues/799

add workshop for policy as code on aws nov 2

---

themes/default/content/blog/developer-portal-platform-teams/index.md

Platform teams blog typo 

---

themes/default/content/docs/pulumi-cloud/esc/environments.md

Fixes a few issues encountered while working through the examples on this page. Still a few things left to take care of, but wanted to get this in before adjourning for the day.

Fix a few typos in the ESC environments doc

---

themes/default/content/docs/pulumi-cloud/esc/get-started/_index.md

Added content about logging into the esc cli and how users will be prompted. Also marked the `Access token` prereq as optional.

Add 'esc login' steps

---

themes/default/content/docs/support/troubleshooting.md

Updating from 9 to 10, as 10 gathers everything

---

themes/default/layouts/partials/footer.html

Adds the newsletter form to the footer.

Add newsletter form to footer

---

themes/default/content/docs/using-pulumi/adopting-pulumi/migrating-to-pulumi/from-terraform.md

Replacement for the state documentation we removed in https://github.com/pulumi/pulumi-hugo/pull/3281.

Readd terraform state documentation

---

themes/default/layouts/index.html

Adds the product hunt badge for ESC

Add product hunt badge

---

themes/default/content/blog/post-mortem-2023-10-06/index.md

Update Postmortem Blog Post Date

---

themes/default/content/learn/building-with-pulumi/stack-outputs/index.md

This PR will resolve [#10088](https://github.com/pulumi/docs/issues/10088)

Make pulumi up command more visible

---

themes/default/content/blog/remediation-policies/index.md

Change policy remediations blog post date

---

themes/default/content/resources/from-zero-to-production-in-kubernetes/index.md
themes/default/content/resources/getting-started-with-iac-pulumi-aws/index.md
themes/default/content/resources/getting-started-with-kubernetes-aws/index.md
themes/default/content/resources/getting-started-with-secrets-management-aws/index.md
themes/default/content/resources/intro-to-aws-typescript/index.md

https://github.com/pulumi/marketing/issues/808
https://github.com/pulumi/marketing/issues/809
https://github.com/pulumi/marketing/issues/815
https://github.com/pulumi/marketing/issues/813
https://github.com/pulumi/marketing/issues/817

Workshops for November/December

---

themes/default/content/docs/pulumi-cloud/esc/providers/aws-login.md

Update details on AWS Login Duration

---

themes/default/content/docs/clouds/aws/guides/cloudwatch.md

Updates aws cloudwatch example code in the guide

---

themes/default/content/testimonials/_index.md

Edit developer quote

---

themes/default/content/docs/using-pulumi/adopting-pulumi/import.md

Add clarity to Pulumi import command

---

themes/default/content/docs/using-pulumi/adopting-pulumi/import.md

Suggestion submitted here: https://github.com/pulumi/pulumi-hugo/pull/3536#discussion_r1372253927, but the PR was auto-merged before it could be considered/applied.

Apply suggestion from merged PR

---

themes/default/content/kubecon/_index.md

Adding GitLab to the list for the Happy Hour

---

themes/default/layouts/partials/docs/right-nav-ad.html

fixes: https://github.com/pulumi/marketing/issues/831

update ad to pulumi ai

---

themes/default/data/awards.toml

removed 404s from 3rd party links

---

themes/default/layouts/partials/banner.html

Fixes https://github.com/pulumi/marketing/issues/833

Update banner for kubecon

---

themes/default/layouts/partials/customer-logos/docker.html

Fixes https://github.com/pulumi/marketing/issues/834

Fix docker logo

---

themes/default/content/docs/pulumi-cloud/esc/providers/_index.md
themes/default/content/docs/pulumi-cloud/oidc/_index.md

Update ESC Provider page to link to the OIDC hub page. Also a small typo fix on the OIDC hub page

Update ESC Provider Page

---

themes/default/content/docs/pulumi-cloud/deployments/_index.md

Added a link on the Deployments hub page to reference the new OIDC hub page.

Added oidc link to deployments page

---

themes/default/content/templates/serverless-application/aws/index.md

Fix a malformed link

---

themes/default/content/docs/pulumi-cloud/oidc/aws.md

This PR updates some incorrect text and updates the ESC environment YAML example include the AWS environment variables.

Small update to AWS OIDC content

---

themes/default/content/docs/clouds/gcp/get-started/next-steps.md

My bad -- I just assumed this tag existed in #3578.

Fix a bad link

---

themes/default/content/docs/languages-sdks/javascript/_index.md
themes/default/content/docs/pulumi-cloud/esc/environments.md

[Fixes these](https://pulumi.slack.com/archives/C04LH6RQZHT/p1699461351901229).

Fix a couple of broken links

---

themes/default/content/resources/serverless-apps-with-google-cloud-run-and-pulumi/index.md

https://github.com/pulumi/marketing/issues/842

add 11/30 Google Cloud workshop to resources

---

themes/default/content/docs/pulumi-cloud/esc/_index.md

Ref: https://github.com/pulumi/home/issues/3190

Add an alias for /docs/esc

---

themes/default/layouts/partials/banner.html

https://github.com/pulumi/marketing/issues/843

update homepage banner for re:invent

---

themes/default/content/blog/google-cloud-7-0/index.md

Update registry link in gcp blog post

---

themes/default/content/blog/google-cloud-7-0/index.md

Add workshop note on gcp blog

---

themes/default/content/docs/clouds/aws/guides/ecs.md

- Page https://www.pulumi.com/docs/clouds/aws/guides/ecs/
- Updates the imports and golang code so that the ECS examples work. This was tested by creating pulumi programs for each. And, running  `pulumi new` / `pulumi destroy` successfully.
- Fixes #3430 
- All Go examples were updated and tested. These are currently found in [this repo](https://github.com/desteves/pulumi-hugo-iss3430/tree/main)

Fixes AWS ECS Guide Go examples

---

themes/default/layouts/partials/hero.html
themes/default/layouts/what-is/single.html

This PR avoids setting the title in the hero as an h2 as this causes so SEO issues.

Fix up hero h2

---

themes/default/content/what-is/what-is-configuration-management.md

This PR adds a "What is" page that defines and discusses configuration management.

Add "What is configuration management" page

---

themes/default/content/what-is/what-are-docker-secrets.md

This update adds the missing steps to initialize a Docker swarm on the Docker Secrets SEO page and some small content edits.

Add missing swarm step

---

themes/default/content/what-is/what-are-kubernetes-secrets.md

This PR adds a "What is" page that defines and discusses Kubernetes Secrets.
Page: /what-is/what-are-kubernetes-secrets/

Add "What are Kubernetes Secrets" SEO Page

---

themes/default/content/what-is/what-are-docker-secrets.md

This PR adds a best practices section to the page content. It also fixes a small typo.

Added best practices section

---

themes/default/content/reinvent/_index.md

ReInvent page, update the secrets page to December 13

ReInvent page: Updating workshop date

---

themes/default/content/what-is/what-are-kubernetes-secrets.md

The referenced SEO page for secrets management is not yet available, so we are currently removing the link.

rm link in k8s secret page

---

themes/default/content/docs/pulumi-cloud/esc/providers/_index.md
themes/default/content/docs/pulumi-cloud/esc/providers/aws-login.md
themes/default/content/docs/pulumi-cloud/esc/providers/pulumi-stacks.md
themes/default/content/docs/pulumi-cloud/esc/providers/vault-login.md
themes/default/content/docs/pulumi-cloud/esc/providers/vault-secrets.md

Add pulumi-stacks provider docs

---

themes/default/content/what-is/what-is-infrastructure-as-code.md

This PR enforces sentence case per style guide and fixes a couple other inconsistencies with other pages.

Minor fixes to What is IaC page

---

themes/default/content/what-is/what-is-hashicorp-vault.md

This PR adds content on what is hashicorp vault to the "What Is" section of the website.

[WIP] Add "What is HashiCorp Vault" SEO page

---

themes/default/content/resources/ai-apps-to-production/index.md

DO NOT MERGE: I still need to get the hubspot form id before we can ship this.
Add AI apps workshop.

Add ai apps workshop

---

themes/default/content/resources/ai-apps-to-production/index.md

Added Pinecone speaker to the workshop

Added speaker

---

themes/default/content/what-is/what-is-secrets-management.md

This PR adds content on secrets management to the "What Is" section of the website.

Add "What is Secrets Management" SEO page

---

themes/default/content/what-is/what-is-hashicorp-vault.md

fixing typo to hashicorp page

---

themes/default/content/docs/get-started/_index.md

This PR adds more descriptive text to the video section so that it is clearer to users that the video is an alternative way to learn about Pulumi at a high level.
Fixes [this issue](https://github.com/pulumi/docs/issues/9844).

Add more descriptive text to video section

---

themes/default/content/b.md
themes/default/layouts/page/home-b.html

This updates the hero tagline on the home page on the "B" version.

Update home page b version hero

---

themes/default/content/docs/concepts/projects/project-file.md

Document `main` for the various languages

---

themes/default/content/docs/concepts/projects/project-file.md

For python if main is set we'll pass that to the python interpreter.

Update docs on main for python

---

themes/default/content/docs/pulumi-cloud/esc/reference.md
themes/default/data/team/team/arun-loganathan.toml

incorporated suggested changes from the previous PR (https://github.com/pulumi/pulumi-hugo/pull/3681)
Previous PR was merged without the suggested changes.

formatting changes to align with rest of the md

---

themes/default/layouts/partials/banner.html

Hide top banner

---

themes/default/content/docs/pulumi-cloud/esc/faq.md
themes/default/content/docs/pulumi-cloud/esc/providers/_index.md

Added ESC FAQs

---

themes/default/static/programs/aws-ec2-instance-with-sg-go/go.mod.txt

Fix an example test

---

themes/default/static/programs/aws-ec2-instance-with-sg-go/go.mod.txt
themes/default/static/programs/aws-eks-cluster-go/go.mod.txt
themes/default/static/programs/awsx-ecr-eks-deployment-service-go/go.mod.txt
themes/default/static/programs/awsx-ecr-image-go/go.mod.txt
themes/default/static/programs/awsx-ecr-repository-go/go.mod.txt
themes/default/static/programs/awsx-elb-multi-listener-redirect-go/go.mod.txt
themes/default/static/programs/awsx-elb-private-subnet-go/go.mod.txt
themes/default/static/programs/awsx-elb-vpc-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-ec2-instances-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-fargate-ecr-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-fargate-nginx-go/go.mod.txt
themes/default/static/programs/awsx-vpc-azs-go/go.mod.txt
themes/default/static/programs/awsx-vpc-cidr-go/go.mod.txt
themes/default/static/programs/awsx-vpc-default-go/go.mod.txt
themes/default/static/programs/awsx-vpc-fargate-service-go/go.mod.txt
themes/default/static/programs/awsx-vpc-go/go.mod.txt
themes/default/static/programs/awsx-vpc-nat-gateways-go/go.mod.txt
themes/default/static/programs/awsx-vpc-security-groups-go/go.mod.txt
themes/default/static/programs/awsx-vpc-sg-ec2-go/go.mod.txt
themes/default/static/programs/awsx-vpc-subnets-go/go.mod.txt

Fixes https://github.com/pulumi/pulumi-hugo-private/issues/186 
Updates go mod dependencies in the go examples to match.

Update go mods for examples

---

themes/default/content/learn/embedding-pulumi/getting-started/index.md

Noticed the filename was wrong here while going through the steps.

Fix filename

---

themes/default/layouts/page/pulumi-for-startups.html

Issue: https://github.com/pulumi/marketing/issues/884
Update startup offer page.

update pulumi startup offer page

---

themes/default/content/docs/pulumi-cloud/access-management/access-tokens.md

Fixes: https://github.com/pulumi/pulumi-pulumiservice/issues/188

Fix access management docs for webhooks

---

themes/default/layouts/partials/example-program.html
themes/default/static/programs/aws-eks-cluster-go/go.mod.txt
themes/default/static/programs/awsx-ecr-eks-deployment-service-go/go.mod.txt
themes/default/static/programs/awsx-ecr-image-go/go.mod.txt
themes/default/static/programs/awsx-ecr-repository-go/go.mod.txt
themes/default/static/programs/awsx-elb-multi-listener-redirect-go/go.mod.txt
themes/default/static/programs/awsx-elb-private-subnet-go/go.mod.txt
themes/default/static/programs/awsx-elb-vpc-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-ec2-instances-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-fargate-ecr-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-fargate-nginx-go/go.mod.txt
themes/default/static/programs/awsx-vpc-azs-go/go.mod.txt
themes/default/static/programs/awsx-vpc-cidr-go/go.mod.txt
themes/default/static/programs/awsx-vpc-default-go/go.mod.txt
themes/default/static/programs/awsx-vpc-fargate-service-go/go.mod.txt
themes/default/static/programs/awsx-vpc-go/go.mod.txt
themes/default/static/programs/awsx-vpc-nat-gateways-go/go.mod.txt
themes/default/static/programs/awsx-vpc-security-groups-go/go.mod.txt
themes/default/static/programs/awsx-vpc-sg-ec2-go/go.mod.txt
themes/default/static/programs/awsx-vpc-subnets-go/go.mod.txt

The config value for the branch name is not resolving in production leading to 404s. This PR hard codes the branch name in to resolve the 404s.

Hardcode branch name for code examples

---

themes/default/layouts/partials/example-program.html
themes/default/static/programs/aws-eks-cluster-go/go.mod.txt
themes/default/static/programs/awsx-ecr-eks-deployment-service-go/go.mod.txt
themes/default/static/programs/awsx-ecr-image-go/go.mod.txt
themes/default/static/programs/awsx-ecr-repository-go/go.mod.txt
themes/default/static/programs/awsx-elb-multi-listener-redirect-go/go.mod.txt
themes/default/static/programs/awsx-elb-private-subnet-go/go.mod.txt
themes/default/static/programs/awsx-elb-vpc-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-ec2-instances-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-fargate-ecr-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-fargate-nginx-go/go.mod.txt
themes/default/static/programs/awsx-vpc-azs-go/go.mod.txt
themes/default/static/programs/awsx-vpc-cidr-go/go.mod.txt
themes/default/static/programs/awsx-vpc-default-go/go.mod.txt
themes/default/static/programs/awsx-vpc-fargate-service-go/go.mod.txt
themes/default/static/programs/awsx-vpc-go/go.mod.txt
themes/default/static/programs/awsx-vpc-nat-gateways-go/go.mod.txt
themes/default/static/programs/awsx-vpc-security-groups-go/go.mod.txt
themes/default/static/programs/awsx-vpc-sg-ec2-go/go.mod.txt
themes/default/static/programs/awsx-vpc-subnets-go/go.mod.txt

Reverts pulumi/pulumi-hugo#3777

Revert "Hardcode branch name for code examples"

---

themes/default/layouts/partials/example-program.html

Hardcode branch name in github link

---

themes/default/content/what-is/run-aws-cloudwatch-get-metric-data-with-dynamic-credentials.md
themes/default/content/what-is/run-aws-dynamodb-list-tables-with-dynamic-credentials.md
themes/default/content/what-is/run-aws-ec2-describe-instances-with-dynamic-credentials.md
themes/default/content/what-is/run-aws-ec2-start-instances-with-dynamic-credentials.md
themes/default/content/what-is/run-aws-ec2-stop-instances-with-dynamic-credentials.md
themes/default/content/what-is/run-aws-iam-list-users-with-dynamic-credentials.md
themes/default/content/what-is/run-aws-lambda-list-functions-with-dynamic-credentials.md
themes/default/content/what-is/run-aws-s3-cp-with-dynamic-credentials.md
themes/default/content/what-is/run-aws-s3-ls-with-dynamic-credentials.md
themes/default/content/what-is/run-aws-s3-sync-with-dynamic-credentials.md
themes/default/content/what-is/run-aws-sts-get-caller-identity-with-dynamic-credentials.md
themes/default/layouts/what-is/single.html

minor updates to aws pages

---

themes/default/layouts/page/ai-solutions.html

Fixes: https://github.com/pulumi/marketing/issues/921

Update solutions page

---

themes/default/content/docs/languages-sdks/javascript/_index.md

Document impact of having different versions of a provider in the Node dependency graph

Document impact of having different versions of a provider in the Node dependency graph

---

themes/default/content/blog/using-terraform-remote-state-with-pulumi/index.md
themes/default/content/what-is/what-is-a-github-action-secret.md
themes/default/layouts/product/internal-developer-platforms.html

typo + link fixes

---

scripts/content/new-example-program.sh
scripts/serve.sh

Includes the script containing certain Bash functions required for local authoring.

Add missing script to serve.sh

---

.github/workflows/scheduled-upgrade-programs.yml

Fixes #3799.
Fixes https://github.com/pulumi/pulumi-hugo-private/issues/191.

Add AWS creds to fix failing test

---

themes/default/content/docs/concepts/stack.md

fixes typescript stack ref example

---

themes/default/content/resources/scaling-ai-apps/index.md

Updating host to Engin.
Waiting confirmation on Pinecone's host

Update Scaling AI apps hosts/presenters

---

themes/default/content/docs/clouds/kubernetes/get-started/_index.md

This PR fixes the page title of the K8s Get Started page.
Fixes [this issue](https://github.com/pulumi/pulumi-hugo/issues/3816).

Fixes K8s Get Started Page Title

---

themes/default/content/docs/concepts/resources/_index.md

This PR corrects the section descriptions on the resource page.
Fixes [this issue](https://github.com/pulumi/docs/issues/10529).

Provide correct section descriptions

---

themes/default/content/_index.md
themes/default/layouts/index.html

Moves the b version of the A/B test to be the main home page.

Update home page to b version

---

themes/default/layouts/page/pricing-b.html
themes/default/layouts/page/pricing.html

Specify GitHub Enterprise Server on Pricing page

---

themes/default/layouts/partials/head.html

Add clearbit snippet

---

themes/default/content/docs/concepts/glossary.md

Fix typo in glossary.md

---

themes/default/layouts/_default/baseof.html

Fixes https://github.com/pulumi/marketing/issues/940

Remove propensity tag

---

README.md

Fixes the link target for Code of Conduct in the README.
Fixes #3845

fix(docs): update code-of-conduct link

---

themes/default/content/blog/managing-secrets-with-pulumi/index.md

updating managing secrets with Pulumi Blog 

---

themes/default/content/resources/scaling-ai-apps/index.md

- add pinecone presenter
- remove a paragraph from the workshop description per @dirien

Update Scaling AI Apps workshop

---

LICENSE
package.json

Part of https://github.com/pulumi/docs/issues/10649.

Add a LICENSE file

---

themes/default/content/docs/concepts/secrets.md

Fixes #950 (and includes a bit of tidying up of the intro section, headings, and usage of `plaintext`).

Add version control section to the secrets docs

---

themes/default/content/docs/concepts/projects/_index.md
themes/default/content/docs/concepts/projects/project-file.md
themes/default/layouts/shortcodes/pulumi-getproject.html

Fixes #1436, and also does a bit of cleanup, bug fixing, and filling out of a few missing details.

Fix missing Go reference, other issues in the project docs

---

themes/default/content/resources/scaling-ai-apps/index.md

Add Scaling AI apps workshop video to resources
https://www.youtube.com/watch?v=D0cOJNf0pCQ&feature=youtu.be

Add Scaling AI apps workshop video to resources

---

themes/default/content/docs/esc/reference.md

* Add note about ciphertext on fn::secret
* Add example for fn::fromBase64

Update ESC syntax reference

---

themes/default/content/docs/using-pulumi/adopting-pulumi/import.md

Update bulk import docs for some of the recent improvements.
Part of https://github.com/pulumi/pulumi/issues/14510
Going to mention these improvements in https://github.com/pulumi/pulumi-hugo/pull/3865. Will follow-up with a larger blog post (and perhaps more doc updates) subsequently.

Initial import doc updates

---

themes/default/content/blog/pulumi-release-notes-99/index.md

fixing broken links

---

themes/default/content/_index.md
themes/default/layouts/partials/head.html

Fixes: https://github.com/pulumi/marketing/issues/865

Add organization search schema to homepage

---

themes/default/content/docs/pulumi-cloud/audit-logs.md

Add new env audit logs

---

themes/default/content/docs/clouds/aws/get-started/begin.md

Mention AWS profiles in the getting-started guide

---

themes/default/content/docs/using-pulumi/define-and-provision-resources/index.md

One of the code examples earlier in the guide included a line that it shouldn't have. This PR corrects the line numbers.

Fixed the line numbers for code inject

---

themes/default/content/_index.md
themes/default/layouts/index.html

Update homepage headline

---

themes/default/content/docs/using-pulumi/adopting-pulumi/converters.md

addressing https://github.com/pulumi/docs/issues/9563 and the start to other improvements to our conversion tool docs

refactoring the convert code to pulumi page

---

themes/default/content/docs/pulumi-cloud/self-hosted/components/api.md

Update api.md with correct version of MySQL

---

themes/default/content/blog/the-present-and-future-of-ai-and-iac/index.md

changed infrastructrure  to infrastructure

fix: a typo

---

themes/default/layouts/page/ai-solutions.html

uniform logo heights on ai solutions page

make logos a uniform height on ai solutions page

---

themes/default/content/docs/esc/environments.md
themes/default/content/docs/esc/providers/aws-login.md
themes/default/content/docs/esc/providers/azure-login.md
themes/default/content/docs/esc/providers/gcp-login.md
themes/default/content/docs/esc/providers/vault-login.md
themes/default/content/docs/esc/reference.md
themes/default/content/docs/pulumi-cloud/oidc/aws.md
themes/default/content/docs/pulumi-cloud/oidc/azure.md
themes/default/content/docs/pulumi-cloud/oidc/gcp.md
themes/default/content/docs/pulumi-cloud/oidc/vault/_index.md

Add docs of new ESC context interpolation and subject customization
https://github.com/pulumi/pulumi-service/issues/15758

Add ESC context docs

---

themes/default/content/blog/software-developer-experience-devex-devx-devops-culture/index.md

Correcting how DevEx shows to be consistent

Blog: DevEx - minor corrections

---

themes/default/content/docs/pulumi-cloud/deployments/reference.md

Fixes: https://github.com/pulumi/docs/issues/10865

Document deployment permissions

---

themes/default/layouts/_default/baseof.html
themes/default/layouts/partials/footer.html
themes/default/layouts/partials/head.html
themes/default/static/programs/aws-import-export-pulumi-config-go/go.mod.txt
themes/default/theme/src/scss/main.scss

Fixes: https://github.com/pulumi/marketing/issues/935

Add segment consent form

---

themes/default/layouts/partials/head.html

Fix segment load script

---

themes/default/layouts/page/pricing.html

TF Migration Edits

---

themes/default/content/docs/concepts/projects/project-file.md

fixes https://github.com/pulumi/pulumi-hugo/issues/2508.
Adds links to the project concepts page and clarity on Pulumi programs written in Pulumi YAML

adding suggestions to the project file page

---

themes/default/content/blog/migration-hub/index.md

Remove a relref to unblock the website build: https://github.com/pulumi/docs/actions/runs/8076715071/job/22065631439?pr=10896#step:9:73

Remove relref

---

themes/default/layouts/index.html
themes/default/layouts/page/home-b.html

Correct typo on home page

---

themes/default/content/resources/getting-started-with-spot-netapp-and-pulumi/index.md

The workshop will no longer happen

Workshop: unlisted = true for Spot by NetApp workshop

---

themes/default/content/docs/cli/environment-variables.md

Documentation about lesser-known environment variables

Add PULUMI_EXPERIMENTAL and PULUMI_SKIP_CHECKPOINTS to documentation about environment variables

---

.github/workflows/pull-request.yml
.github/workflows/push.yml

Upgrade Go to 1.21 in CI

---

themes/default/content/product/pulumi-deployments.md

Redirects to https://www.pulumi.com/product/pulumi-deployments/.

Add an alias for /deployments

---

themes/default/content/resources/developer-infrastructure-with-pulumi-and-okteto/index.md
themes/default/content/resources/whats-new-pulumi-cloud/index.md

- Add What's New to Pulumi video
- Add Okteto's workshop video

[Workshops] add on-demand video to resources

---

themes/default/content/docs/concepts/vs/_index.md
themes/default/content/docs/concepts/vs/opentofu.md
themes/default/content/docs/concepts/vs/terraform/_index.md
themes/default/content/docs/concepts/vs/terraform/opentofu.md

Just adding in a vs page for OpenTofu but also added a TF vs OpenTofu page to capture SEO

Adding OpenTofu to docs

---

themes/default/content/docs/pulumi-cloud/projects-and-stacks.md

Fixes : https://github.com/pulumi/docs/issues/9512
adding metadata to make finding how to delete a stack easier

adding search metadata for delete stack

---

themes/default/content/resources/developer-infrastructure-with-pulumi-and-okteto/index.md

Set to Unlisted workshop

---

.github/workflows/scheduled-test.yml
.github/workflows/scheduled-upgrade-programs.yml
themes/default/static/programs/awsx-ecr-eks-deployment-service-go/go.mod.txt
themes/default/static/programs/awsx-ecr-image-go/go.mod.txt
themes/default/static/programs/awsx-ecr-repository-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-fargate-ecr-go/go.mod.txt
themes/default/static/programs/awsx-load-balanced-fargate-nginx-go/go.mod.txt
themes/default/static/programs/awsx-vpc-fargate-service-go/go.mod.txt

Bump Go to 1.21 in CI

---

themes/default/content/blog/international-women-day-celebrating-women-in-tech/index.md

Updating article

---

themes/default/content/docs/esc/reference.md

- Document field usage
- Document new namespace option for Vault Enterprise

Update ESC vault syntax reference

---

themes/default/content/docs/esc/providers/vault-login.md
themes/default/content/docs/esc/providers/vault-secrets.md

Adds documentation for the feature added to address https://github.com/pulumi/esc/issues/142.

Add documentation for `namespace` for Vault Enterprise

---

themes/default/content/docs/using-pulumi/testing/unit.md

This PR adds additional packages to the csharp section to ensure users have them installed.

Added Pulumi packages

---

themes/default/static/programs/aws-ec2-sg-nginx-server-javascript/index.js

Looks like this one just didn't get fleshed out with the others alongside it. This should fix it up.

Fix aws-ec2-sg-nginx-server-javascript example

---

themes/default/content/blog/aws-lambda-response-streaming/index.md
themes/default/data/awards.toml

This PR fixes a few of the docs ops links.

Fix docs-ops links

---

themes/default/content/community/community-engineering/engin-diri.md
themes/default/content/community/community-engineering/kat-morgan.md
themes/default/data/team/team/kat-morgan.toml
themes/default/layouts/community/community-engineering/single.html

Adding community engineer pages for use as CTA after talks

Add community engineer pages

---

themes/default/layouts/community/community-engineering/single.html

Remove time from community engineers page.

Remove time from community engineers page

---

themes/default/layouts/partials/docs/main-nav.html

Like we did for Python, open Node SDK docs in a new tab https://github.com/pulumi/pulumi-hugo/pull/3754
To be merged after https://github.com/pulumi/docs/pull/10964

Open NodeJS SDK docs in a new tab

---

themes/default/content/docs/pulumi-cloud/oidc/vault/_index.md

This PR updates the vault configuration example to include namespaces which is now supported for Vault Enterprise. It also removes the previous note that stated namespaces is not supported.

Updated Vault OIDC page

---

themes/default/content/blog/nx-monorepo/index.md

A few tweaks to uplevel the messaging.

A few updates

---

themes/default/content/learn/embedding-pulumi/building-api/index.md

fix(embedding-tutorial): use correct project name for stack

---

themes/default/content/blog/pulumi-esc-public-preview-for-1password-support/index.md

[Blog][Edit] Pulumi ESC Public Preview for 1Password Support

---

themes/default/static/programs/aws-lambda-stepfunctions-jsonhelper-csharp/aws-lambda-stepfunctions-jsonhelper-csharp.csproj

Add missing AWS Native package to a C# example program.

Adds missing AWS Native package

---

BLOGGING.md

Added a note for the blogger to ensure the meta-image logos are current.

Update blogging guide

---

themes/default/content/blog/developer-portal-gallery/index.md
themes/default/content/blog/esc-editor-enhancements/index.md
themes/default/content/blog/pulumi-ai-new/index.md
themes/default/content/blog/pulumi-esc-public-preview-for-1password-support/index.md
themes/default/content/docs/pulumi-cloud/oidc/azure.md
themes/default/static/programs/aws-iampolicy-jsonparse-go/go.mod.txt

Follow up to #4106, this change just fixes up a few we missed (and fixes another caught by the link checker today).

Fix a few broken links

---

themes/default/content/resources/getting-started-with-iac-on-aws/index.md
themes/default/static/programs/aws-iampolicy-jsonparse-go/go.mod.txt

workshop rescheduled as described in [this comment](https://github.com/pulumi/marketing/issues/979#issuecomment-2027309964)

postpone 4/4 workshop to 5/9

---

themes/default/content/docs/concepts/stack.md
themes/default/content/docs/support/troubleshooting.md

Fixes https://github.com/pulumi/pulumi/issues/15695
Adding details on how to resolve issues when pulumi destroy is unable to remove all provider resources.

adding troubleshooting steps for pulumi destroy

---

themes/default/content/google-next/_index.md
themes/default/content/resources/advanced-cicd-aws-pulumi-github-actions/index.md
themes/default/content/resources/building-ai-powered-applications-at-pulumi/index.md
themes/default/content/resources/deploying-llamaindex-applications-on-aws-with-pulumi/index.md
themes/default/content/resources/serverless-java-production-resilience-and-optimization-gcp/index.md

https://github.com/pulumi/marketing/issues/990
https://github.com/pulumi/marketing/issues/991
https://github.com/pulumi/marketing/issues/993
https://github.com/pulumi/marketing/issues/995

add another batch of april/may workshops to resources

---

themes/default/content/docs/clouds/aws/guides/aws-index-of-services.md

This PR corrects the link for AWS AppSync.

Correct AppSync link

---

themes/default/layouts/partials/docs/footer.html
themes/default/layouts/partials/footer.html

Fixes https://github.com/pulumi/docs/issues/11158.

Make the copyright date dynamic

---

themes/default/content/resources/advanced-cicd-aws-pulumi-github-actions/index.md

Update tags on CICD workshop

---

themes/default/layouts/robots.txt
themes/default/static/programs/aws-lambda-stepfunctions-jsonhelper-go/go.mod.txt

Adds the unpublished sitemap index to the list in robots.txt.

Add the unpublished sitemap to robots.txt

---

themes/default/content/_index.md
themes/default/layouts/index.html

Homepage tagline updated per https://github.com/pulumi/pulumi-hugo/issues/4144 back to "Infrastructure as Code in Any Programming Language"

update homepage h1

---

themes/default/layouts/index.html

Rainbowify the home page header

---

themes/default/config.yml
themes/default/content/docs/esc/faq.md
themes/default/content/docs/esc/get-started/integrate-with-direnv.md
themes/default/content/docs/esc/other-integrations/_index.md
themes/default/content/docs/esc/other-integrations/direnv.md

Add a page that explains how to integrate ESC with Direnv.

Add ESC + Direnv guide

---

themes/default/content/resources/deploying-langchain-apps-on-aws-with-pulumi/index.md

Remove copresenter and the LangSeve

Update `Deploying LangChain Applications on AWS with Pulumi`

---

themes/default/content/community/community-engineering/engin-diri.md

feat: add new talk to my community page

---

themes/default/content/community/community-engineering/engin-diri.md

fix: remove duplicate and reorder a talk

fix: remove duplicate and reorder a talk

---

themes/default/content/docs/concepts/projects/project-file.md
themes/default/content/docs/languages-sdks/python/_index.md

Fixes https://github.com/pulumi/pulumi-hugo/issues/4181.

Add typeChecker to project file and language docs

---

themes/default/content/resources/deploying-llamaindex-applications-on-aws-with-pulumi/index.md

Update workshop `Deploying LlamaIndex Applications on AWS with Pulumi` description

---

themes/default/content/blog/oidc-trust-relationships/index.md

- Fix OIDC connect to OpenID Connect as the former is wrong
- Simplify some language

Fix OpenID and tighten up some language

---

themes/default/content/docs/pulumi-cloud/deployments/schedules.md

adding the steps for schedules from blog

Update schedules.md steps

---

themes/default/layouts/page/pricing.html

fix docs links for new features on the pricing page

fix links on pricing page

---

themes/default/content/blog/deploy-minutes-included/index.md
themes/default/content/blog/infrastructure-lifecycle-management/index.md

Update Customer Quote Link

---

themes/default/content/blog/next-level-iac-pulumi-runtime-logic/index.md

Update pub date index.md

---

themes/default/content/docs/using-pulumi/crossguard/compliance-ready-policies-aws.md
themes/default/content/docs/using-pulumi/crossguard/compliance-ready-policies-awsnative.md

This pull request contains a documentation refresh of the compliance ready policies for aws.

📄 refresh compliance ready policies to include hitrust information

---

themes/default/content/docs/clouds/kubernetes/guides/_index.md

We no longer recommend using this.

Remove reference to kubernetesx

---

themes/default/content/docs/clouds/kubernetes/guides/_index.md

Remove reference to pulumi query

---

themes/default/content/resources/intro-to-iac-azure/index.md
themes/default/content/resources/platform-engineering-with-azure-pulumi/index.md

https://github.com/pulumi/marketing/issues/1031
https://github.com/pulumi/marketing/issues/1027
Will troubleshoot hubspot form issues with @prischoi tomorrow

add azure workshops for june to resources

---

themes/default/content/microsoft-build/_index.md
themes/default/content/resources/microsoft-build/index.md
themes/default/layouts/page/microsoft-build.html

https://github.com/pulumi/marketing/issues/1030
- booth corrected
- added event to resources
- June Azure workshops added to microsite
- Happy Hour registration link added to microsite

updates to microsoft build mcirosite, add event to resources list

---

README.md

Adds an announcement to the readme to communicate the repo's retirement

Update readme with repo retirement date

---

themes/default/content/docs/esc/other-integrations/_index.md
themes/default/content/docs/esc/other-integrations/docker.md

[esc] Add ESC + Docker guide

---

themes/default/content/docs/pulumi-cloud/self-hosted/components/api.md

Adds instructions along with some example configurations for setting up OpenTelemetry in self-hosted instances.

Add docs for configuring OpenTelemetry for self-hosted

---

themes/default/content/docs/pulumi-cloud/cloud-rest-api/_index.md

There are two additional memberAction values no documented promote - promote user to admin
demote - demote user to member

Update `Update Team Membership` documentation

---

themes/default/content/docs/pulumi-cloud/deployments/api.md

Update GetDeployment docs

---

themes/default/content/blog/docker-build/index.md

fixes: https://github.com/pulumi/docs/issues/11440

Fix docker build blog post code example

---

themes/default/content/docs/pulumi-cloud/webhooks.md

fixes: https://github.com/pulumi/docs/issues/11439

Fix pulumi service python package name

---

themes/default/content/docs/esc/other-integrations/_index.md
themes/default/content/docs/esc/other-integrations/terraform.md
themes/default/static/programs/aws-ec2-vpc-resources-go/go.mod.txt
themes/default/static/programs/aws-iampolicy-jsonparse-go/go.mod.txt
themes/default/static/programs/aws-s3-bucket-resources-go/go.mod.txt
themes/default/static/programs/aws-s3-bucketpolicy-jsonstringify-go/go.mod.txt
themes/default/static/programs/aws-simulated-server-interpolate-go/go.mod.txt

Add a page that explains how to integrate ESC with the Terraform CLI.

Add ESC + Terraform guide

---

themes/default/content/blog/next-level-iac-package-ecosystems/index.md

Adds Python code samples to the packages ecosystem post.

Add python code samples to packages ecosystem blog post

---

themes/default/content/resources/building-a-platform-engineering-api-pulumi-automation-api/index.md
themes/default/content/resources/getting-started-with-kubernetes-aws/index.md
themes/default/content/resources/securing-deployments-policy-as-code/index.md

Added to resources:
- https://github.com/pulumi/marketing/issues/1026
- https://github.com/pulumi/marketing/issues/1036 (reusing old workshop page)
- https://github.com/pulumi/marketing/issues/1037 (reusing old workshop page)

add another batch of workshops to resources for June
